// Code generated by "stringer"; DO NOT EDIT.

package screl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DescID-1]
	_ = x[IndexID-2]
	_ = x[ColumnID-3]
	_ = x[ConstraintID-4]
	_ = x[Name-5]
	_ = x[ReferencedDescID-6]
	_ = x[TargetStatus-7]
	_ = x[CurrentStatus-8]
	_ = x[Element-9]
	_ = x[Target-10]
}

const _Attr_name = "DescIDIndexIDColumnIDConstraintIDNameReferencedDescIDTargetStatusCurrentStatusElementTarget"

var _Attr_index = [...]uint8{0, 6, 13, 21, 33, 37, 53, 65, 78, 85, 91}

func (i Attr) String() string {
	i -= 1
	if i < 0 || i >= Attr(len(_Attr_index)-1) {
		return "Attr(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Attr_name[_Attr_index[i]:_Attr_index[i+1]]
}
