// Copyright 2021 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

syntax = "proto3";
package cockroach.util.log.eventpb;
option go_package = "eventpb";

import "gogoproto/gogo.proto";
import "util/log/eventpb/events.proto";

// Category: Job events
// Channel: OPS
//
// Events in this category pertain to long-running jobs that are orchestrated by
// a node's job registry. These system processes can create and/or modify stored
// objects during the course of their execution.
//
// A job might choose to emit multiple events during its execution when
// transitioning from one "state" to another.
// Egs: IMPORT/RESTORE will emit events on job creation and successful
// completion. If the job fails, events will be emitted on job creation,
// failure, and successful revert.

// Import is recorded when an import job is created and successful completion.
// If the job fails, events will be emitted on job creation, failure, and
// successful revert.
message Import {
  CommonEventDetails common = 1 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "", (gogoproto.embed) = true];
  CommonJobEventDetails job = 2 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "", (gogoproto.embed) = true];
}

// Restore is recorded when a restore job is created and successful completion.
// If the job fails, events will be emitted on job creation, failure, and
// successful revert.
message Restore {
  CommonEventDetails common = 1 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "", (gogoproto.embed) = true];
  CommonJobEventDetails job = 2 [(gogoproto.nullable) = false, (gogoproto.jsontag) = "", (gogoproto.embed) = true];
}
