// Copyright 2021 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

syntax = "proto3";
package cockroach.util.timeutil.pgdate;
option go_package = "pgdate";

// DateStyle refers to the PostgreSQL DateStyle allowed variables.
message DateStyle {
  // Style refers to the style to print output dates.
  Style style = 1;
  // Order refers to the order of day, month and year components.
  Order order = 2;
}

// Order refers to the Order component of a DateStyle.
enum Order {
  MDY = 0;
  DMY = 1;
  YMD = 2;
}

// Style refers to the Style component of a DateStyle.
enum Style {
  ISO = 0;
  SQL = 1;
  POSTGRES = 2;
  GERMAN = 3;
}
