[[repos]]
repo = "https://github.com/dnephin/pre-commit-golang"
rev = "v0.5.1"
hooks = [
    { id = "go-fmt", exclude = '\.pb\.go$' },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "go-vet"
name = "go vet"
entry = "bash -c 'go vet -mod=vendor ./pkg/testutils/inproc/ ./pkg/rpc/ ./pkg/server/ ./pkg/storage/'"
language = "system"
types = ["go"]
pass_filenames = false

[[repos.hooks]]
id = "go-build"
name = "go build"
entry = "bash -c 'go build -mod=vendor ./pkg/testutils/inproc/ ./pkg/rpc/ ./pkg/server/ ./pkg/storage/'"
language = "system"
types = ["go"]
pass_filenames = false
