// Code generated by help.awk. DO NOT EDIT.
// GENERATED FILE DO NOT EDIT

package parser

var helpMessages = map[string]HelpMessageBody{
	//line sql.y: 1612
	`ALTER`: {
		//line sql.y: 1613
		Category: hGroup,
		//line sql.y: 1614
		Text: `ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER SEQUENCE, ALTER DATABASE, ALTER USER, ALTER ROLE, ALTER DEFAULT PRIVILEGES, ALTER TENANT
`,
	},
	//line sql.y: 1636
	`ALTER TABLE`: {
		ShortDescription: `change the definition of a table`,
		//line sql.y: 1637
		Category: hDDL,
		//line sql.y: 1638
		Text: `
ALTER TABLE [IF EXISTS] <tablename> <command> [, ...]

Commands:
  ALTER TABLE ... ADD [COLUMN] [IF NOT EXISTS] <colname> <type> [<qualifiers...>]
  ALTER TABLE ... ADD <constraint>
  ALTER TABLE ... DROP [COLUMN] [IF EXISTS] <colname> [RESTRICT | CASCADE]
  ALTER TABLE ... DROP CONSTRAINT [IF EXISTS] <constraintname> [RESTRICT | CASCADE]
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET DEFAULT <expr> | DROP DEFAULT}
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET ON UPDATE <expr> | DROP ON UPDATE}
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP NOT NULL
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP STORED
  ALTER TABLE ... ALTER [COLUMN] <colname> [SET DATA] TYPE <type> [COLLATE <collation>]
  ALTER TABLE ... ALTER PRIMARY KEY USING COLUMNS ( <colnames...> )
  ALTER TABLE ... RENAME TO <newname>
  ALTER TABLE ... RENAME [COLUMN] <colname> TO <newname>
  ALTER TABLE ... VALIDATE CONSTRAINT <constraintname>
  ALTER TABLE ... SET (storage_param = value, ...)
  ALTER TABLE ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER TABLE ... UNSPLIT AT <selectclause>
  ALTER TABLE ... UNSPLIT ALL
  ALTER TABLE ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]
  ALTER TABLE ... INJECT STATISTICS ...  (experimental)
  ALTER TABLE ... RELOCATE [ LEASE | VOTERS | NONVOTERS ] <selectclause>  (experimental)
  ALTER TABLE ... PARTITION BY RANGE ( <name...> ) ( <rangespec> )
  ALTER TABLE ... PARTITION BY LIST ( <name...> ) ( <listspec> )
  ALTER TABLE ... PARTITION BY NOTHING
  ALTER TABLE ... CONFIGURE ZONE <zoneconfig>
  ALTER TABLE ... SET SCHEMA <newschemaname>
  ALTER TABLE ... SET LOCALITY [REGIONAL BY [TABLE IN <region> | ROW] | GLOBAL]

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )]
  COLLATE <collationname>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1681
		SeeAlso: `WEBDOCS/alter-table.html
`,
	},
	//line sql.y: 1697
	`ALTER PARTITION`: {
		ShortDescription: `apply zone configurations to a partition`,
		//line sql.y: 1698
		Category: hDDL,
		//line sql.y: 1699
		Text: `
ALTER PARTITION <name> <command>

Commands:
  -- Alter a single partition which exists on any of a table's indexes.
  ALTER PARTITION <partition> OF TABLE <tablename> CONFIGURE ZONE <zoneconfig>

  -- Alter a partition of a specific index.
  ALTER PARTITION <partition> OF INDEX <tablename>@<indexname> CONFIGURE ZONE <zoneconfig>

  -- Alter all partitions with the same name across a table's indexes.
  ALTER PARTITION <partition> OF INDEX <tablename>@* CONFIGURE ZONE <zoneconfig>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1718
		SeeAlso: `WEBDOCS/configure-zone.html
`,
	},
	//line sql.y: 1723
	`ALTER VIEW`: {
		ShortDescription: `change the definition of a view`,
		//line sql.y: 1724
		Category: hDDL,
		//line sql.y: 1725
		Text: `
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> RENAME TO <newname>
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
		//line sql.y: 1728
		SeeAlso: `WEBDOCS/alter-view.html
`,
	},
	//line sql.y: 1737
	`ALTER SEQUENCE`: {
		ShortDescription: `change the definition of a sequence`,
		//line sql.y: 1738
		Category: hDDL,
		//line sql.y: 1739
		Text: `
ALTER SEQUENCE [IF EXISTS] <name>
  [AS <typename>]
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START <start>]
  [[NO] CYCLE]
ALTER SEQUENCE [IF EXISTS] <name> RENAME TO <newname>
ALTER SEQUENCE [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
	},
	//line sql.y: 1766
	`ALTER DATABASE`: {
		ShortDescription: `change the definition of a database`,
		//line sql.y: 1767
		Category: hDDL,
		//line sql.y: 1768
		Text: `
ALTER DATABASE <name> RENAME TO <newname>
ALTER DATABASE <name> CONFIGURE ZONE <zone config>
ALTER DATABASE <name> OWNER TO <newowner>
ALTER DATABASE <name> CONVERT TO SCHEMA WITH PARENT <name>
ALTER DATABASE <name> ADD REGION [IF NOT EXISTS] <region>
ALTER DATABASE <name> DROP REGION [IF EXISTS] <region>
ALTER DATABASE <name> PRIMARY REGION <region>
ALTER DATABASE <name> SURVIVE <failure type>
ALTER DATABASE <name> PLACEMENT { RESTRICTED | DEFAULT }
ALTER DATABASE <name> SET var { TO | = } { value | DEFAULT }
ALTER DATABASE <name> RESET { var | ALL }
`,
		//line sql.y: 1780
		SeeAlso: `WEBDOCS/alter-database.html
`,
	},
	//line sql.y: 1916
	`ALTER RANGE`: {
		ShortDescription: `change the parameters of a range`,
		//line sql.y: 1917
		Category: hDDL,
		//line sql.y: 1918
		Text: `
ALTER RANGE <zonename> <command>

Commands:
  ALTER RANGE ... CONFIGURE ZONE <zoneconfig>
  ALTER RANGE   RELOCATE { VOTERS | NONVOTERS } FROM <store_id> TO <store_id> FOR <selectclause>
  ALTER RANGE r RELOCATE { VOTERS | NONVOTERS } FROM <store_id> TO <store_id>
  ALTER RANGE   RELOCATE LEASE                                  TO <store_id> FOR <selectclause>
  ALTER RANGE r RELOCATE LEASE                                  TO <store_id>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1934
		SeeAlso: `ALTER TABLE
`,
	},
	//line sql.y: 1940
	`ALTER INDEX`: {
		ShortDescription: `change the definition of an index`,
		//line sql.y: 1941
		Category: hDDL,
		//line sql.y: 1942
		Text: `
ALTER INDEX [IF EXISTS] <idxname> <command>

Commands:
  ALTER INDEX ... RENAME TO <newname>
  ALTER INDEX ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER INDEX ... UNSPLIT AT <selectclause>
  ALTER INDEX ... UNSPLIT ALL
  ALTER INDEX ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]
  ALTER INDEX ... RELOCATE [ LEASE | VOTERS | NONVOTERS ] <selectclause>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1959
		SeeAlso: `WEBDOCS/alter-index.html
`,
	},
	//line sql.y: 2602
	`ALTER TYPE`: {
		ShortDescription: `change the definition of a type.`,
		//line sql.y: 2603
		Category: hDDL,
		//line sql.y: 2604
		Text: `ALTER TYPE <typename> <command>

Commands:
  ALTER TYPE ... ADD VALUE [IF NOT EXISTS] <value> [ { BEFORE | AFTER } <value> ]
  ALTER TYPE ... RENAME VALUE <oldname> TO <newname>
  ALTER TYPE ... RENAME TO <newname>
  ALTER TYPE ... SET SCHEMA <newschemaname>
  ALTER TYPE ... OWNER TO {<newowner> | CURRENT_USER | SESSION_USER }
  ALTER TYPE ... RENAME ATTRIBUTE <oldname> TO <newname> [ CASCADE | RESTRICT ]
  ALTER TYPE ... <attributeaction> [, ... ]

Attribute action:
  ADD ATTRIBUTE <name> <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]
  DROP ATTRIBUTE [IF EXISTS] <name> [ CASCADE | RESTRICT ]
  ALTER ATTRIBUTE <name> [ SET DATA ] TYPE <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]

`,
		//line sql.y: 2620
		SeeAlso: `WEBDOCS/alter-type.html
`,
	},
	//line sql.y: 2769
	`REFRESH`: {
		ShortDescription: `recalculate a materialized view`,
		//line sql.y: 2770
		Category: hMisc,
		//line sql.y: 2771
		Text: `
REFRESH MATERIALIZED VIEW [CONCURRENTLY] view_name [WITH [NO] DATA]
`,
	},
	//line sql.y: 2798
	`BACKUP`: {
		ShortDescription: `back up data to external storage`,
		//line sql.y: 2799
		Category: hCCL,
		//line sql.y: 2800
		Text: `

Create a full backup
BACKUP <targets...> INTO <destination...>
       [ AS OF SYSTEM TIME <expr> ]
			[ WITH <option> [= <value>] [, ...] ]

Append an incremental backup to the most recent backup added to a collection
BACKUP <targets...> INTO LATEST IN <destination...>
       [ AS OF SYSTEM TIME <expr> ]
			[ WITH <option> [= <value>] [, ...] ]


Append an incremental backup in the <subdir>. This command will create an
incremental backup iff there is a full backup in <destination>
BACKUP <targets...> INTO [<subdir...> IN] <destination>
       [ AS OF SYSTEM TIME <expr> ]
			[ WITH <option> [= <value>] [, ...] ]

Targets:
   Empty targets list: backup full cluster.
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Destination:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   revision_history: enable revision history
   encryption_passphrase="secret": encrypt backups
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : encrypt backups using KMS
   detached: execute backup job asynchronously, without waiting for its completion
   incremental_location: specify a different path to store the incremental backup

`,
		//line sql.y: 2834
		SeeAlso: `RESTORE, WEBDOCS/backup.html
`,
	},
	//line sql.y: 2944
	`CREATE SCHEDULE FOR BACKUP`: {
		ShortDescription: `backup data periodically`,
		//line sql.y: 2945
		Category: hCCL,
		//line sql.y: 2946
		Text: `
CREATE SCHEDULE [IF NOT EXISTS]
[<description>]
FOR BACKUP [<targets>] INTO <location...>
[WITH <backup_option>[=<value>] [, ...]]
RECURRING [crontab|NEVER] [FULL BACKUP <crontab|ALWAYS>]
[WITH EXPERIMENTAL SCHEDULE OPTIONS <schedule_option>[= <value>] [, ...] ]

All backups run in UTC timezone.

Description:
  Optional description (or name) for this schedule

Targets:
  empty targets: Backup entire cluster
  DATABASE <pattern> [, ...]: comma separated list of databases to backup.
  TABLE <pattern> [, ...]: comma separated list of tables to backup.

Location:
  "[scheme]://[host]/[path prefix to backup]?[parameters]"
  Backup schedule will create subdirectories under this location to store
  full and periodic backups.

WITH <options>:
  Options specific to BACKUP: See BACKUP options

RECURRING <crontab>:
  The RECURRING expression specifies when we backup.  By default these are incremental
  backups that capture changes since the last backup, writing to the "current" backup.

  Schedule specified as a string in crontab format.
  All times in UTC.
    "5 0 * * *": run schedule 5 minutes past midnight.
    "@daily": run daily, at midnight
  See https://en.wikipedia.org/wiki/Cron

FULL BACKUP <crontab|ALWAYS>:
  The optional FULL BACKUP '<cron expr>' clause specifies when we'll start a new full backup,
  which becomes the "current" backup when complete.
  If FULL BACKUP ALWAYS is specified, then the backups triggered by the RECURRING clause will
  always be full backups. For free users, this is the only accepted value of FULL BACKUP.

  If the FULL BACKUP clause is omitted, we will select a reasonable default:
     * RECURRING <= 1 hour: we default to FULL BACKUP '@daily';
     * RECURRING <= 1 day:  we default to FULL BACKUP '@weekly';
     * Otherwise: we default to FULL BACKUP ALWAYS.

 SCHEDULE OPTIONS:
  The schedule can be modified by specifying the following options (which are considered
  to be experimental at this time):
  * first_run=TIMESTAMPTZ:
    execute the schedule at the specified time. If not specified, the default is to execute
    the scheduled based on it's next RECURRING time.
  * on_execution_failure='[retry|reschedule|pause]':
    If an error occurs during the execution, handle the error based as:
    * retry: retry execution right away
    * reschedule: retry execution by rescheduling it based on its RECURRING expression.
      This is the default.
    * pause: pause this schedule.  Requires manual intervention to unpause.
  * on_previous_running='[start|skip|wait]':
    If the previous backup started by this schedule still running, handle this as:
    * start: start this execution anyway, even if the previous one still running.
    * skip: skip this execution, reschedule it based on RECURRING (or change_capture_period)
      expression.
    * wait: wait for the previous execution to complete.  This is the default.
  * ignore_existing_backups
    If backups were already created in the destination in which a new schedule references,
    this flag must be passed in to acknowledge that the new schedule may be backing up different
    objects.

`,
		//line sql.y: 3016
		SeeAlso: `BACKUP
`,
	},
	//line sql.y: 3101
	`RESTORE`: {
		ShortDescription: `restore data from external storage`,
		//line sql.y: 3102
		Category: hCCL,
		//line sql.y: 3103
		Text: `
RESTORE <targets...> FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]
or
RESTORE SYSTEM USERS FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   into_db: specify target database
   skip_missing_foreign_keys: remove foreign key constraints before restoring
   skip_missing_sequences: ignore sequence dependencies
   skip_missing_views: skip restoring views because of dependencies that cannot be restored
   skip_missing_sequence_owners: remove sequence-table ownership dependencies before restoring
   encryption_passphrase=passphrase: decrypt BACKUP with specified passphrase
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : decrypt backups using KMS
   detached: execute restore job asynchronously, without waiting for its completion
   skip_localities_check: ignore difference of zone configuration between restore cluster and backup cluster
   debug_pause_on: describes the events that the job should pause itself on for debugging purposes.
   new_db_name: renames the restored database. only applies to database restores
`,
		//line sql.y: 3131
		SeeAlso: `BACKUP, WEBDOCS/restore.html
`,
	},
	//line sql.y: 3323
	`IMPORT`: {
		ShortDescription: `load data from file in a distributed manner`,
		//line sql.y: 3324
		Category: hCCL,
		//line sql.y: 3325
		Text: `
-- Import both schema and table data:
IMPORT [ TABLE <tablename> FROM ]
       <format> <datafile>
       [ WITH <option> [= <value>] [, ...] ]

Formats:
   MYSQLDUMP
   PGDUMP

Options:
   distributed = '...'
   sstsize = '...'
   temp = '...'

Use CREATE TABLE followed by IMPORT INTO to create and import into a table
from external files that only have table data.

`,
		//line sql.y: 3343
		SeeAlso: `CREATE TABLE, WEBDOCS/import-into.html
`,
	},
	//line sql.y: 3377
	`EXPORT`: {
		ShortDescription: `export data to file in a distributed manner`,
		//line sql.y: 3378
		Category: hCCL,
		//line sql.y: 3379
		Text: `
EXPORT INTO <format> <datafile> [WITH <option> [= value] [,...]] FROM <query>

Formats:
   CSV
   Parquet

Options:
   delimiter = '...'   [CSV-specific]

`,
		//line sql.y: 3389
		SeeAlso: `SELECT
`,
	},
	//line sql.y: 3577
	`CANCEL`: {
		//line sql.y: 3578
		Category: hGroup,
		//line sql.y: 3579
		Text: `CANCEL JOBS, CANCEL QUERIES, CANCEL SESSIONS
`,
	},
	//line sql.y: 3587
	`CANCEL JOBS`: {
		ShortDescription: `cancel background jobs`,
		//line sql.y: 3588
		Category: hMisc,
		//line sql.y: 3589
		Text: `
CANCEL JOBS <selectclause>
CANCEL JOB <jobid>
`,
		//line sql.y: 3592
		SeeAlso: `SHOW JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 3614
	`CANCEL QUERIES`: {
		ShortDescription: `cancel running queries`,
		//line sql.y: 3615
		Category: hMisc,
		//line sql.y: 3616
		Text: `
CANCEL QUERIES [IF EXISTS] <selectclause>
CANCEL QUERY [IF EXISTS] <expr>
`,
		//line sql.y: 3619
		SeeAlso: `SHOW STATEMENTS
`,
	},
	//line sql.y: 3650
	`CANCEL SESSIONS`: {
		ShortDescription: `cancel open sessions`,
		//line sql.y: 3651
		Category: hMisc,
		//line sql.y: 3652
		Text: `
CANCEL SESSIONS [IF EXISTS] <selectclause>
CANCEL SESSION [IF EXISTS] <sessionid>
`,
		//line sql.y: 3655
		SeeAlso: `SHOW SESSIONS
`,
	},
	//line sql.y: 3686
	`CANCEL ALL JOBS`: {
		//line sql.y: 3687
		Category: hMisc,
		//line sql.y: 3688
		Text: `
CANCEL ALL {BACKUP|CHANGEFEED|IMPORT|RESTORE} JOBS
`,
	},
	//line sql.y: 3747
	`CREATE`: {
		//line sql.y: 3748
		Category: hGroup,
		//line sql.y: 3749
		Text: `
CREATE DATABASE, CREATE TABLE, CREATE INDEX, CREATE TABLE AS,
CREATE USER, CREATE VIEW, CREATE SEQUENCE, CREATE STATISTICS,
CREATE ROLE, CREATE TYPE, CREATE EXTENSION
`,
	},
	//line sql.y: 3765
	`CREATE EXTENSION`: {
		//line sql.y: 3766
		Category: hCfg,
		//line sql.y: 3767
		Text: `CREATE EXTENSION [IF NOT EXISTS] name
`,
	},
	//line sql.y: 3785
	`CREATE FUNCTION`: {
		ShortDescription: `define a new WASM function`,
		//line sql.y: 3786
		Category: hDDL,
		//line sql.y: 3787
		Text: `CREATE FUNCTION <name> ( [<param_name> <type>, ...] ) RETURNS <type> LANGUAGE wasm AS '<wat_source>' IMMUTABLE
`,
	},
	//line sql.y: 3858
	`DROP FUNCTION`: {
		ShortDescription: `remove a function`,
		//line sql.y: 3859
		Category: hDDL,
		//line sql.y: 3860
		Text: `DROP FUNCTION [IF EXISTS] <name> ( [<type>, ...] )
`,
	},
	//line sql.y: 3969
	`CREATE STATISTICS`: {
		ShortDescription: `create a new table statistic`,
		//line sql.y: 3970
		Category: hMisc,
		//line sql.y: 3971
		Text: `
CREATE STATISTICS <statisticname>
  [ON <colname> [, ...]]
  FROM <tablename> [AS OF SYSTEM TIME <expr>]
`,
	},
	//line sql.y: 4064
	`CREATE CHANGEFEED`: {
		ShortDescription: `create change data capture`,
		//line sql.y: 4065
		Category: hCCL,
		//line sql.y: 4066
		Text: `
CREATE CHANGEFEED
FOR <targets> [INTO sink] [WITH <options>]

Sink: Data caputre stream stream destination.  Enterprise only.
`,
	},
	//line sql.y: 4142
	`CREATE REPLICATION STREAM`: {
		ShortDescription: `continuously replicate data`,
		//line sql.y: 4143
		Category: hCCL,
		//line sql.y: 4144
		Text: `
CREATE REPLICATION STREAM FOR <targets> [INTO <sink>] [WITH <options>]

Sink: Replication stream destination.
WITH <options>:
  Options specific to REPLICATION STREAM: See CHANGEFEED options

`,
		//line sql.y: 4151
		SeeAlso: `CREATE CHANGEFEED
`,
	},
	//line sql.y: 4201
	`DELETE`: {
		ShortDescription: `delete rows from a table`,
		//line sql.y: 4202
		Category: hDML,
		//line sql.y: 4203
		Text: `DELETE FROM <tablename> [WHERE <expr>]
              [ORDER BY <exprs...>]
              [LIMIT <expr>]
              [RETURNING <exprs...>]
`,
		//line sql.y: 4207
		SeeAlso: `WEBDOCS/delete.html
`,
	},
	//line sql.y: 4227
	`DISCARD`: {
		ShortDescription: `reset the session to its initial state`,
		//line sql.y: 4228
		Category: hCfg,
		//line sql.y: 4229
		Text: `DISCARD ALL
`,
	},
	//line sql.y: 4241
	`DROP`: {
		//line sql.y: 4242
		Category: hGroup,
		//line sql.y: 4243
		Text: `
DROP DATABASE, DROP INDEX, DROP TABLE, DROP VIEW, DROP SEQUENCE,
DROP USER, DROP ROLE, DROP TYPE
`,
	},
	//line sql.y: 4263
	`DROP VIEW`: {
		ShortDescription: `remove a view`,
		//line sql.y: 4264
		Category: hDDL,
		//line sql.y: 4265
		Text: `DROP [MATERIALIZED] VIEW [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 4266
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 4296
	`DROP SEQUENCE`: {
		ShortDescription: `remove a sequence`,
		//line sql.y: 4297
		Category: hDDL,
		//line sql.y: 4298
		Text: `DROP SEQUENCE [IF EXISTS] <sequenceName> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 4299
		SeeAlso: `DROP
`,
	},
	//line sql.y: 4311
	`DROP TABLE`: {
		ShortDescription: `remove a table`,
		//line sql.y: 4312
		Category: hDDL,
		//line sql.y: 4313
		Text: `DROP TABLE [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 4314
		SeeAlso: `WEBDOCS/drop-table.html
`,
	},
	//line sql.y: 4326
	`DROP INDEX`: {
		ShortDescription: `remove an index`,
		//line sql.y: 4327
		Category: hDDL,
		//line sql.y: 4328
		Text: `DROP INDEX [CONCURRENTLY] [IF EXISTS] <idxname> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 4329
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 4351
	`DROP DATABASE`: {
		ShortDescription: `remove a database`,
		//line sql.y: 4352
		Category: hDDL,
		//line sql.y: 4353
		Text: `DROP DATABASE [IF EXISTS] <databasename> [CASCADE | RESTRICT]
`,
		//line sql.y: 4354
		SeeAlso: `WEBDOCS/drop-database.html
`,
	},
	//line sql.y: 4374
	`DROP TYPE`: {
		ShortDescription: `remove a type`,
		//line sql.y: 4375
		Category: hDDL,
		//line sql.y: 4376
		Text: `DROP TYPE [IF EXISTS] <type_name> [, ...] [CASCASE | RESTRICT]
`,
	},
	//line sql.y: 4412
	`DROP SCHEMA`: {
		ShortDescription: `remove a schema`,
		//line sql.y: 4413
		Category: hDDL,
		//line sql.y: 4414
		Text: `DROP SCHEMA [IF EXISTS] <schema_name> [, ...] [CASCADE | RESTRICT]
`,
	},
	//line sql.y: 4434
	`DROP ROLE`: {
		ShortDescription: `remove a user`,
		//line sql.y: 4435
		Category: hPriv,
		//line sql.y: 4436
		Text: `DROP ROLE [IF EXISTS] <user> [, ...]
`,
		//line sql.y: 4437
		SeeAlso: `CREATE ROLE, SHOW ROLE
`,
	},
	//line sql.y: 4461
	`ANALYZE`: {
		ShortDescription: `collect table statistics`,
		//line sql.y: 4462
		Category: hMisc,
		//line sql.y: 4463
		Text: `
ANALYZE <tablename>

`,
		//line sql.y: 4466
		SeeAlso: `CREATE STATISTICS
`,
	},
	//line sql.y: 4489
	`EXPLAIN`: {
		ShortDescription: `show the logical plan of a query`,
		//line sql.y: 4490
		Category: hMisc,
		//line sql.y: 4491
		Text: `
EXPLAIN <statement>
EXPLAIN ([PLAN ,] <planoptions...> ) <statement>
EXPLAIN (DISTSQL) <statement>
EXPLAIN ANALYZE [(DISTSQL)] <statement>
EXPLAIN ANALYZE (PLAN <planoptions...>) <statement>

Explainable statements:
    SELECT, CREATE, DROP, ALTER, INSERT, UPSERT, UPDATE, DELETE,
    SHOW, EXPLAIN

Plan options:
    TYPES, VERBOSE, OPT

`,
		//line sql.y: 4505
		SeeAlso: `WEBDOCS/explain.html
`,
	},
	//line sql.y: 4616
	`ALTER CHANGEFEED`: {
		ShortDescription: `alter an existing changefeed`,
		//line sql.y: 4617
		Category: hCCL,
		//line sql.y: 4618
		Text: `
ALTER CHANGEFEED <job_id> {{ADD|DROP <targets...>} | SET <options...>}...
`,
	},
	//line sql.y: 4669
	`ALTER BACKUP`: {
		ShortDescription: `alter an existing backup's encryption keys`,
		//line sql.y: 4670
		Category: hCCL,
		//line sql.y: 4671
		Text: `
ALTER BACKUP <location...>
       [ ADD NEW_KMS = <kms...> ]
       [ WITH OLD_KMS = <kms...> ]
Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

KMS:
   "[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : add new kms keys to backup
`,
	},
	//line sql.y: 4725
	`PREPARE`: {
		ShortDescription: `prepare a statement for later execution`,
		//line sql.y: 4726
		Category: hMisc,
		//line sql.y: 4727
		Text: `PREPARE <name> [ ( <types...> ) ] AS <query>
`,
		//line sql.y: 4728
		SeeAlso: `EXECUTE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 4759
	`EXECUTE`: {
		ShortDescription: `execute a statement prepared previously`,
		//line sql.y: 4760
		Category: hMisc,
		//line sql.y: 4761
		Text: `EXECUTE <name> [ ( <exprs...> ) ]
`,
		//line sql.y: 4762
		SeeAlso: `PREPARE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 4792
	`DEALLOCATE`: {
		ShortDescription: `remove a prepared statement`,
		//line sql.y: 4793
		Category: hMisc,
		//line sql.y: 4794
		Text: `DEALLOCATE [PREPARE] { <name> | ALL }
`,
		//line sql.y: 4795
		SeeAlso: `PREPARE, EXECUTE, DISCARD
`,
	},
	//line sql.y: 4815
	`GRANT`: {
		ShortDescription: `define access privileges and role memberships`,
		//line sql.y: 4816
		Category: hPriv,
		//line sql.y: 4817
		Text: `
Grant privileges:
  GRANT {ALL [PRIVILEGES] | <privileges...> } ON <targets...> TO <grantees...>
Grant role membership:
  GRANT <roles...> TO <grantees...> [WITH ADMIN OPTION]

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE

Targets:
  DATABASE <databasename> [, ...]
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  SCHEMA [<databasename> .]<schemaname> [, [<databasename> .]<schemaname>]...
  ALL TABLES IN SCHEMA schema_name [, ...]

`,
		//line sql.y: 4833
		SeeAlso: `REVOKE, WEBDOCS/grant.html
`,
	},
	//line sql.y: 4884
	`REVOKE`: {
		ShortDescription: `remove access privileges and role memberships`,
		//line sql.y: 4885
		Category: hPriv,
		//line sql.y: 4886
		Text: `
Revoke privileges:
  REVOKE {ALL | <privileges...> } ON <targets...> FROM <grantees...>
Revoke role membership:
  REVOKE [ADMIN OPTION FOR] <roles...> FROM <grantees...>

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE

Targets:
  DATABASE <databasename> [, <databasename>]...
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  SCHEMA [<databasename> .]<schemaname> [, [<databasename> .]<schemaname]...
  ALL TABLES IN SCHEMA schema_name [, ...]

`,
		//line sql.y: 4902
		SeeAlso: `GRANT, WEBDOCS/revoke.html
`,
	},
	//line sql.y: 5019
	`RESET`: {
		ShortDescription: `reset a session variable to its default value`,
		//line sql.y: 5020
		Category: hCfg,
		//line sql.y: 5021
		Text: `RESET [SESSION] <var>
`,
		//line sql.y: 5022
		SeeAlso: `RESET CLUSTER SETTING, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 5038
	`RESET CLUSTER SETTING`: {
		ShortDescription: `reset a cluster setting to its default value`,
		//line sql.y: 5039
		Category: hCfg,
		//line sql.y: 5040
		Text: `RESET CLUSTER SETTING <var>
`,
		//line sql.y: 5041
		SeeAlso: `SET CLUSTER SETTING, RESET
`,
	},
	//line sql.y: 5050
	`USE`: {
		ShortDescription: `set the current database`,
		//line sql.y: 5051
		Category: hCfg,
		//line sql.y: 5052
		Text: `USE <dbname>

"USE <dbname>" is an alias for "SET [SESSION] database = <dbname>".
`,
		//line sql.y: 5055
		SeeAlso: `SET SESSION, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 5076
	`SCRUB`: {
		ShortDescription: `run checks against databases or tables`,
		//line sql.y: 5077
		Category: hExperimental,
		//line sql.y: 5078
		Text: `
EXPERIMENTAL SCRUB TABLE <table> ...
EXPERIMENTAL SCRUB DATABASE <database>

The various checks that ca be run with SCRUB includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 5086
		SeeAlso: `SCRUB TABLE, SCRUB DATABASE
`,
	},
	//line sql.y: 5092
	`SCRUB DATABASE`: {
		ShortDescription: `run scrub checks on a database`,
		//line sql.y: 5093
		Category: hExperimental,
		//line sql.y: 5094
		Text: `
EXPERIMENTAL SCRUB DATABASE <database>
                            [AS OF SYSTEM TIME <expr>]

All scrub checks will be run on the database. This includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 5102
		SeeAlso: `SCRUB TABLE, SCRUB
`,
	},
	//line sql.y: 5110
	`SCRUB TABLE`: {
		ShortDescription: `run scrub checks on a table`,
		//line sql.y: 5111
		Category: hExperimental,
		//line sql.y: 5112
		Text: `
SCRUB TABLE <tablename>
            [AS OF SYSTEM TIME <expr>]
            [WITH OPTIONS <option> [, ...]]

Options:
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX (<index>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT (<constraint>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS PHYSICAL
`,
		//line sql.y: 5123
		SeeAlso: `SCRUB DATABASE, SRUB
`,
	},
	//line sql.y: 5178
	`SET CLUSTER SETTING`: {
		ShortDescription: `change a cluster setting`,
		//line sql.y: 5179
		Category: hCfg,
		//line sql.y: 5180
		Text: `SET CLUSTER SETTING <var> { TO | = } <value>
`,
		//line sql.y: 5181
		SeeAlso: `SHOW CLUSTER SETTING, RESET CLUSTER SETTING, SET SESSION, SET LOCAL
WEBDOCS/cluster-settings.html
`,
	},
	//line sql.y: 5190
	`ALTER TENANT`: {
		ShortDescription: `alter tenant configuration`,
		//line sql.y: 5191
		Category: hCfg,
		//line sql.y: 5192
		Text: `
ALTER TENANT { <tenant_id> | ALL } SET CLUSTER SETTING <var> { TO | = } <value>
ALTER TENANT { <tenant_id> | ALL } RESET CLUSTER SETTING <var>
`,
		//line sql.y: 5195
		SeeAlso: `SET CLUSTER SETTING
`,
	},
	//line sql.y: 5232
	`SET SESSION`: {
		ShortDescription: `change a session variable`,
		//line sql.y: 5233
		Category: hCfg,
		//line sql.y: 5234
		Text: `
SET [SESSION] <var> { TO | = } <values...>
SET [SESSION] TIME ZONE <tz>
SET [SESSION] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
SET [SESSION] TRACING { TO | = } { on | off | cluster | kv | results } [,...]

`,
		//line sql.y: 5240
		SeeAlso: `SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION, SET LOCAL
WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 5271
	`SET LOCAL`: {
		ShortDescription: `change a session variable scoped to the current transaction`,
		//line sql.y: 5272
		Category: hCfg,
		//line sql.y: 5273
		Text: `
SET LOCAL <var> { TO | = } <values...>
SET LOCAL TIME ZONE <tz>

`,
		//line sql.y: 5277
		SeeAlso: `SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION, SET SESSION
WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 5288
	`SET TRANSACTION`: {
		ShortDescription: `configure the transaction settings`,
		//line sql.y: 5289
		Category: hTxn,
		//line sql.y: 5290
		Text: `
SET [SESSION] TRANSACTION <txnparameters...>

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }
   AS OF SYSTEM TIME <expr>
   [NOT] DEFERRABLE

`,
		//line sql.y: 5299
		SeeAlso: `SHOW TRANSACTION, SET SESSION, SET LOCAL
WEBDOCS/set-transaction.html
`,
	},
	//line sql.y: 5496
	`SHOW`: {
		//line sql.y: 5497
		Category: hGroup,
		//line sql.y: 5498
		Text: `
SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,
SHOW CREATE, SHOW CREATE SCHEDULES, SHOW DATABASES, SHOW ENUMS, SHOW HISTOGRAM, SHOW INDEXES, SHOW
PARTITIONS, SHOW JOBS, SHOW STATEMENTS, SHOW RANGE, SHOW RANGES, SHOW REGIONS, SHOW SURVIVAL GOAL,
SHOW ROLES, SHOW SCHEMAS, SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS,
SHOW STATISTICS, SHOW SYNTAX, SHOW TABLES, SHOW TRACE, SHOW TRANSACTION,
SHOW TRANSACTIONS, SHOW TRANSFER, SHOW TYPES, SHOW USERS, SHOW LAST QUERY STATISTICS,
SHOW SCHEDULES, SHOW LOCALITY, SHOW ZONE CONFIGURATION, SHOW FULL TABLE SCANS
`,
	},
	//line sql.y: 5550
	`CLOSE`: {
		ShortDescription: `close SQL cursor`,
		//line sql.y: 5551
		Category: hMisc,
		//line sql.y: 5552
		Text: `CLOSE [ ALL | <name> ]
`,
		//line sql.y: 5553
		SeeAlso: `DECLARE, FETCH
`,
	},
	//line sql.y: 5569
	`DECLARE`: {
		ShortDescription: `declare SQL cursor`,
		//line sql.y: 5570
		Category: hMisc,
		//line sql.y: 5571
		Text: `DECLARE <name> [ options ] CURSOR p [ WITH | WITHOUT HOLD ] FOR <query>
`,
		//line sql.y: 5572
		SeeAlso: `CLOSE, FETCH
`,
	},
	//line sql.y: 5641
	`FETCH`: {
		ShortDescription: `fetch rows from a SQL cursor`,
		//line sql.y: 5642
		Category: hMisc,
		//line sql.y: 5643
		Text: `FETCH [ direction [ FROM | IN ] ] <name>
`,
		//line sql.y: 5644
		SeeAlso: `MOVE, CLOSE, DECLARE
`,
	},
	//line sql.y: 5654
	`MOVE`: {
		ShortDescription: `move a SQL cursor without fetching rows`,
		//line sql.y: 5655
		Category: hMisc,
		//line sql.y: 5656
		Text: `MOVE [ direction [ FROM | IN ] ] <name>
`,
		//line sql.y: 5657
		SeeAlso: `FETCH, CLOSE, DECLARE
`,
	},
	//line sql.y: 5793
	`SHOW SESSION`: {
		ShortDescription: `display session variables`,
		//line sql.y: 5794
		Category: hCfg,
		//line sql.y: 5795
		Text: `SHOW [SESSION] { <var> | ALL }
`,
		//line sql.y: 5796
		SeeAlso: `WEBDOCS/show-vars.html
`,
	},
	//line sql.y: 5840
	`SHOW STATISTICS`: {
		ShortDescription: `display table statistics (experimental)`,
		//line sql.y: 5841
		Category: hExperimental,
		//line sql.y: 5842
		Text: `SHOW STATISTICS [USING JSON] FOR TABLE <table_name>

Returns the available statistics for a table.
The statistics can include a histogram ID, which can
be used with SHOW HISTOGRAM.
If USING JSON is specified, the statistics and histograms
are encoded in JSON format.
`,
		//line sql.y: 5849
		SeeAlso: `SHOW HISTOGRAM
`,
	},
	//line sql.y: 5862
	`SHOW HISTOGRAM`: {
		ShortDescription: `display histogram (experimental)`,
		//line sql.y: 5863
		Category: hExperimental,
		//line sql.y: 5864
		Text: `SHOW HISTOGRAM <histogram_id>

Returns the data in the histogram with the
given ID (as returned by SHOW STATISTICS).
`,
		//line sql.y: 5868
		SeeAlso: `SHOW STATISTICS
`,
	},
	//line sql.y: 5881
	`SHOW BACKUP`: {
		ShortDescription: `list backup contents`,
		//line sql.y: 5882
		Category: hCCL,
		//line sql.y: 5883
		Text: `SHOW BACKUP [SCHEMAS|FILES|RANGES] <location>
`,
		//line sql.y: 5884
		SeeAlso: `WEBDOCS/show-backup.html
`,
	},
	//line sql.y: 5963
	`SHOW CLUSTER SETTING`: {
		ShortDescription: `display cluster settings`,
		//line sql.y: 5964
		Category: hCfg,
		//line sql.y: 5965
		Text: `
SHOW CLUSTER SETTING <var> [ FOR TENANT <tenant_id> ]
SHOW [ PUBLIC | ALL ] CLUSTER SETTINGS [ FOR TENANT <tenant_id> ]
`,
		//line sql.y: 5968
		SeeAlso: `WEBDOCS/cluster-settings.html
`,
	},
	//line sql.y: 6014
	`SHOW COLUMNS`: {
		ShortDescription: `list columns in relation`,
		//line sql.y: 6015
		Category: hDDL,
		//line sql.y: 6016
		Text: `SHOW COLUMNS FROM <tablename>
`,
		//line sql.y: 6017
		SeeAlso: `WEBDOCS/show-columns.html
`,
	},
	//line sql.y: 6025
	`SHOW PARTITIONS`: {
		ShortDescription: `list partition information`,
		//line sql.y: 6026
		Category: hDDL,
		//line sql.y: 6027
		Text: `SHOW PARTITIONS FROM { TABLE <table> | INDEX <index> | DATABASE <database> }
`,
		//line sql.y: 6028
		SeeAlso: `WEBDOCS/show-partitions.html
`,
	},
	//line sql.y: 6048
	`SHOW DATABASES`: {
		ShortDescription: `list databases`,
		//line sql.y: 6049
		Category: hDDL,
		//line sql.y: 6050
		Text: `SHOW DATABASES
`,
		//line sql.y: 6051
		SeeAlso: `WEBDOCS/show-databases.html
`,
	},
	//line sql.y: 6059
	`SHOW DEFAULT PRIVILEGES`: {
		ShortDescription: `list default privileges`,
		//line sql.y: 6060
		Category: hDDL,
		//line sql.y: 6061
		Text: `SHOW DEFAULT PRIVILEGES
`,
	},
	//line sql.y: 6077
	`SHOW ENUMS`: {
		ShortDescription: `list enums`,
		//line sql.y: 6078
		Category: hMisc,
		//line sql.y: 6079
		Text: `SHOW ENUMS
`,
	},
	//line sql.y: 6107
	`SHOW TYPES`: {
		ShortDescription: `list user defined types`,
		//line sql.y: 6108
		Category: hMisc,
		//line sql.y: 6109
		Text: `SHOW TYPES
`,
	},
	//line sql.y: 6117
	`SHOW GRANTS`: {
		ShortDescription: `list grants`,
		//line sql.y: 6118
		Category: hPriv,
		//line sql.y: 6119
		Text: `
Show privilege grants:
  SHOW GRANTS [ON <targets...>] [FOR <users...>]
Show role grants:
  SHOW GRANTS ON ROLE [<roles...>] [FOR <grantees...>]

`,
		//line sql.y: 6125
		SeeAlso: `WEBDOCS/show-grants.html
`,
	},
	//line sql.y: 6138
	`SHOW INDEXES`: {
		ShortDescription: `list indexes`,
		//line sql.y: 6139
		Category: hDDL,
		//line sql.y: 6140
		Text: `SHOW INDEXES FROM { <tablename> | DATABASE <database_name> } [WITH COMMENT]
`,
		//line sql.y: 6141
		SeeAlso: `WEBDOCS/show-index.html
`,
	},
	//line sql.y: 6171
	`SHOW CONSTRAINTS`: {
		ShortDescription: `list constraints`,
		//line sql.y: 6172
		Category: hDDL,
		//line sql.y: 6173
		Text: `SHOW CONSTRAINTS FROM <tablename>
`,
		//line sql.y: 6174
		SeeAlso: `WEBDOCS/show-constraints.html
`,
	},
	//line sql.y: 6187
	`SHOW STATEMENTS`: {
		ShortDescription: `list running statements`,
		//line sql.y: 6188
		Category: hMisc,
		//line sql.y: 6189
		Text: `SHOW [ALL] [CLUSTER | LOCAL] STATEMENTS
`,
		//line sql.y: 6190
		SeeAlso: `CANCEL QUERIES
`,
	},
	//line sql.y: 6217
	`SHOW JOBS`: {
		ShortDescription: `list background jobs`,
		//line sql.y: 6218
		Category: hMisc,
		//line sql.y: 6219
		Text: `
SHOW [AUTOMATIC | CHANGEFEED] JOBS [select clause]
SHOW JOBS FOR SCHEDULES [select clause]
SHOW [CHANGEFEED] JOB <jobid>
`,
		//line sql.y: 6223
		SeeAlso: `CANCEL JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 6285
	`SHOW SCHEDULES`: {
		ShortDescription: `list periodic schedules`,
		//line sql.y: 6286
		Category: hMisc,
		//line sql.y: 6287
		Text: `
SHOW [RUNNING | PAUSED] SCHEDULES [FOR BACKUP]
SHOW SCHEDULE <schedule_id>
`,
		//line sql.y: 6290
		SeeAlso: `PAUSE SCHEDULES, RESUME SCHEDULES, DROP SCHEDULES
`,
	},
	//line sql.y: 6341
	`SHOW TRACE`: {
		ShortDescription: `display an execution trace`,
		//line sql.y: 6342
		Category: hMisc,
		//line sql.y: 6343
		Text: `
SHOW [COMPACT] [KV] TRACE FOR SESSION
`,
		//line sql.y: 6345
		SeeAlso: `EXPLAIN
`,
	},
	//line sql.y: 6368
	`SHOW SESSIONS`: {
		ShortDescription: `list open client sessions`,
		//line sql.y: 6369
		Category: hMisc,
		//line sql.y: 6370
		Text: `SHOW [ALL] [CLUSTER | LOCAL] SESSIONS
`,
		//line sql.y: 6371
		SeeAlso: `CANCEL SESSIONS
`,
	},
	//line sql.y: 6384
	`SHOW TABLES`: {
		ShortDescription: `list tables`,
		//line sql.y: 6385
		Category: hDDL,
		//line sql.y: 6386
		Text: `SHOW TABLES [FROM <databasename> [ . <schemaname> ] ] [WITH COMMENT]
`,
		//line sql.y: 6387
		SeeAlso: `WEBDOCS/show-tables.html
`,
	},
	//line sql.y: 6415
	`SHOW TRANSACTIONS`: {
		ShortDescription: `list open client transactions across the cluster`,
		//line sql.y: 6416
		Category: hMisc,
		//line sql.y: 6417
		Text: `SHOW [ALL] [CLUSTER | LOCAL] TRANSACTIONS
`,
	},
	//line sql.y: 6434
	`SHOW SCHEMAS`: {
		ShortDescription: `list schemas`,
		//line sql.y: 6435
		Category: hDDL,
		//line sql.y: 6436
		Text: `SHOW SCHEMAS [FROM <databasename> ]
`,
	},
	//line sql.y: 6448
	`SHOW SEQUENCES`: {
		ShortDescription: `list sequences`,
		//line sql.y: 6449
		Category: hDDL,
		//line sql.y: 6450
		Text: `SHOW SEQUENCES [FROM <databasename> ]
`,
	},
	//line sql.y: 6462
	`SHOW SYNTAX`: {
		ShortDescription: `analyze SQL syntax`,
		//line sql.y: 6463
		Category: hMisc,
		//line sql.y: 6464
		Text: `SHOW SYNTAX <string>
`,
	},
	//line sql.y: 6502
	`SHOW SAVEPOINT`: {
		ShortDescription: `display current savepoint properties`,
		//line sql.y: 6503
		Category: hCfg,
		//line sql.y: 6504
		Text: `SHOW SAVEPOINT STATUS
`,
	},
	//line sql.y: 6512
	`SHOW TRANSACTION`: {
		ShortDescription: `display current transaction properties`,
		//line sql.y: 6513
		Category: hCfg,
		//line sql.y: 6514
		Text: `SHOW TRANSACTION {ISOLATION LEVEL | PRIORITY | STATUS}
`,
		//line sql.y: 6515
		SeeAlso: `WEBDOCS/show-vars.html
`,
	},
	//line sql.y: 6534
	`SHOW TRANSFER`: {
		ShortDescription: `display session state for connection migration`,
		//line sql.y: 6535
		Category: hMisc,
		//line sql.y: 6536
		Text: `SHOW TRANSFER STATE [ WITH '<transfer_key>' ]
`,
	},
	//line sql.y: 6548
	`SHOW CREATE`: {
		ShortDescription: `display the CREATE statement for a table, sequence, view, or database`,
		//line sql.y: 6549
		Category: hDDL,
		//line sql.y: 6550
		Text: `
SHOW CREATE [ TABLE | SEQUENCE | VIEW | DATABASE ] <object_name>
SHOW CREATE ALL SCHEMAS
SHOW CREATE ALL TABLES
SHOW CREATE ALL TYPES
`,
		//line sql.y: 6555
		SeeAlso: `WEBDOCS/show-create.html
`,
	},
	//line sql.y: 6595
	`SHOW CREATE SCHEDULES`: {
		ShortDescription: `list CREATE statements for scheduled jobs`,
		//line sql.y: 6596
		Category: hDDL,
		//line sql.y: 6597
		Text: `
SHOW CREATE ALL SCHEDULES
SHOW CREATE SCHEDULE <schedule_id>
`,
		//line sql.y: 6600
		SeeAlso: `SHOW SCHEDULES, PAUSE SCHEDULES, RESUME SCHEDULES, DROP SCHEDULES
`,
	},
	//line sql.y: 6613
	`SHOW USERS`: {
		ShortDescription: `list defined users`,
		//line sql.y: 6614
		Category: hPriv,
		//line sql.y: 6615
		Text: `SHOW USERS
`,
		//line sql.y: 6616
		SeeAlso: `CREATE USER, DROP USER, WEBDOCS/show-users.html
`,
	},
	//line sql.y: 6624
	`SHOW ROLES`: {
		ShortDescription: `list defined roles`,
		//line sql.y: 6625
		Category: hPriv,
		//line sql.y: 6626
		Text: `SHOW ROLES
`,
		//line sql.y: 6627
		SeeAlso: `CREATE ROLE, ALTER ROLE, DROP ROLE
`,
	},
	//line sql.y: 6635
	`SHOW ZONE CONFIGURATION`: {
		ShortDescription: `display current zone configuration`,
		//line sql.y: 6636
		Category: hCfg,
		//line sql.y: 6637
		Text: `SHOW ZONE CONFIGURATION FROM [ RANGE | DATABASE | TABLE | INDEX ] <name>
SHOW ZONE CONFIGURATION FROM PARTITION OF [ INDEX | TABLE ] <name>
SHOW [ALL] ZONE CONFIGURATIONS
`,
		//line sql.y: 6640
		SeeAlso: `WEBDOCS/show-zone-configurations.html
`,
	},
	//line sql.y: 6696
	`SHOW RANGE`: {
		ShortDescription: `show range information for a row`,
		//line sql.y: 6697
		Category: hMisc,
		//line sql.y: 6698
		Text: `
SHOW RANGE FROM TABLE <tablename> FOR ROW (value1, value2, ...)
SHOW RANGE FROM INDEX [ <tablename> @ ] <indexname> FOR ROW (value1, value2, ...)
`,
	},
	//line sql.y: 6719
	`SHOW RANGES`: {
		ShortDescription: `list ranges`,
		//line sql.y: 6720
		Category: hMisc,
		//line sql.y: 6721
		Text: `
SHOW RANGES FROM TABLE <tablename>
SHOW RANGES FROM INDEX [ <tablename> @ ] <indexname>
`,
	},
	//line sql.y: 6740
	`SHOW SURVIVAL GOAL`: {
		ShortDescription: `shows survival goals`,
		//line sql.y: 6741
		Category: hDDL,
		//line sql.y: 6742
		Text: `
SHOW SURVIVAL GOAL FROM DATABASE
SHOW SURVIVAL GOAL FROM DATABASE <database>
`,
	},
	//line sql.y: 6757
	`SHOW REGIONS`: {
		ShortDescription: `shows regions`,
		//line sql.y: 6758
		Category: hDDL,
		//line sql.y: 6759
		Text: `
SHOW REGIONS
SHOW REGIONS FROM ALL DATABASES
SHOW REGIONS FROM CLUSTER
SHOW REGIONS FROM DATABASE
SHOW REGIONS FROM DATABASE <database>
`,
	},
	//line sql.y: 7064
	`PAUSE`: {
		//line sql.y: 7065
		Category: hMisc,
		//line sql.y: 7066
		Text: `

Pause various background tasks and activities.

PAUSE JOBS, PAUSE SCHEDULES
`,
	},
	//line sql.y: 7077
	`RESUME`: {
		//line sql.y: 7078
		Category: hMisc,
		//line sql.y: 7079
		Text: `

Resume various background tasks and activities.

RESUME JOBS, RESUME SCHEDULES, RESUME ALL BACKUP JOBS
`,
	},
	//line sql.y: 7090
	`RESUME ALL JOBS`: {
		//line sql.y: 7091
		Category: hMisc,
		//line sql.y: 7092
		Text: `
RESUME ALL {BACKUP|CHANGEFEED|IMPORT|RESTORE} JOBS
`,
	},
	//line sql.y: 7101
	`PAUSE JOBS`: {
		ShortDescription: `pause background jobs`,
		//line sql.y: 7102
		Category: hMisc,
		//line sql.y: 7103
		Text: `
PAUSE JOBS <selectclause>
PAUSE JOB <jobid>
`,
		//line sql.y: 7106
		SeeAlso: `SHOW JOBS, CANCEL JOBS, RESUME JOBS
`,
	},
	//line sql.y: 7155
	`PAUSE SCHEDULES`: {
		ShortDescription: `pause scheduled jobs`,
		//line sql.y: 7156
		Category: hMisc,
		//line sql.y: 7157
		Text: `
PAUSE SCHEDULES <selectclause>
  select clause: select statement returning schedule id to pause.
PAUSE SCHEDULE <scheduleID>
`,
		//line sql.y: 7161
		SeeAlso: `RESUME SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
	},
	//line sql.y: 7182
	`PAUSE ALL JOBS`: {
		//line sql.y: 7183
		Category: hMisc,
		//line sql.y: 7184
		Text: `
PAUSE ALL {BACKUP|CHANGEFEED|IMPORT|RESTORE} JOBS
`,
	},
	//line sql.y: 7194
	`CREATE SCHEMA`: {
		ShortDescription: `create a new schema`,
		//line sql.y: 7195
		Category: hDDL,
		//line sql.y: 7196
		Text: `
CREATE SCHEMA [IF NOT EXISTS] { [<databasename>.]<schemaname> | [[<databasename>.]<schemaname>] AUTHORIZATION <rolename> }
`,
	},
	//line sql.y: 7229
	`ALTER SCHEMA`: {
		ShortDescription: `alter an existing schema`,
		//line sql.y: 7230
		Category: hDDL,
		//line sql.y: 7231
		Text: `

Commands:
  ALTER SCHEMA ... RENAME TO <newschemaname>
  ALTER SCHEMA ... OWNER TO {<newowner> | CURRENT_USER | SESSION_USER }
`,
	},
	//line sql.y: 7257
	`CREATE TABLE`: {
		ShortDescription: `create a new table`,
		//line sql.y: 7258
		Category: hDDL,
		//line sql.y: 7259
		Text: `
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> ( <elements...> ) [<on_commit>]
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> [( <colnames...> )] AS <source> [<on commit>]

Table elements:
   <name> <type> [<qualifiers...>]
   [UNIQUE | INVERTED] INDEX [<name>] ( <colname> [ASC | DESC] [, ...] )
                           [USING HASH] [{STORING | INCLUDE | COVERING} ( <colnames...> )]
   FAMILY [<name>] ( <colnames...> )
   [CONSTRAINT <name>] <constraint>

Table constraints:
   PRIMARY KEY ( <colnames...> ) [USING HASH]
   FOREIGN KEY ( <colnames...> ) REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
   UNIQUE ( <colnames...> ) [{STORING | INCLUDE | COVERING} ( <colnames...> )]
   CHECK ( <expr> )

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | NOT VISIBLE | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr> | ON UPDATE <expr> | GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [( <opt_sequence_option_list> )]}
  FAMILY <familyname>, CREATE [IF NOT EXISTS] FAMILY [<familyname>]
  REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
  COLLATE <collationname>
  AS ( <expr> ) { STORED | VIRTUAL }

On commit clause:
   ON COMMIT {PRESERVE ROWS | DROP | DELETE ROWS}

`,
		//line sql.y: 7286
		SeeAlso: `SHOW TABLES, CREATE VIEW, SHOW CREATE,
WEBDOCS/create-table.html
WEBDOCS/create-table-as.html
`,
	},
	//line sql.y: 8222
	`CREATE SEQUENCE`: {
		ShortDescription: `create a new sequence`,
		//line sql.y: 8223
		Category: hDDL,
		//line sql.y: 8224
		Text: `
CREATE [TEMPORARY | TEMP] SEQUENCE <seqname>
  [AS <typename>]
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START [WITH] <start>]
  [CACHE <cache>]
  [NO CYCLE]
  [VIRTUAL]

`,
		//line sql.y: 8235
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 8312
	`TRUNCATE`: {
		ShortDescription: `empty one or more tables`,
		//line sql.y: 8313
		Category: hDML,
		//line sql.y: 8314
		Text: `TRUNCATE [TABLE] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 8315
		SeeAlso: `WEBDOCS/truncate.html
`,
	},
	//line sql.y: 8339
	`CREATE ROLE`: {
		ShortDescription: `define a new role`,
		//line sql.y: 8340
		Category: hPriv,
		//line sql.y: 8341
		Text: `CREATE ROLE [IF NOT EXISTS] <name> [ [WITH] <OPTIONS...> ]
`,
		//line sql.y: 8342
		SeeAlso: `ALTER ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 8354
	`ALTER ROLE`: {
		ShortDescription: `alter a role`,
		//line sql.y: 8355
		Category: hPriv,
		//line sql.y: 8356
		Text: `
ALTER ROLE <name> [WITH] <options...>
ALTER ROLE { name | ALL } [ IN DATABASE database_name ] SET var { TO | = } { value | DEFAULT }
ALTER ROLE { name | ALL } [ IN DATABASE database_name ] RESET { var | ALL }
`,
		//line sql.y: 8360
		SeeAlso: `CREATE ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 8438
	`CREATE VIEW`: {
		ShortDescription: `create a new view`,
		//line sql.y: 8439
		Category: hDDL,
		//line sql.y: 8440
		Text: `CREATE [TEMPORARY | TEMP] [MATERIALIZED] VIEW [IF NOT EXISTS] <viewname> [( <colnames...> )] AS <source>
`,
		//line sql.y: 8441
		SeeAlso: `CREATE TABLE, SHOW CREATE, WEBDOCS/create-view.html
`,
	},
	//line sql.y: 8653
	`CREATE TYPE`: {
		ShortDescription: `- create a type`,
		//line sql.y: 8654
		Category: hDDL,
		//line sql.y: 8655
		Text: `CREATE TYPE [IF NOT EXISTS] <type_name> AS ENUM (...)
`,
	},
	//line sql.y: 8707
	`CREATE INDEX`: {
		ShortDescription: `create a new index`,
		//line sql.y: 8708
		Category: hDDL,
		//line sql.y: 8709
		Text: `
CREATE [UNIQUE | INVERTED] INDEX [CONCURRENTLY] [IF NOT EXISTS] [<idxname>]
       ON <tablename> ( <colname> [ASC | DESC] [, ...] )
       [USING HASH] [STORING ( <colnames...> )]
       [PARTITION BY <partition params>]
       [WITH <storage_parameter_list] [WHERE <where_conds...>]

`,
		//line sql.y: 8716
		SeeAlso: `CREATE TABLE, SHOW INDEXES, SHOW CREATE,
WEBDOCS/create-index.html
`,
	},
	//line sql.y: 9215
	`ALTER DEFAULT PRIVILEGES`: {
		ShortDescription: `alter default privileges on an object`,
		//line sql.y: 9216
		Category: hDDL,
		//line sql.y: 9217
		Text: `

Commands:
  ALTER DEFAULT PRIVILEGES [ FOR { ROLE | USER } target_roles... ] [ IN SCHEMA schema_name...] abbreviated_grant_or_revoke
`,
	},
	//line sql.y: 9364
	`RELEASE`: {
		ShortDescription: `complete a sub-transaction`,
		//line sql.y: 9365
		Category: hTxn,
		//line sql.y: 9366
		Text: `RELEASE [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 9367
		SeeAlso: `SAVEPOINT, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 9375
	`RESUME JOBS`: {
		ShortDescription: `resume background jobs`,
		//line sql.y: 9376
		Category: hMisc,
		//line sql.y: 9377
		Text: `
RESUME JOBS <selectclause>
RESUME JOB <jobid>
`,
		//line sql.y: 9380
		SeeAlso: `SHOW JOBS, CANCEL JOBS, PAUSE JOBS
`,
	},
	//line sql.y: 9402
	`RESUME SCHEDULES`: {
		ShortDescription: `resume executing scheduled jobs`,
		//line sql.y: 9403
		Category: hMisc,
		//line sql.y: 9404
		Text: `
RESUME SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

RESUME SCHEDULE <scheduleID>

`,
		//line sql.y: 9410
		SeeAlso: `PAUSE SCHEDULES, SHOW JOBS, RESUME JOBS
`,
	},
	//line sql.y: 9431
	`DROP SCHEDULES`: {
		ShortDescription: `destroy specified schedules`,
		//line sql.y: 9432
		Category: hMisc,
		//line sql.y: 9433
		Text: `
DROP SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

DROP SCHEDULE <scheduleID>

`,
		//line sql.y: 9439
		SeeAlso: `PAUSE SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
	},
	//line sql.y: 9460
	`SAVEPOINT`: {
		ShortDescription: `start a sub-transaction`,
		//line sql.y: 9461
		Category: hTxn,
		//line sql.y: 9462
		Text: `SAVEPOINT <savepoint name>
`,
		//line sql.y: 9463
		SeeAlso: `RELEASE, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 9478
	`BEGIN`: {
		ShortDescription: `start a transaction`,
		//line sql.y: 9479
		Category: hTxn,
		//line sql.y: 9480
		Text: `
BEGIN [TRANSACTION] [ <txnparameter> [[,] ...] ]
START TRANSACTION [ <txnparameter> [[,] ...] ]

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 9488
		SeeAlso: `COMMIT, ROLLBACK, WEBDOCS/begin-transaction.html
`,
	},
	//line sql.y: 9501
	`COMMIT`: {
		ShortDescription: `commit the current transaction`,
		//line sql.y: 9502
		Category: hTxn,
		//line sql.y: 9503
		Text: `
COMMIT [TRANSACTION]
END [TRANSACTION]
`,
		//line sql.y: 9506
		SeeAlso: `BEGIN, ROLLBACK, WEBDOCS/commit-transaction.html
`,
	},
	//line sql.y: 9530
	`ROLLBACK`: {
		ShortDescription: `abort the current (sub-)transaction`,
		//line sql.y: 9531
		Category: hTxn,
		//line sql.y: 9532
		Text: `
ROLLBACK [TRANSACTION]
ROLLBACK [TRANSACTION] TO [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 9535
		SeeAlso: `BEGIN, COMMIT, SAVEPOINT, WEBDOCS/rollback-transaction.html
`,
	},
	//line sql.y: 9649
	`CREATE DATABASE`: {
		ShortDescription: `create a new database`,
		//line sql.y: 9650
		Category: hDDL,
		//line sql.y: 9651
		Text: `CREATE DATABASE [IF NOT EXISTS] <name>
`,
		//line sql.y: 9652
		SeeAlso: `WEBDOCS/create-database.html
`,
	},
	//line sql.y: 9830
	`INSERT`: {
		ShortDescription: `create new rows in a table`,
		//line sql.y: 9831
		Category: hDML,
		//line sql.y: 9832
		Text: `
INSERT INTO <tablename> [[AS] <name>] [( <colnames...> )]
       <selectclause>
       [ON CONFLICT {
         [( <colnames...> )] [WHERE <arbiter_predicate>] DO NOTHING |
         ( <colnames...> ) [WHERE <index_predicate>] DO UPDATE SET ... [WHERE <expr>]
       }
       [RETURNING <exprs...>]
`,
		//line sql.y: 9840
		SeeAlso: `UPSERT, UPDATE, DELETE, WEBDOCS/insert.html
`,
	},
	//line sql.y: 9859
	`UPSERT`: {
		ShortDescription: `create or replace rows in a table`,
		//line sql.y: 9860
		Category: hDML,
		//line sql.y: 9861
		Text: `
UPSERT INTO <tablename> [AS <name>] [( <colnames...> )]
       <selectclause>
       [RETURNING <exprs...>]
`,
		//line sql.y: 9865
		SeeAlso: `INSERT, UPDATE, DELETE, WEBDOCS/upsert.html
`,
	},
	//line sql.y: 9995
	`UPDATE`: {
		ShortDescription: `update rows of a table`,
		//line sql.y: 9996
		Category: hDML,
		//line sql.y: 9997
		Text: `
UPDATE <tablename> [[AS] <name>]
       SET ...
       [FROM <source>]
       [WHERE <expr>]
       [ORDER BY <exprs...>]
       [LIMIT <expr>]
       [RETURNING <exprs...>]
`,
		//line sql.y: 10005
		SeeAlso: `INSERT, UPSERT, DELETE, WEBDOCS/update.html
`,
	},
	//line sql.y: 10061
	`REASSIGN OWNED BY`: {
		ShortDescription: `change ownership of all objects`,
		//line sql.y: 10062
		Category: hPriv,
		//line sql.y: 10063
		Text: `REASSIGN OWNED BY {<name> | CURRENT_USER | SESSION_USER}[,...]
TO {<name> | CURRENT_USER | SESSION_USER}
`,
		//line sql.y: 10065
		SeeAlso: `DROP OWNED BY
`,
	},
	//line sql.y: 10076
	`DROP OWNED BY`: {
		ShortDescription: `remove database objects owned by role(s).`,
		//line sql.y: 10077
		Category: hPriv,
		//line sql.y: 10078
		Text: `DROP OWNED BY {<name> | CURRENT_USER | SESSION_USER}[,...]
[RESTRICT | CASCADE]
`,
		//line sql.y: 10080
		SeeAlso: `REASSIGN OWNED BY
`,
	},
	//line sql.y: 10260
	`<SELECTCLAUSE>`: {
		ShortDescription: `access tabular data`,
		//line sql.y: 10261
		Category: hDML,
		//line sql.y: 10262
		Text: `
Select clause:
  TABLE <tablename>
  VALUES ( <exprs...> ) [ , ... ]
  SELECT ... [ { INTERSECT | UNION | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
`,
	},
	//line sql.y: 10273
	`SELECT`: {
		ShortDescription: `retrieve rows from a data source and compute a result`,
		//line sql.y: 10274
		Category: hDML,
		//line sql.y: 10275
		Text: `
SELECT [DISTINCT [ ON ( <expr> [ , ... ] ) ] ]
       { <expr> [[AS] <name>] | [ [<dbname>.] <tablename>. ] * } [, ...]
       [ FROM <source> ]
       [ WHERE <expr> ]
       [ GROUP BY <expr> [ , ... ] ]
       [ HAVING <expr> ]
       [ WINDOW <name> AS ( <definition> ) ]
       [ { UNION | INTERSECT | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
       [ ORDER BY <expr> [ ASC | DESC ] [, ...] ]
       [ LIMIT { <expr> | ALL } ]
       [ OFFSET <expr> [ ROW | ROWS ] ]
`,
		//line sql.y: 10287
		SeeAlso: `WEBDOCS/select-clause.html
`,
	},
	//line sql.y: 10362
	`TABLE`: {
		ShortDescription: `select an entire table`,
		//line sql.y: 10363
		Category: hDML,
		//line sql.y: 10364
		Text: `TABLE <tablename>
`,
		//line sql.y: 10365
		SeeAlso: `SELECT, VALUES, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 10727
	`VALUES`: {
		ShortDescription: `select a given set of values`,
		//line sql.y: 10728
		Category: hDML,
		//line sql.y: 10729
		Text: `VALUES ( <exprs...> ) [, ...]
`,
		//line sql.y: 10730
		SeeAlso: `SELECT, TABLE, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 10865
	`<SOURCE>`: {
		ShortDescription: `define a data source for SELECT`,
		//line sql.y: 10866
		Category: hDML,
		//line sql.y: 10867
		Text: `
Data sources:
  <tablename> [ @ { <idxname> | <indexflags> } ]
  <tablefunc> ( <exprs...> )
  ( { <selectclause> | <source> } )
  <source> [AS] <alias> [( <colnames...> )]
  <source> [ <jointype> ] JOIN <source> ON <expr>
  <source> [ <jointype> ] JOIN <source> USING ( <colnames...> )
  <source> NATURAL [ <jointype> ] JOIN <source>
  <source> CROSS JOIN <source>
  <source> WITH ORDINALITY
  '[' EXPLAIN ... ']'
  '[' SHOW ... ']'

Index flags:
  '{' FORCE_INDEX = <idxname> [, ...] '}'
  '{' NO_INDEX_JOIN [, ...] '}'
  '{' NO_ZIGZAG_JOIN [, ...] '}'
  '{' NO_FULL_SCAN [, ...] '}'
  '{' IGNORE_FOREIGN_KEYS [, ...] '}'
  '{' FORCE_ZIGZAG = <idxname> [, ...]  '}'

Join types:
  { INNER | { LEFT | RIGHT | FULL } [OUTER] } [ { HASH | MERGE | LOOKUP | INVERTED } ]

`,
		//line sql.y: 10892
		SeeAlso: `WEBDOCS/table-expressions.html
`,
	},
}
