// Code generated by help.awk. DO NOT EDIT.
// GENERATED FILE DO NOT EDIT

package parser

var helpMessages = map[string]HelpMessageBody{
	//line sql.y: 1610
	`ALTER`: {
		//line sql.y: 1611
		Category: hGroup,
		//line sql.y: 1612
		Text: `ALTER TABLE, ALTER INDEX, ALTER VIEW, ALTER SEQUENCE, ALTER DATABASE, ALTER USER, ALTER ROLE, ALTER DEFAULT PRIVILEGES, ALTER TENANT
`,
	},
	//line sql.y: 1634
	`ALTER TABLE`: {
		ShortDescription: `change the definition of a table`,
		//line sql.y: 1635
		Category: hDDL,
		//line sql.y: 1636
		Text: `
ALTER TABLE [IF EXISTS] <tablename> <command> [, ...]

Commands:
  ALTER TABLE ... ADD [COLUMN] [IF NOT EXISTS] <colname> <type> [<qualifiers...>]
  ALTER TABLE ... ADD <constraint>
  ALTER TABLE ... DROP [COLUMN] [IF EXISTS] <colname> [RESTRICT | CASCADE]
  ALTER TABLE ... DROP CONSTRAINT [IF EXISTS] <constraintname> [RESTRICT | CASCADE]
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET DEFAULT <expr> | DROP DEFAULT}
  ALTER TABLE ... ALTER [COLUMN] <colname> {SET ON UPDATE <expr> | DROP ON UPDATE}
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP NOT NULL
  ALTER TABLE ... ALTER [COLUMN] <colname> DROP STORED
  ALTER TABLE ... ALTER [COLUMN] <colname> [SET DATA] TYPE <type> [COLLATE <collation>]
  ALTER TABLE ... ALTER PRIMARY KEY USING COLUMNS ( <colnames...> )
  ALTER TABLE ... RENAME TO <newname>
  ALTER TABLE ... RENAME [COLUMN] <colname> TO <newname>
  ALTER TABLE ... VALIDATE CONSTRAINT <constraintname>
  ALTER TABLE ... SET (storage_param = value, ...)
  ALTER TABLE ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER TABLE ... UNSPLIT AT <selectclause>
  ALTER TABLE ... UNSPLIT ALL
  ALTER TABLE ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]
  ALTER TABLE ... INJECT STATISTICS ...  (experimental)
  ALTER TABLE ... RELOCATE [ LEASE | VOTERS | NONVOTERS ] <selectclause>  (experimental)
  ALTER TABLE ... PARTITION BY RANGE ( <name...> ) ( <rangespec> )
  ALTER TABLE ... PARTITION BY LIST ( <name...> ) ( <listspec> )
  ALTER TABLE ... PARTITION BY NOTHING
  ALTER TABLE ... CONFIGURE ZONE <zoneconfig>
  ALTER TABLE ... SET SCHEMA <newschemaname>
  ALTER TABLE ... SET LOCALITY [REGIONAL BY [TABLE IN <region> | ROW] | GLOBAL]

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr>}
  REFERENCES <tablename> [( <colnames...> )]
  COLLATE <collationname>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1678
		SeeAlso: `WEBDOCS/alter-table.html
`,
	},
	//line sql.y: 1694
	`ALTER PARTITION`: {
		ShortDescription: `apply zone configurations to a partition`,
		//line sql.y: 1695
		Category: hDDL,
		//line sql.y: 1696
		Text: `
ALTER PARTITION <name> <command>

Commands:
  -- Alter a single partition which exists on any of a table's indexes.
  ALTER PARTITION <partition> OF TABLE <tablename> CONFIGURE ZONE <zoneconfig>

  -- Alter a partition of a specific index.
  ALTER PARTITION <partition> OF INDEX <tablename>@<indexname> CONFIGURE ZONE <zoneconfig>

  -- Alter all partitions with the same name across a table's indexes.
  ALTER PARTITION <partition> OF INDEX <tablename>@* CONFIGURE ZONE <zoneconfig>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1715
		SeeAlso: `WEBDOCS/configure-zone.html
`,
	},
	//line sql.y: 1720
	`ALTER VIEW`: {
		ShortDescription: `change the definition of a view`,
		//line sql.y: 1721
		Category: hDDL,
		//line sql.y: 1722
		Text: `
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> RENAME TO <newname>
ALTER [MATERIALIZED] VIEW [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
		//line sql.y: 1725
		SeeAlso: `WEBDOCS/alter-view.html
`,
	},
	//line sql.y: 1734
	`ALTER SEQUENCE`: {
		ShortDescription: `change the definition of a sequence`,
		//line sql.y: 1735
		Category: hDDL,
		//line sql.y: 1736
		Text: `
ALTER SEQUENCE [IF EXISTS] <name>
  [AS <typename>]
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START <start>]
  [[NO] CYCLE]
ALTER SEQUENCE [IF EXISTS] <name> RENAME TO <newname>
ALTER SEQUENCE [IF EXISTS] <name> SET SCHEMA <newschemaname>
`,
	},
	//line sql.y: 1763
	`ALTER DATABASE`: {
		ShortDescription: `change the definition of a database`,
		//line sql.y: 1764
		Category: hDDL,
		//line sql.y: 1765
		Text: `
ALTER DATABASE <name> RENAME TO <newname>
ALTER DATABASE <name> CONFIGURE ZONE <zone config>
ALTER DATABASE <name> OWNER TO <newowner>
ALTER DATABASE <name> CONVERT TO SCHEMA WITH PARENT <name>
ALTER DATABASE <name> ADD REGION [IF NOT EXISTS] <region>
ALTER DATABASE <name> DROP REGION [IF EXISTS] <region>
ALTER DATABASE <name> PRIMARY REGION <region>
ALTER DATABASE <name> SURVIVE <failure type>
ALTER DATABASE <name> PLACEMENT { RESTRICTED | DEFAULT }
ALTER DATABASE <name> SET var { TO | = } { value | DEFAULT }
ALTER DATABASE <name> RESET { var | ALL }
`,
		//line sql.y: 1777
		SeeAlso: `WEBDOCS/alter-database.html
`,
	},
	//line sql.y: 1913
	`ALTER RANGE`: {
		ShortDescription: `change the parameters of a range`,
		//line sql.y: 1914
		Category: hDDL,
		//line sql.y: 1915
		Text: `
ALTER RANGE <zonename> <command>

Commands:
  ALTER RANGE ... CONFIGURE ZONE <zoneconfig>
  ALTER RANGE   RELOCATE { VOTERS | NONVOTERS } FROM <store_id> TO <store_id> FOR <selectclause>
  ALTER RANGE r RELOCATE { VOTERS | NONVOTERS } FROM <store_id> TO <store_id>
  ALTER RANGE   RELOCATE LEASE                                  TO <store_id> FOR <selectclause>
  ALTER RANGE r RELOCATE LEASE                                  TO <store_id>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1931
		SeeAlso: `ALTER TABLE
`,
	},
	//line sql.y: 1937
	`ALTER INDEX`: {
		ShortDescription: `change the definition of an index`,
		//line sql.y: 1938
		Category: hDDL,
		//line sql.y: 1939
		Text: `
ALTER INDEX [IF EXISTS] <idxname> <command>

Commands:
  ALTER INDEX ... RENAME TO <newname>
  ALTER INDEX ... SPLIT AT <selectclause> [WITH EXPIRATION <expr>]
  ALTER INDEX ... UNSPLIT AT <selectclause>
  ALTER INDEX ... UNSPLIT ALL
  ALTER INDEX ... SCATTER [ FROM ( <exprs...> ) TO ( <exprs...> ) ]
  ALTER INDEX ... RELOCATE [ LEASE | VOTERS | NONVOTERS ] <selectclause>

Zone configurations:
  DISCARD
  USING <var> = <expr> [, ...]
  USING <var> = COPY FROM PARENT [, ...]
  { TO | = } <expr>

`,
		//line sql.y: 1956
		SeeAlso: `WEBDOCS/alter-index.html
`,
	},
	//line sql.y: 2599
	`ALTER TYPE`: {
		ShortDescription: `change the definition of a type.`,
		//line sql.y: 2600
		Category: hDDL,
		//line sql.y: 2601
		Text: `ALTER TYPE <typename> <command>

Commands:
  ALTER TYPE ... ADD VALUE [IF NOT EXISTS] <value> [ { BEFORE | AFTER } <value> ]
  ALTER TYPE ... RENAME VALUE <oldname> TO <newname>
  ALTER TYPE ... RENAME TO <newname>
  ALTER TYPE ... SET SCHEMA <newschemaname>
  ALTER TYPE ... OWNER TO {<newowner> | CURRENT_USER | SESSION_USER }
  ALTER TYPE ... RENAME ATTRIBUTE <oldname> TO <newname> [ CASCADE | RESTRICT ]
  ALTER TYPE ... <attributeaction> [, ... ]

Attribute action:
  ADD ATTRIBUTE <name> <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]
  DROP ATTRIBUTE [IF EXISTS] <name> [ CASCADE | RESTRICT ]
  ALTER ATTRIBUTE <name> [ SET DATA ] TYPE <type> [ COLLATE <collation> ] [ CASCADE | RESTRICT ]

`,
		//line sql.y: 2617
		SeeAlso: `WEBDOCS/alter-type.html
`,
	},
	//line sql.y: 2766
	`REFRESH`: {
		ShortDescription: `recalculate a materialized view`,
		//line sql.y: 2767
		Category: hMisc,
		//line sql.y: 2768
		Text: `
REFRESH MATERIALIZED VIEW [CONCURRENTLY] view_name [WITH [NO] DATA]
`,
	},
	//line sql.y: 2795
	`BACKUP`: {
		ShortDescription: `back up data to external storage`,
		//line sql.y: 2796
		Category: hCCL,
		//line sql.y: 2797
		Text: `

Create a full backup
BACKUP <targets...> INTO <destination...>
       [ AS OF SYSTEM TIME <expr> ]
			[ WITH <option> [= <value>] [, ...] ]

Append an incremental backup to the most recent backup added to a collection
BACKUP <targets...> INTO LATEST IN <destination...>
       [ AS OF SYSTEM TIME <expr> ]
			[ WITH <option> [= <value>] [, ...] ]


Append an incremental backup in the <subdir>. This command will create an
incremental backup iff there is a full backup in <destination>
BACKUP <targets...> INTO [<subdir...> IN] <destination>
       [ AS OF SYSTEM TIME <expr> ]
			[ WITH <option> [= <value>] [, ...] ]

Targets:
   Empty targets list: backup full cluster.
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Destination:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   revision_history: enable revision history
   encryption_passphrase="secret": encrypt backups
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : encrypt backups using KMS
   detached: execute backup job asynchronously, without waiting for its completion
   incremental_location: specify a different path to store the incremental backup

`,
		//line sql.y: 2831
		SeeAlso: `RESTORE, WEBDOCS/backup.html
`,
	},
	//line sql.y: 2941
	`CREATE SCHEDULE FOR BACKUP`: {
		ShortDescription: `backup data periodically`,
		//line sql.y: 2942
		Category: hCCL,
		//line sql.y: 2943
		Text: `
CREATE SCHEDULE [IF NOT EXISTS]
[<description>]
FOR BACKUP [<targets>] INTO <location...>
[WITH <backup_option>[=<value>] [, ...]]
RECURRING [crontab|NEVER] [FULL BACKUP <crontab|ALWAYS>]
[WITH EXPERIMENTAL SCHEDULE OPTIONS <schedule_option>[= <value>] [, ...] ]

All backups run in UTC timezone.

Description:
  Optional description (or name) for this schedule

Targets:
  empty targets: Backup entire cluster
  DATABASE <pattern> [, ...]: comma separated list of databases to backup.
  TABLE <pattern> [, ...]: comma separated list of tables to backup.

Location:
  "[scheme]://[host]/[path prefix to backup]?[parameters]"
  Backup schedule will create subdirectories under this location to store
  full and periodic backups.

WITH <options>:
  Options specific to BACKUP: See BACKUP options

RECURRING <crontab>:
  The RECURRING expression specifies when we backup.  By default these are incremental
  backups that capture changes since the last backup, writing to the "current" backup.

  Schedule specified as a string in crontab format.
  All times in UTC.
    "5 0 * * *": run schedule 5 minutes past midnight.
    "@daily": run daily, at midnight
  See https://en.wikipedia.org/wiki/Cron

FULL BACKUP <crontab|ALWAYS>:
  The optional FULL BACKUP '<cron expr>' clause specifies when we'll start a new full backup,
  which becomes the "current" backup when complete.
  If FULL BACKUP ALWAYS is specified, then the backups triggered by the RECURRING clause will
  always be full backups. For free users, this is the only accepted value of FULL BACKUP.

  If the FULL BACKUP clause is omitted, we will select a reasonable default:
     * RECURRING <= 1 hour: we default to FULL BACKUP '@daily';
     * RECURRING <= 1 day:  we default to FULL BACKUP '@weekly';
     * Otherwise: we default to FULL BACKUP ALWAYS.

 SCHEDULE OPTIONS:
  The schedule can be modified by specifying the following options (which are considered
  to be experimental at this time):
  * first_run=TIMESTAMPTZ:
    execute the schedule at the specified time. If not specified, the default is to execute
    the scheduled based on it's next RECURRING time.
  * on_execution_failure='[retry|reschedule|pause]':
    If an error occurs during the execution, handle the error based as:
    * retry: retry execution right away
    * reschedule: retry execution by rescheduling it based on its RECURRING expression.
      This is the default.
    * pause: pause this schedule.  Requires manual intervention to unpause.
  * on_previous_running='[start|skip|wait]':
    If the previous backup started by this schedule still running, handle this as:
    * start: start this execution anyway, even if the previous one still running.
    * skip: skip this execution, reschedule it based on RECURRING (or change_capture_period)
      expression.
    * wait: wait for the previous execution to complete.  This is the default.
  * ignore_existing_backups
    If backups were already created in the destination in which a new schedule references,
    this flag must be passed in to acknowledge that the new schedule may be backing up different
    objects.

`,
		//line sql.y: 3013
		SeeAlso: `BACKUP
`,
	},
	//line sql.y: 3098
	`RESTORE`: {
		ShortDescription: `restore data from external storage`,
		//line sql.y: 3099
		Category: hCCL,
		//line sql.y: 3100
		Text: `
RESTORE <targets...> FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]
or
RESTORE SYSTEM USERS FROM <location...>
        [ AS OF SYSTEM TIME <expr> ]
        [ WITH <option> [= <value>] [, ...] ]

Targets:
   TABLE <pattern> [, ...]
   DATABASE <databasename> [, ...]

Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

Options:
   into_db: specify target database
   skip_missing_foreign_keys: remove foreign key constraints before restoring
   skip_missing_sequences: ignore sequence dependencies
   skip_missing_views: skip restoring views because of dependencies that cannot be restored
   skip_missing_sequence_owners: remove sequence-table ownership dependencies before restoring
   encryption_passphrase=passphrase: decrypt BACKUP with specified passphrase
   kms="[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : decrypt backups using KMS
   detached: execute restore job asynchronously, without waiting for its completion
   skip_localities_check: ignore difference of zone configuration between restore cluster and backup cluster
   debug_pause_on: describes the events that the job should pause itself on for debugging purposes.
   new_db_name: renames the restored database. only applies to database restores
`,
		//line sql.y: 3128
		SeeAlso: `BACKUP, WEBDOCS/restore.html
`,
	},
	//line sql.y: 3320
	`IMPORT`: {
		ShortDescription: `load data from file in a distributed manner`,
		//line sql.y: 3321
		Category: hCCL,
		//line sql.y: 3322
		Text: `
-- Import both schema and table data:
IMPORT [ TABLE <tablename> FROM ]
       <format> <datafile>
       [ WITH <option> [= <value>] [, ...] ]

Formats:
   MYSQLDUMP
   PGDUMP

Options:
   distributed = '...'
   sstsize = '...'
   temp = '...'

Use CREATE TABLE followed by IMPORT INTO to create and import into a table
from external files that only have table data.

`,
		//line sql.y: 3340
		SeeAlso: `CREATE TABLE, WEBDOCS/import-into.html
`,
	},
	//line sql.y: 3374
	`EXPORT`: {
		ShortDescription: `export data to file in a distributed manner`,
		//line sql.y: 3375
		Category: hCCL,
		//line sql.y: 3376
		Text: `
EXPORT INTO <format> <datafile> [WITH <option> [= value] [,...]] FROM <query>

Formats:
   CSV
   Parquet

Options:
   delimiter = '...'   [CSV-specific]

`,
		//line sql.y: 3386
		SeeAlso: `SELECT
`,
	},
	//line sql.y: 3574
	`CANCEL`: {
		//line sql.y: 3575
		Category: hGroup,
		//line sql.y: 3576
		Text: `CANCEL JOBS, CANCEL QUERIES, CANCEL SESSIONS
`,
	},
	//line sql.y: 3584
	`CANCEL JOBS`: {
		ShortDescription: `cancel background jobs`,
		//line sql.y: 3585
		Category: hMisc,
		//line sql.y: 3586
		Text: `
CANCEL JOBS <selectclause>
CANCEL JOB <jobid>
`,
		//line sql.y: 3589
		SeeAlso: `SHOW JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 3611
	`CANCEL QUERIES`: {
		ShortDescription: `cancel running queries`,
		//line sql.y: 3612
		Category: hMisc,
		//line sql.y: 3613
		Text: `
CANCEL QUERIES [IF EXISTS] <selectclause>
CANCEL QUERY [IF EXISTS] <expr>
`,
		//line sql.y: 3616
		SeeAlso: `SHOW STATEMENTS
`,
	},
	//line sql.y: 3647
	`CANCEL SESSIONS`: {
		ShortDescription: `cancel open sessions`,
		//line sql.y: 3648
		Category: hMisc,
		//line sql.y: 3649
		Text: `
CANCEL SESSIONS [IF EXISTS] <selectclause>
CANCEL SESSION [IF EXISTS] <sessionid>
`,
		//line sql.y: 3652
		SeeAlso: `SHOW SESSIONS
`,
	},
	//line sql.y: 3683
	`CANCEL ALL JOBS`: {
		//line sql.y: 3684
		Category: hMisc,
		//line sql.y: 3685
		Text: `
CANCEL ALL {BACKUP|CHANGEFEED|IMPORT|RESTORE} JOBS
`,
	},
	//line sql.y: 3744
	`CREATE`: {
		//line sql.y: 3745
		Category: hGroup,
		//line sql.y: 3746
		Text: `
CREATE DATABASE, CREATE TABLE, CREATE INDEX, CREATE TABLE AS,
CREATE USER, CREATE VIEW, CREATE SEQUENCE, CREATE STATISTICS,
CREATE ROLE, CREATE TYPE, CREATE EXTENSION
`,
	},
	//line sql.y: 3762
	`CREATE EXTENSION`: {
		//line sql.y: 3763
		Category: hCfg,
		//line sql.y: 3764
		Text: `CREATE EXTENSION [IF NOT EXISTS] name
`,
	},
	//line sql.y: 3782
	`CREATE FUNCTION`: {
		ShortDescription: `define a new WASM function`,
		//line sql.y: 3783
		Category: hDDL,
		//line sql.y: 3784
		Text: `CREATE FUNCTION <name> ( [<param_name> <type>, ...] ) RETURNS <type> LANGUAGE wasm AS '<wat_source>' IMMUTABLE
`,
	},
	//line sql.y: 3866
	`DROP FUNCTION`: {
		ShortDescription: `remove a function`,
		//line sql.y: 3867
		Category: hDDL,
		//line sql.y: 3868
		Text: `DROP FUNCTION [IF EXISTS] <name> ( [<type>, ...] )
`,
	},
	//line sql.y: 3977
	`CREATE STATISTICS`: {
		ShortDescription: `create a new table statistic`,
		//line sql.y: 3978
		Category: hMisc,
		//line sql.y: 3979
		Text: `
CREATE STATISTICS <statisticname>
  [ON <colname> [, ...]]
  FROM <tablename> [AS OF SYSTEM TIME <expr>]
`,
	},
	//line sql.y: 4072
	`CREATE CHANGEFEED`: {
		ShortDescription: `create change data capture`,
		//line sql.y: 4073
		Category: hCCL,
		//line sql.y: 4074
		Text: `
CREATE CHANGEFEED
FOR <targets> [INTO sink] [WITH <options>]

Sink: Data caputre stream stream destination.  Enterprise only.
`,
	},
	//line sql.y: 4150
	`CREATE REPLICATION STREAM`: {
		ShortDescription: `continuously replicate data`,
		//line sql.y: 4151
		Category: hCCL,
		//line sql.y: 4152
		Text: `
CREATE REPLICATION STREAM FOR <targets> [INTO <sink>] [WITH <options>]

Sink: Replication stream destination.
WITH <options>:
  Options specific to REPLICATION STREAM: See CHANGEFEED options

`,
		//line sql.y: 4159
		SeeAlso: `CREATE CHANGEFEED
`,
	},
	//line sql.y: 4209
	`DELETE`: {
		ShortDescription: `delete rows from a table`,
		//line sql.y: 4210
		Category: hDML,
		//line sql.y: 4211
		Text: `DELETE FROM <tablename> [WHERE <expr>]
              [ORDER BY <exprs...>]
              [LIMIT <expr>]
              [RETURNING <exprs...>]
`,
		//line sql.y: 4215
		SeeAlso: `WEBDOCS/delete.html
`,
	},
	//line sql.y: 4235
	`DISCARD`: {
		ShortDescription: `reset the session to its initial state`,
		//line sql.y: 4236
		Category: hCfg,
		//line sql.y: 4237
		Text: `DISCARD ALL
`,
	},
	//line sql.y: 4249
	`DROP`: {
		//line sql.y: 4250
		Category: hGroup,
		//line sql.y: 4251
		Text: `
DROP DATABASE, DROP INDEX, DROP TABLE, DROP VIEW, DROP SEQUENCE,
DROP USER, DROP ROLE, DROP TYPE
`,
	},
	//line sql.y: 4271
	`DROP VIEW`: {
		ShortDescription: `remove a view`,
		//line sql.y: 4272
		Category: hDDL,
		//line sql.y: 4273
		Text: `DROP [MATERIALIZED] VIEW [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 4274
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 4304
	`DROP SEQUENCE`: {
		ShortDescription: `remove a sequence`,
		//line sql.y: 4305
		Category: hDDL,
		//line sql.y: 4306
		Text: `DROP SEQUENCE [IF EXISTS] <sequenceName> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 4307
		SeeAlso: `DROP
`,
	},
	//line sql.y: 4319
	`DROP TABLE`: {
		ShortDescription: `remove a table`,
		//line sql.y: 4320
		Category: hDDL,
		//line sql.y: 4321
		Text: `DROP TABLE [IF EXISTS] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 4322
		SeeAlso: `WEBDOCS/drop-table.html
`,
	},
	//line sql.y: 4334
	`DROP INDEX`: {
		ShortDescription: `remove an index`,
		//line sql.y: 4335
		Category: hDDL,
		//line sql.y: 4336
		Text: `DROP INDEX [CONCURRENTLY] [IF EXISTS] <idxname> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 4337
		SeeAlso: `WEBDOCS/drop-index.html
`,
	},
	//line sql.y: 4359
	`DROP DATABASE`: {
		ShortDescription: `remove a database`,
		//line sql.y: 4360
		Category: hDDL,
		//line sql.y: 4361
		Text: `DROP DATABASE [IF EXISTS] <databasename> [CASCADE | RESTRICT]
`,
		//line sql.y: 4362
		SeeAlso: `WEBDOCS/drop-database.html
`,
	},
	//line sql.y: 4382
	`DROP TYPE`: {
		ShortDescription: `remove a type`,
		//line sql.y: 4383
		Category: hDDL,
		//line sql.y: 4384
		Text: `DROP TYPE [IF EXISTS] <type_name> [, ...] [CASCASE | RESTRICT]
`,
	},
	//line sql.y: 4420
	`DROP SCHEMA`: {
		ShortDescription: `remove a schema`,
		//line sql.y: 4421
		Category: hDDL,
		//line sql.y: 4422
		Text: `DROP SCHEMA [IF EXISTS] <schema_name> [, ...] [CASCADE | RESTRICT]
`,
	},
	//line sql.y: 4442
	`DROP ROLE`: {
		ShortDescription: `remove a user`,
		//line sql.y: 4443
		Category: hPriv,
		//line sql.y: 4444
		Text: `DROP ROLE [IF EXISTS] <user> [, ...]
`,
		//line sql.y: 4445
		SeeAlso: `CREATE ROLE, SHOW ROLE
`,
	},
	//line sql.y: 4469
	`ANALYZE`: {
		ShortDescription: `collect table statistics`,
		//line sql.y: 4470
		Category: hMisc,
		//line sql.y: 4471
		Text: `
ANALYZE <tablename>

`,
		//line sql.y: 4474
		SeeAlso: `CREATE STATISTICS
`,
	},
	//line sql.y: 4497
	`EXPLAIN`: {
		ShortDescription: `show the logical plan of a query`,
		//line sql.y: 4498
		Category: hMisc,
		//line sql.y: 4499
		Text: `
EXPLAIN <statement>
EXPLAIN ([PLAN ,] <planoptions...> ) <statement>
EXPLAIN (DISTSQL) <statement>
EXPLAIN ANALYZE [(DISTSQL)] <statement>
EXPLAIN ANALYZE (PLAN <planoptions...>) <statement>

Explainable statements:
    SELECT, CREATE, DROP, ALTER, INSERT, UPSERT, UPDATE, DELETE,
    SHOW, EXPLAIN

Plan options:
    TYPES, VERBOSE, OPT

`,
		//line sql.y: 4513
		SeeAlso: `WEBDOCS/explain.html
`,
	},
	//line sql.y: 4624
	`ALTER CHANGEFEED`: {
		ShortDescription: `alter an existing changefeed`,
		//line sql.y: 4625
		Category: hCCL,
		//line sql.y: 4626
		Text: `
ALTER CHANGEFEED <job_id> {{ADD|DROP <targets...>} | SET <options...>}...
`,
	},
	//line sql.y: 4677
	`ALTER BACKUP`: {
		ShortDescription: `alter an existing backup's encryption keys`,
		//line sql.y: 4678
		Category: hCCL,
		//line sql.y: 4679
		Text: `
ALTER BACKUP <location...>
       [ ADD NEW_KMS = <kms...> ]
       [ WITH OLD_KMS = <kms...> ]
Locations:
   "[scheme]://[host]/[path to backup]?[parameters]"

KMS:
   "[kms_provider]://[kms_host]/[master_key_identifier]?[parameters]" : add new kms keys to backup
`,
	},
	//line sql.y: 4733
	`PREPARE`: {
		ShortDescription: `prepare a statement for later execution`,
		//line sql.y: 4734
		Category: hMisc,
		//line sql.y: 4735
		Text: `PREPARE <name> [ ( <types...> ) ] AS <query>
`,
		//line sql.y: 4736
		SeeAlso: `EXECUTE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 4767
	`EXECUTE`: {
		ShortDescription: `execute a statement prepared previously`,
		//line sql.y: 4768
		Category: hMisc,
		//line sql.y: 4769
		Text: `EXECUTE <name> [ ( <exprs...> ) ]
`,
		//line sql.y: 4770
		SeeAlso: `PREPARE, DEALLOCATE, DISCARD
`,
	},
	//line sql.y: 4800
	`DEALLOCATE`: {
		ShortDescription: `remove a prepared statement`,
		//line sql.y: 4801
		Category: hMisc,
		//line sql.y: 4802
		Text: `DEALLOCATE [PREPARE] { <name> | ALL }
`,
		//line sql.y: 4803
		SeeAlso: `PREPARE, EXECUTE, DISCARD
`,
	},
	//line sql.y: 4823
	`GRANT`: {
		ShortDescription: `define access privileges and role memberships`,
		//line sql.y: 4824
		Category: hPriv,
		//line sql.y: 4825
		Text: `
Grant privileges:
  GRANT {ALL [PRIVILEGES] | <privileges...> } ON <targets...> TO <grantees...>
Grant role membership:
  GRANT <roles...> TO <grantees...> [WITH ADMIN OPTION]

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE

Targets:
  DATABASE <databasename> [, ...]
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  SCHEMA [<databasename> .]<schemaname> [, [<databasename> .]<schemaname>]...
  ALL TABLES IN SCHEMA schema_name [, ...]

`,
		//line sql.y: 4841
		SeeAlso: `REVOKE, WEBDOCS/grant.html
`,
	},
	//line sql.y: 4892
	`REVOKE`: {
		ShortDescription: `remove access privileges and role memberships`,
		//line sql.y: 4893
		Category: hPriv,
		//line sql.y: 4894
		Text: `
Revoke privileges:
  REVOKE {ALL | <privileges...> } ON <targets...> FROM <grantees...>
Revoke role membership:
  REVOKE [ADMIN OPTION FOR] <roles...> FROM <grantees...>

Privileges:
  CREATE, DROP, GRANT, SELECT, INSERT, DELETE, UPDATE, USAGE

Targets:
  DATABASE <databasename> [, <databasename>]...
  [TABLE] [<databasename> .] { <tablename> | * } [, ...]
  TYPE <typename> [, <typename>]...
  SCHEMA [<databasename> .]<schemaname> [, [<databasename> .]<schemaname]...
  ALL TABLES IN SCHEMA schema_name [, ...]

`,
		//line sql.y: 4910
		SeeAlso: `GRANT, WEBDOCS/revoke.html
`,
	},
	//line sql.y: 5027
	`RESET`: {
		ShortDescription: `reset a session variable to its default value`,
		//line sql.y: 5028
		Category: hCfg,
		//line sql.y: 5029
		Text: `RESET [SESSION] <var>
`,
		//line sql.y: 5030
		SeeAlso: `RESET CLUSTER SETTING, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 5046
	`RESET CLUSTER SETTING`: {
		ShortDescription: `reset a cluster setting to its default value`,
		//line sql.y: 5047
		Category: hCfg,
		//line sql.y: 5048
		Text: `RESET CLUSTER SETTING <var>
`,
		//line sql.y: 5049
		SeeAlso: `SET CLUSTER SETTING, RESET
`,
	},
	//line sql.y: 5058
	`USE`: {
		ShortDescription: `set the current database`,
		//line sql.y: 5059
		Category: hCfg,
		//line sql.y: 5060
		Text: `USE <dbname>

"USE <dbname>" is an alias for "SET [SESSION] database = <dbname>".
`,
		//line sql.y: 5063
		SeeAlso: `SET SESSION, WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 5084
	`SCRUB`: {
		ShortDescription: `run checks against databases or tables`,
		//line sql.y: 5085
		Category: hExperimental,
		//line sql.y: 5086
		Text: `
EXPERIMENTAL SCRUB TABLE <table> ...
EXPERIMENTAL SCRUB DATABASE <database>

The various checks that ca be run with SCRUB includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 5094
		SeeAlso: `SCRUB TABLE, SCRUB DATABASE
`,
	},
	//line sql.y: 5100
	`SCRUB DATABASE`: {
		ShortDescription: `run scrub checks on a database`,
		//line sql.y: 5101
		Category: hExperimental,
		//line sql.y: 5102
		Text: `
EXPERIMENTAL SCRUB DATABASE <database>
                            [AS OF SYSTEM TIME <expr>]

All scrub checks will be run on the database. This includes:
  - Physical table data (encoding)
  - Secondary index integrity
  - Constraint integrity (NOT NULL, CHECK, FOREIGN KEY, UNIQUE)
`,
		//line sql.y: 5110
		SeeAlso: `SCRUB TABLE, SCRUB
`,
	},
	//line sql.y: 5118
	`SCRUB TABLE`: {
		ShortDescription: `run scrub checks on a table`,
		//line sql.y: 5119
		Category: hExperimental,
		//line sql.y: 5120
		Text: `
SCRUB TABLE <tablename>
            [AS OF SYSTEM TIME <expr>]
            [WITH OPTIONS <option> [, ...]]

Options:
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS INDEX (<index>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT ALL
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS CONSTRAINT (<constraint>...)
  EXPERIMENTAL SCRUB TABLE ... WITH OPTIONS PHYSICAL
`,
		//line sql.y: 5131
		SeeAlso: `SCRUB DATABASE, SRUB
`,
	},
	//line sql.y: 5186
	`SET CLUSTER SETTING`: {
		ShortDescription: `change a cluster setting`,
		//line sql.y: 5187
		Category: hCfg,
		//line sql.y: 5188
		Text: `SET CLUSTER SETTING <var> { TO | = } <value>
`,
		//line sql.y: 5189
		SeeAlso: `SHOW CLUSTER SETTING, RESET CLUSTER SETTING, SET SESSION, SET LOCAL
WEBDOCS/cluster-settings.html
`,
	},
	//line sql.y: 5198
	`ALTER TENANT`: {
		ShortDescription: `alter tenant configuration`,
		//line sql.y: 5199
		Category: hCfg,
		//line sql.y: 5200
		Text: `
ALTER TENANT { <tenant_id> | ALL } SET CLUSTER SETTING <var> { TO | = } <value>
ALTER TENANT { <tenant_id> | ALL } RESET CLUSTER SETTING <var>
`,
		//line sql.y: 5203
		SeeAlso: `SET CLUSTER SETTING
`,
	},
	//line sql.y: 5240
	`SET SESSION`: {
		ShortDescription: `change a session variable`,
		//line sql.y: 5241
		Category: hCfg,
		//line sql.y: 5242
		Text: `
SET [SESSION] <var> { TO | = } <values...>
SET [SESSION] TIME ZONE <tz>
SET [SESSION] CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
SET [SESSION] TRACING { TO | = } { on | off | cluster | kv | results } [,...]

`,
		//line sql.y: 5248
		SeeAlso: `SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION, SET LOCAL
WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 5279
	`SET LOCAL`: {
		ShortDescription: `change a session variable scoped to the current transaction`,
		//line sql.y: 5280
		Category: hCfg,
		//line sql.y: 5281
		Text: `
SET LOCAL <var> { TO | = } <values...>
SET LOCAL TIME ZONE <tz>

`,
		//line sql.y: 5285
		SeeAlso: `SHOW SESSION, RESET, DISCARD, SHOW, SET CLUSTER SETTING, SET TRANSACTION, SET SESSION
WEBDOCS/set-vars.html
`,
	},
	//line sql.y: 5296
	`SET TRANSACTION`: {
		ShortDescription: `configure the transaction settings`,
		//line sql.y: 5297
		Category: hTxn,
		//line sql.y: 5298
		Text: `
SET [SESSION] TRANSACTION <txnparameters...>

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }
   AS OF SYSTEM TIME <expr>
   [NOT] DEFERRABLE

`,
		//line sql.y: 5307
		SeeAlso: `SHOW TRANSACTION, SET SESSION, SET LOCAL
WEBDOCS/set-transaction.html
`,
	},
	//line sql.y: 5504
	`SHOW`: {
		//line sql.y: 5505
		Category: hGroup,
		//line sql.y: 5506
		Text: `
SHOW BACKUP, SHOW CLUSTER SETTING, SHOW COLUMNS, SHOW CONSTRAINTS,
SHOW CREATE, SHOW CREATE SCHEDULES, SHOW DATABASES, SHOW ENUMS, SHOW HISTOGRAM, SHOW INDEXES, SHOW
PARTITIONS, SHOW JOBS, SHOW STATEMENTS, SHOW RANGE, SHOW RANGES, SHOW REGIONS, SHOW SURVIVAL GOAL,
SHOW ROLES, SHOW SCHEMAS, SHOW SEQUENCES, SHOW SESSION, SHOW SESSIONS,
SHOW STATISTICS, SHOW SYNTAX, SHOW TABLES, SHOW TRACE, SHOW TRANSACTION,
SHOW TRANSACTIONS, SHOW TRANSFER, SHOW TYPES, SHOW USERS, SHOW LAST QUERY STATISTICS,
SHOW SCHEDULES, SHOW LOCALITY, SHOW ZONE CONFIGURATION, SHOW FULL TABLE SCANS
`,
	},
	//line sql.y: 5558
	`CLOSE`: {
		ShortDescription: `close SQL cursor`,
		//line sql.y: 5559
		Category: hMisc,
		//line sql.y: 5560
		Text: `CLOSE [ ALL | <name> ]
`,
		//line sql.y: 5561
		SeeAlso: `DECLARE, FETCH
`,
	},
	//line sql.y: 5577
	`DECLARE`: {
		ShortDescription: `declare SQL cursor`,
		//line sql.y: 5578
		Category: hMisc,
		//line sql.y: 5579
		Text: `DECLARE <name> [ options ] CURSOR p [ WITH | WITHOUT HOLD ] FOR <query>
`,
		//line sql.y: 5580
		SeeAlso: `CLOSE, FETCH
`,
	},
	//line sql.y: 5649
	`FETCH`: {
		ShortDescription: `fetch rows from a SQL cursor`,
		//line sql.y: 5650
		Category: hMisc,
		//line sql.y: 5651
		Text: `FETCH [ direction [ FROM | IN ] ] <name>
`,
		//line sql.y: 5652
		SeeAlso: `MOVE, CLOSE, DECLARE
`,
	},
	//line sql.y: 5662
	`MOVE`: {
		ShortDescription: `move a SQL cursor without fetching rows`,
		//line sql.y: 5663
		Category: hMisc,
		//line sql.y: 5664
		Text: `MOVE [ direction [ FROM | IN ] ] <name>
`,
		//line sql.y: 5665
		SeeAlso: `FETCH, CLOSE, DECLARE
`,
	},
	//line sql.y: 5801
	`SHOW SESSION`: {
		ShortDescription: `display session variables`,
		//line sql.y: 5802
		Category: hCfg,
		//line sql.y: 5803
		Text: `SHOW [SESSION] { <var> | ALL }
`,
		//line sql.y: 5804
		SeeAlso: `WEBDOCS/show-vars.html
`,
	},
	//line sql.y: 5848
	`SHOW STATISTICS`: {
		ShortDescription: `display table statistics (experimental)`,
		//line sql.y: 5849
		Category: hExperimental,
		//line sql.y: 5850
		Text: `SHOW STATISTICS [USING JSON] FOR TABLE <table_name>

Returns the available statistics for a table.
The statistics can include a histogram ID, which can
be used with SHOW HISTOGRAM.
If USING JSON is specified, the statistics and histograms
are encoded in JSON format.
`,
		//line sql.y: 5857
		SeeAlso: `SHOW HISTOGRAM
`,
	},
	//line sql.y: 5870
	`SHOW HISTOGRAM`: {
		ShortDescription: `display histogram (experimental)`,
		//line sql.y: 5871
		Category: hExperimental,
		//line sql.y: 5872
		Text: `SHOW HISTOGRAM <histogram_id>

Returns the data in the histogram with the
given ID (as returned by SHOW STATISTICS).
`,
		//line sql.y: 5876
		SeeAlso: `SHOW STATISTICS
`,
	},
	//line sql.y: 5889
	`SHOW BACKUP`: {
		ShortDescription: `list backup contents`,
		//line sql.y: 5890
		Category: hCCL,
		//line sql.y: 5891
		Text: `SHOW BACKUP [SCHEMAS|FILES|RANGES] <location>
`,
		//line sql.y: 5892
		SeeAlso: `WEBDOCS/show-backup.html
`,
	},
	//line sql.y: 5971
	`SHOW CLUSTER SETTING`: {
		ShortDescription: `display cluster settings`,
		//line sql.y: 5972
		Category: hCfg,
		//line sql.y: 5973
		Text: `
SHOW CLUSTER SETTING <var> [ FOR TENANT <tenant_id> ]
SHOW [ PUBLIC | ALL ] CLUSTER SETTINGS [ FOR TENANT <tenant_id> ]
`,
		//line sql.y: 5976
		SeeAlso: `WEBDOCS/cluster-settings.html
`,
	},
	//line sql.y: 6022
	`SHOW COLUMNS`: {
		ShortDescription: `list columns in relation`,
		//line sql.y: 6023
		Category: hDDL,
		//line sql.y: 6024
		Text: `SHOW COLUMNS FROM <tablename>
`,
		//line sql.y: 6025
		SeeAlso: `WEBDOCS/show-columns.html
`,
	},
	//line sql.y: 6033
	`SHOW PARTITIONS`: {
		ShortDescription: `list partition information`,
		//line sql.y: 6034
		Category: hDDL,
		//line sql.y: 6035
		Text: `SHOW PARTITIONS FROM { TABLE <table> | INDEX <index> | DATABASE <database> }
`,
		//line sql.y: 6036
		SeeAlso: `WEBDOCS/show-partitions.html
`,
	},
	//line sql.y: 6056
	`SHOW DATABASES`: {
		ShortDescription: `list databases`,
		//line sql.y: 6057
		Category: hDDL,
		//line sql.y: 6058
		Text: `SHOW DATABASES
`,
		//line sql.y: 6059
		SeeAlso: `WEBDOCS/show-databases.html
`,
	},
	//line sql.y: 6067
	`SHOW DEFAULT PRIVILEGES`: {
		ShortDescription: `list default privileges`,
		//line sql.y: 6068
		Category: hDDL,
		//line sql.y: 6069
		Text: `SHOW DEFAULT PRIVILEGES
`,
	},
	//line sql.y: 6085
	`SHOW ENUMS`: {
		ShortDescription: `list enums`,
		//line sql.y: 6086
		Category: hMisc,
		//line sql.y: 6087
		Text: `SHOW ENUMS
`,
	},
	//line sql.y: 6115
	`SHOW TYPES`: {
		ShortDescription: `list user defined types`,
		//line sql.y: 6116
		Category: hMisc,
		//line sql.y: 6117
		Text: `SHOW TYPES
`,
	},
	//line sql.y: 6125
	`SHOW GRANTS`: {
		ShortDescription: `list grants`,
		//line sql.y: 6126
		Category: hPriv,
		//line sql.y: 6127
		Text: `
Show privilege grants:
  SHOW GRANTS [ON <targets...>] [FOR <users...>]
Show role grants:
  SHOW GRANTS ON ROLE [<roles...>] [FOR <grantees...>]

`,
		//line sql.y: 6133
		SeeAlso: `WEBDOCS/show-grants.html
`,
	},
	//line sql.y: 6146
	`SHOW INDEXES`: {
		ShortDescription: `list indexes`,
		//line sql.y: 6147
		Category: hDDL,
		//line sql.y: 6148
		Text: `SHOW INDEXES FROM { <tablename> | DATABASE <database_name> } [WITH COMMENT]
`,
		//line sql.y: 6149
		SeeAlso: `WEBDOCS/show-index.html
`,
	},
	//line sql.y: 6179
	`SHOW CONSTRAINTS`: {
		ShortDescription: `list constraints`,
		//line sql.y: 6180
		Category: hDDL,
		//line sql.y: 6181
		Text: `SHOW CONSTRAINTS FROM <tablename>
`,
		//line sql.y: 6182
		SeeAlso: `WEBDOCS/show-constraints.html
`,
	},
	//line sql.y: 6195
	`SHOW STATEMENTS`: {
		ShortDescription: `list running statements`,
		//line sql.y: 6196
		Category: hMisc,
		//line sql.y: 6197
		Text: `SHOW [ALL] [CLUSTER | LOCAL] STATEMENTS
`,
		//line sql.y: 6198
		SeeAlso: `CANCEL QUERIES
`,
	},
	//line sql.y: 6225
	`SHOW JOBS`: {
		ShortDescription: `list background jobs`,
		//line sql.y: 6226
		Category: hMisc,
		//line sql.y: 6227
		Text: `
SHOW [AUTOMATIC | CHANGEFEED] JOBS [select clause]
SHOW JOBS FOR SCHEDULES [select clause]
SHOW [CHANGEFEED] JOB <jobid>
`,
		//line sql.y: 6231
		SeeAlso: `CANCEL JOBS, PAUSE JOBS, RESUME JOBS
`,
	},
	//line sql.y: 6293
	`SHOW SCHEDULES`: {
		ShortDescription: `list periodic schedules`,
		//line sql.y: 6294
		Category: hMisc,
		//line sql.y: 6295
		Text: `
SHOW [RUNNING | PAUSED] SCHEDULES [FOR BACKUP]
SHOW SCHEDULE <schedule_id>
`,
		//line sql.y: 6298
		SeeAlso: `PAUSE SCHEDULES, RESUME SCHEDULES, DROP SCHEDULES
`,
	},
	//line sql.y: 6349
	`SHOW TRACE`: {
		ShortDescription: `display an execution trace`,
		//line sql.y: 6350
		Category: hMisc,
		//line sql.y: 6351
		Text: `
SHOW [COMPACT] [KV] TRACE FOR SESSION
`,
		//line sql.y: 6353
		SeeAlso: `EXPLAIN
`,
	},
	//line sql.y: 6376
	`SHOW SESSIONS`: {
		ShortDescription: `list open client sessions`,
		//line sql.y: 6377
		Category: hMisc,
		//line sql.y: 6378
		Text: `SHOW [ALL] [CLUSTER | LOCAL] SESSIONS
`,
		//line sql.y: 6379
		SeeAlso: `CANCEL SESSIONS
`,
	},
	//line sql.y: 6392
	`SHOW TABLES`: {
		ShortDescription: `list tables`,
		//line sql.y: 6393
		Category: hDDL,
		//line sql.y: 6394
		Text: `SHOW TABLES [FROM <databasename> [ . <schemaname> ] ] [WITH COMMENT]
`,
		//line sql.y: 6395
		SeeAlso: `WEBDOCS/show-tables.html
`,
	},
	//line sql.y: 6423
	`SHOW TRANSACTIONS`: {
		ShortDescription: `list open client transactions across the cluster`,
		//line sql.y: 6424
		Category: hMisc,
		//line sql.y: 6425
		Text: `SHOW [ALL] [CLUSTER | LOCAL] TRANSACTIONS
`,
	},
	//line sql.y: 6442
	`SHOW SCHEMAS`: {
		ShortDescription: `list schemas`,
		//line sql.y: 6443
		Category: hDDL,
		//line sql.y: 6444
		Text: `SHOW SCHEMAS [FROM <databasename> ]
`,
	},
	//line sql.y: 6456
	`SHOW SEQUENCES`: {
		ShortDescription: `list sequences`,
		//line sql.y: 6457
		Category: hDDL,
		//line sql.y: 6458
		Text: `SHOW SEQUENCES [FROM <databasename> ]
`,
	},
	//line sql.y: 6470
	`SHOW SYNTAX`: {
		ShortDescription: `analyze SQL syntax`,
		//line sql.y: 6471
		Category: hMisc,
		//line sql.y: 6472
		Text: `SHOW SYNTAX <string>
`,
	},
	//line sql.y: 6510
	`SHOW SAVEPOINT`: {
		ShortDescription: `display current savepoint properties`,
		//line sql.y: 6511
		Category: hCfg,
		//line sql.y: 6512
		Text: `SHOW SAVEPOINT STATUS
`,
	},
	//line sql.y: 6520
	`SHOW TRANSACTION`: {
		ShortDescription: `display current transaction properties`,
		//line sql.y: 6521
		Category: hCfg,
		//line sql.y: 6522
		Text: `SHOW TRANSACTION {ISOLATION LEVEL | PRIORITY | STATUS}
`,
		//line sql.y: 6523
		SeeAlso: `WEBDOCS/show-vars.html
`,
	},
	//line sql.y: 6542
	`SHOW TRANSFER`: {
		ShortDescription: `display session state for connection migration`,
		//line sql.y: 6543
		Category: hMisc,
		//line sql.y: 6544
		Text: `SHOW TRANSFER STATE [ WITH '<transfer_key>' ]
`,
	},
	//line sql.y: 6556
	`SHOW CREATE`: {
		ShortDescription: `display the CREATE statement for a table, sequence, view, or database`,
		//line sql.y: 6557
		Category: hDDL,
		//line sql.y: 6558
		Text: `
SHOW CREATE [ TABLE | SEQUENCE | VIEW | DATABASE ] <object_name>
SHOW CREATE ALL SCHEMAS
SHOW CREATE ALL TABLES
SHOW CREATE ALL TYPES
`,
		//line sql.y: 6563
		SeeAlso: `WEBDOCS/show-create.html
`,
	},
	//line sql.y: 6603
	`SHOW CREATE SCHEDULES`: {
		ShortDescription: `list CREATE statements for scheduled jobs`,
		//line sql.y: 6604
		Category: hDDL,
		//line sql.y: 6605
		Text: `
SHOW CREATE ALL SCHEDULES
SHOW CREATE SCHEDULE <schedule_id>
`,
		//line sql.y: 6608
		SeeAlso: `SHOW SCHEDULES, PAUSE SCHEDULES, RESUME SCHEDULES, DROP SCHEDULES
`,
	},
	//line sql.y: 6621
	`SHOW USERS`: {
		ShortDescription: `list defined users`,
		//line sql.y: 6622
		Category: hPriv,
		//line sql.y: 6623
		Text: `SHOW USERS
`,
		//line sql.y: 6624
		SeeAlso: `CREATE USER, DROP USER, WEBDOCS/show-users.html
`,
	},
	//line sql.y: 6632
	`SHOW ROLES`: {
		ShortDescription: `list defined roles`,
		//line sql.y: 6633
		Category: hPriv,
		//line sql.y: 6634
		Text: `SHOW ROLES
`,
		//line sql.y: 6635
		SeeAlso: `CREATE ROLE, ALTER ROLE, DROP ROLE
`,
	},
	//line sql.y: 6643
	`SHOW ZONE CONFIGURATION`: {
		ShortDescription: `display current zone configuration`,
		//line sql.y: 6644
		Category: hCfg,
		//line sql.y: 6645
		Text: `SHOW ZONE CONFIGURATION FROM [ RANGE | DATABASE | TABLE | INDEX ] <name>
SHOW ZONE CONFIGURATION FROM PARTITION OF [ INDEX | TABLE ] <name>
SHOW [ALL] ZONE CONFIGURATIONS
`,
		//line sql.y: 6648
		SeeAlso: `WEBDOCS/show-zone-configurations.html
`,
	},
	//line sql.y: 6704
	`SHOW RANGE`: {
		ShortDescription: `show range information for a row`,
		//line sql.y: 6705
		Category: hMisc,
		//line sql.y: 6706
		Text: `
SHOW RANGE FROM TABLE <tablename> FOR ROW (value1, value2, ...)
SHOW RANGE FROM INDEX [ <tablename> @ ] <indexname> FOR ROW (value1, value2, ...)
`,
	},
	//line sql.y: 6727
	`SHOW RANGES`: {
		ShortDescription: `list ranges`,
		//line sql.y: 6728
		Category: hMisc,
		//line sql.y: 6729
		Text: `
SHOW RANGES FROM TABLE <tablename>
SHOW RANGES FROM INDEX [ <tablename> @ ] <indexname>
`,
	},
	//line sql.y: 6748
	`SHOW SURVIVAL GOAL`: {
		ShortDescription: `shows survival goals`,
		//line sql.y: 6749
		Category: hDDL,
		//line sql.y: 6750
		Text: `
SHOW SURVIVAL GOAL FROM DATABASE
SHOW SURVIVAL GOAL FROM DATABASE <database>
`,
	},
	//line sql.y: 6765
	`SHOW REGIONS`: {
		ShortDescription: `shows regions`,
		//line sql.y: 6766
		Category: hDDL,
		//line sql.y: 6767
		Text: `
SHOW REGIONS
SHOW REGIONS FROM ALL DATABASES
SHOW REGIONS FROM CLUSTER
SHOW REGIONS FROM DATABASE
SHOW REGIONS FROM DATABASE <database>
`,
	},
	//line sql.y: 7072
	`PAUSE`: {
		//line sql.y: 7073
		Category: hMisc,
		//line sql.y: 7074
		Text: `

Pause various background tasks and activities.

PAUSE JOBS, PAUSE SCHEDULES
`,
	},
	//line sql.y: 7085
	`RESUME`: {
		//line sql.y: 7086
		Category: hMisc,
		//line sql.y: 7087
		Text: `

Resume various background tasks and activities.

RESUME JOBS, RESUME SCHEDULES, RESUME ALL BACKUP JOBS
`,
	},
	//line sql.y: 7098
	`RESUME ALL JOBS`: {
		//line sql.y: 7099
		Category: hMisc,
		//line sql.y: 7100
		Text: `
RESUME ALL {BACKUP|CHANGEFEED|IMPORT|RESTORE} JOBS
`,
	},
	//line sql.y: 7109
	`PAUSE JOBS`: {
		ShortDescription: `pause background jobs`,
		//line sql.y: 7110
		Category: hMisc,
		//line sql.y: 7111
		Text: `
PAUSE JOBS <selectclause>
PAUSE JOB <jobid>
`,
		//line sql.y: 7114
		SeeAlso: `SHOW JOBS, CANCEL JOBS, RESUME JOBS
`,
	},
	//line sql.y: 7163
	`PAUSE SCHEDULES`: {
		ShortDescription: `pause scheduled jobs`,
		//line sql.y: 7164
		Category: hMisc,
		//line sql.y: 7165
		Text: `
PAUSE SCHEDULES <selectclause>
  select clause: select statement returning schedule id to pause.
PAUSE SCHEDULE <scheduleID>
`,
		//line sql.y: 7169
		SeeAlso: `RESUME SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
	},
	//line sql.y: 7190
	`PAUSE ALL JOBS`: {
		//line sql.y: 7191
		Category: hMisc,
		//line sql.y: 7192
		Text: `
PAUSE ALL {BACKUP|CHANGEFEED|IMPORT|RESTORE} JOBS
`,
	},
	//line sql.y: 7202
	`CREATE SCHEMA`: {
		ShortDescription: `create a new schema`,
		//line sql.y: 7203
		Category: hDDL,
		//line sql.y: 7204
		Text: `
CREATE SCHEMA [IF NOT EXISTS] { [<databasename>.]<schemaname> | [[<databasename>.]<schemaname>] AUTHORIZATION <rolename> }
`,
	},
	//line sql.y: 7237
	`ALTER SCHEMA`: {
		ShortDescription: `alter an existing schema`,
		//line sql.y: 7238
		Category: hDDL,
		//line sql.y: 7239
		Text: `

Commands:
  ALTER SCHEMA ... RENAME TO <newschemaname>
  ALTER SCHEMA ... OWNER TO {<newowner> | CURRENT_USER | SESSION_USER }
`,
	},
	//line sql.y: 7265
	`CREATE TABLE`: {
		ShortDescription: `create a new table`,
		//line sql.y: 7266
		Category: hDDL,
		//line sql.y: 7267
		Text: `
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> ( <elements...> ) [<on_commit>]
CREATE [[GLOBAL | LOCAL] {TEMPORARY | TEMP}] TABLE [IF NOT EXISTS] <tablename> [( <colnames...> )] AS <source> [<on commit>]

Table elements:
   <name> <type> [<qualifiers...>]
   [UNIQUE | INVERTED] INDEX [<name>] ( <colname> [ASC | DESC] [, ...] )
                           [USING HASH] [{STORING | INCLUDE | COVERING} ( <colnames...> )]
   [CONSTRAINT <name>] <constraint>

Table constraints:
   PRIMARY KEY ( <colnames...> ) [USING HASH]
   FOREIGN KEY ( <colnames...> ) REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
   UNIQUE ( <colnames...> ) [{STORING | INCLUDE | COVERING} ( <colnames...> )]
   CHECK ( <expr> )

Column qualifiers:
  [CONSTRAINT <constraintname>] {NULL | NOT NULL | NOT VISIBLE | UNIQUE | PRIMARY KEY | CHECK (<expr>) | DEFAULT <expr> | ON UPDATE <expr> | GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [( <opt_sequence_option_list> )]}
  REFERENCES <tablename> [( <colnames...> )] [ON DELETE {NO ACTION | RESTRICT}] [ON UPDATE {NO ACTION | RESTRICT}]
  COLLATE <collationname>
  AS ( <expr> ) { STORED | VIRTUAL }

On commit clause:
   ON COMMIT {PRESERVE ROWS | DROP | DELETE ROWS}

`,
		//line sql.y: 7292
		SeeAlso: `SHOW TABLES, CREATE VIEW, SHOW CREATE,
WEBDOCS/create-table.html
WEBDOCS/create-table-as.html
`,
	},
	//line sql.y: 8193
	`CREATE SEQUENCE`: {
		ShortDescription: `create a new sequence`,
		//line sql.y: 8194
		Category: hDDL,
		//line sql.y: 8195
		Text: `
CREATE [TEMPORARY | TEMP] SEQUENCE <seqname>
  [AS <typename>]
  [INCREMENT <increment>]
  [MINVALUE <minvalue> | NO MINVALUE]
  [MAXVALUE <maxvalue> | NO MAXVALUE]
  [START [WITH] <start>]
  [CACHE <cache>]
  [NO CYCLE]
  [VIRTUAL]

`,
		//line sql.y: 8206
		SeeAlso: `CREATE TABLE
`,
	},
	//line sql.y: 8283
	`TRUNCATE`: {
		ShortDescription: `empty one or more tables`,
		//line sql.y: 8284
		Category: hDML,
		//line sql.y: 8285
		Text: `TRUNCATE [TABLE] <tablename> [, ...] [CASCADE | RESTRICT]
`,
		//line sql.y: 8286
		SeeAlso: `WEBDOCS/truncate.html
`,
	},
	//line sql.y: 8310
	`CREATE ROLE`: {
		ShortDescription: `define a new role`,
		//line sql.y: 8311
		Category: hPriv,
		//line sql.y: 8312
		Text: `CREATE ROLE [IF NOT EXISTS] <name> [ [WITH] <OPTIONS...> ]
`,
		//line sql.y: 8313
		SeeAlso: `ALTER ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 8325
	`ALTER ROLE`: {
		ShortDescription: `alter a role`,
		//line sql.y: 8326
		Category: hPriv,
		//line sql.y: 8327
		Text: `
ALTER ROLE <name> [WITH] <options...>
ALTER ROLE { name | ALL } [ IN DATABASE database_name ] SET var { TO | = } { value | DEFAULT }
ALTER ROLE { name | ALL } [ IN DATABASE database_name ] RESET { var | ALL }
`,
		//line sql.y: 8331
		SeeAlso: `CREATE ROLE, DROP ROLE, SHOW ROLES
`,
	},
	//line sql.y: 8409
	`CREATE VIEW`: {
		ShortDescription: `create a new view`,
		//line sql.y: 8410
		Category: hDDL,
		//line sql.y: 8411
		Text: `CREATE [TEMPORARY | TEMP] [MATERIALIZED] VIEW [IF NOT EXISTS] <viewname> [( <colnames...> )] AS <source>
`,
		//line sql.y: 8412
		SeeAlso: `CREATE TABLE, SHOW CREATE, WEBDOCS/create-view.html
`,
	},
	//line sql.y: 8624
	`CREATE TYPE`: {
		ShortDescription: `- create a type`,
		//line sql.y: 8625
		Category: hDDL,
		//line sql.y: 8626
		Text: `CREATE TYPE [IF NOT EXISTS] <type_name> AS ENUM (...)
`,
	},
	//line sql.y: 8678
	`CREATE INDEX`: {
		ShortDescription: `create a new index`,
		//line sql.y: 8679
		Category: hDDL,
		//line sql.y: 8680
		Text: `
CREATE [UNIQUE | INVERTED] INDEX [CONCURRENTLY] [IF NOT EXISTS] [<idxname>]
       ON <tablename> ( <colname> [ASC | DESC] [, ...] )
       [USING HASH] [STORING ( <colnames...> )]
       [PARTITION BY <partition params>]
       [WITH <storage_parameter_list] [WHERE <where_conds...>]

`,
		//line sql.y: 8687
		SeeAlso: `CREATE TABLE, SHOW INDEXES, SHOW CREATE,
WEBDOCS/create-index.html
`,
	},
	//line sql.y: 9186
	`ALTER DEFAULT PRIVILEGES`: {
		ShortDescription: `alter default privileges on an object`,
		//line sql.y: 9187
		Category: hDDL,
		//line sql.y: 9188
		Text: `

Commands:
  ALTER DEFAULT PRIVILEGES [ FOR { ROLE | USER } target_roles... ] [ IN SCHEMA schema_name...] abbreviated_grant_or_revoke
`,
	},
	//line sql.y: 9335
	`RELEASE`: {
		ShortDescription: `complete a sub-transaction`,
		//line sql.y: 9336
		Category: hTxn,
		//line sql.y: 9337
		Text: `RELEASE [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 9338
		SeeAlso: `SAVEPOINT, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 9346
	`RESUME JOBS`: {
		ShortDescription: `resume background jobs`,
		//line sql.y: 9347
		Category: hMisc,
		//line sql.y: 9348
		Text: `
RESUME JOBS <selectclause>
RESUME JOB <jobid>
`,
		//line sql.y: 9351
		SeeAlso: `SHOW JOBS, CANCEL JOBS, PAUSE JOBS
`,
	},
	//line sql.y: 9373
	`RESUME SCHEDULES`: {
		ShortDescription: `resume executing scheduled jobs`,
		//line sql.y: 9374
		Category: hMisc,
		//line sql.y: 9375
		Text: `
RESUME SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

RESUME SCHEDULE <scheduleID>

`,
		//line sql.y: 9381
		SeeAlso: `PAUSE SCHEDULES, SHOW JOBS, RESUME JOBS
`,
	},
	//line sql.y: 9402
	`DROP SCHEDULES`: {
		ShortDescription: `destroy specified schedules`,
		//line sql.y: 9403
		Category: hMisc,
		//line sql.y: 9404
		Text: `
DROP SCHEDULES <selectclause>
 selectclause: select statement returning schedule IDs to resume.

DROP SCHEDULE <scheduleID>

`,
		//line sql.y: 9410
		SeeAlso: `PAUSE SCHEDULES, SHOW JOBS, CANCEL JOBS
`,
	},
	//line sql.y: 9431
	`SAVEPOINT`: {
		ShortDescription: `start a sub-transaction`,
		//line sql.y: 9432
		Category: hTxn,
		//line sql.y: 9433
		Text: `SAVEPOINT <savepoint name>
`,
		//line sql.y: 9434
		SeeAlso: `RELEASE, WEBDOCS/savepoint.html
`,
	},
	//line sql.y: 9449
	`BEGIN`: {
		ShortDescription: `start a transaction`,
		//line sql.y: 9450
		Category: hTxn,
		//line sql.y: 9451
		Text: `
BEGIN [TRANSACTION] [ <txnparameter> [[,] ...] ]
START TRANSACTION [ <txnparameter> [[,] ...] ]

Transaction parameters:
   ISOLATION LEVEL { SNAPSHOT | SERIALIZABLE }
   PRIORITY { LOW | NORMAL | HIGH }

`,
		//line sql.y: 9459
		SeeAlso: `COMMIT, ROLLBACK, WEBDOCS/begin-transaction.html
`,
	},
	//line sql.y: 9472
	`COMMIT`: {
		ShortDescription: `commit the current transaction`,
		//line sql.y: 9473
		Category: hTxn,
		//line sql.y: 9474
		Text: `
COMMIT [TRANSACTION]
END [TRANSACTION]
`,
		//line sql.y: 9477
		SeeAlso: `BEGIN, ROLLBACK, WEBDOCS/commit-transaction.html
`,
	},
	//line sql.y: 9501
	`ROLLBACK`: {
		ShortDescription: `abort the current (sub-)transaction`,
		//line sql.y: 9502
		Category: hTxn,
		//line sql.y: 9503
		Text: `
ROLLBACK [TRANSACTION]
ROLLBACK [TRANSACTION] TO [SAVEPOINT] <savepoint name>
`,
		//line sql.y: 9506
		SeeAlso: `BEGIN, COMMIT, SAVEPOINT, WEBDOCS/rollback-transaction.html
`,
	},
	//line sql.y: 9620
	`CREATE DATABASE`: {
		ShortDescription: `create a new database`,
		//line sql.y: 9621
		Category: hDDL,
		//line sql.y: 9622
		Text: `CREATE DATABASE [IF NOT EXISTS] <name>
`,
		//line sql.y: 9623
		SeeAlso: `WEBDOCS/create-database.html
`,
	},
	//line sql.y: 9801
	`INSERT`: {
		ShortDescription: `create new rows in a table`,
		//line sql.y: 9802
		Category: hDML,
		//line sql.y: 9803
		Text: `
INSERT INTO <tablename> [[AS] <name>] [( <colnames...> )]
       <selectclause>
       [ON CONFLICT {
         [( <colnames...> )] [WHERE <arbiter_predicate>] DO NOTHING |
         ( <colnames...> ) [WHERE <index_predicate>] DO UPDATE SET ... [WHERE <expr>]
       }
       [RETURNING <exprs...>]
`,
		//line sql.y: 9811
		SeeAlso: `UPSERT, UPDATE, DELETE, WEBDOCS/insert.html
`,
	},
	//line sql.y: 9830
	`UPSERT`: {
		ShortDescription: `create or replace rows in a table`,
		//line sql.y: 9831
		Category: hDML,
		//line sql.y: 9832
		Text: `
UPSERT INTO <tablename> [AS <name>] [( <colnames...> )]
       <selectclause>
       [RETURNING <exprs...>]
`,
		//line sql.y: 9836
		SeeAlso: `INSERT, UPDATE, DELETE, WEBDOCS/upsert.html
`,
	},
	//line sql.y: 9966
	`UPDATE`: {
		ShortDescription: `update rows of a table`,
		//line sql.y: 9967
		Category: hDML,
		//line sql.y: 9968
		Text: `
UPDATE <tablename> [[AS] <name>]
       SET ...
       [FROM <source>]
       [WHERE <expr>]
       [ORDER BY <exprs...>]
       [LIMIT <expr>]
       [RETURNING <exprs...>]
`,
		//line sql.y: 9976
		SeeAlso: `INSERT, UPSERT, DELETE, WEBDOCS/update.html
`,
	},
	//line sql.y: 10032
	`REASSIGN OWNED BY`: {
		ShortDescription: `change ownership of all objects`,
		//line sql.y: 10033
		Category: hPriv,
		//line sql.y: 10034
		Text: `REASSIGN OWNED BY {<name> | CURRENT_USER | SESSION_USER}[,...]
TO {<name> | CURRENT_USER | SESSION_USER}
`,
		//line sql.y: 10036
		SeeAlso: `DROP OWNED BY
`,
	},
	//line sql.y: 10047
	`DROP OWNED BY`: {
		ShortDescription: `remove database objects owned by role(s).`,
		//line sql.y: 10048
		Category: hPriv,
		//line sql.y: 10049
		Text: `DROP OWNED BY {<name> | CURRENT_USER | SESSION_USER}[,...]
[RESTRICT | CASCADE]
`,
		//line sql.y: 10051
		SeeAlso: `REASSIGN OWNED BY
`,
	},
	//line sql.y: 10231
	`<SELECTCLAUSE>`: {
		ShortDescription: `access tabular data`,
		//line sql.y: 10232
		Category: hDML,
		//line sql.y: 10233
		Text: `
Select clause:
  TABLE <tablename>
  VALUES ( <exprs...> ) [ , ... ]
  SELECT ... [ { INTERSECT | UNION | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
`,
	},
	//line sql.y: 10244
	`SELECT`: {
		ShortDescription: `retrieve rows from a data source and compute a result`,
		//line sql.y: 10245
		Category: hDML,
		//line sql.y: 10246
		Text: `
SELECT [DISTINCT [ ON ( <expr> [ , ... ] ) ] ]
       { <expr> [[AS] <name>] | [ [<dbname>.] <tablename>. ] * } [, ...]
       [ FROM <source> ]
       [ WHERE <expr> ]
       [ GROUP BY <expr> [ , ... ] ]
       [ HAVING <expr> ]
       [ WINDOW <name> AS ( <definition> ) ]
       [ { UNION | INTERSECT | EXCEPT } [ ALL | DISTINCT ] <selectclause> ]
       [ ORDER BY <expr> [ ASC | DESC ] [, ...] ]
       [ LIMIT { <expr> | ALL } ]
       [ OFFSET <expr> [ ROW | ROWS ] ]
`,
		//line sql.y: 10258
		SeeAlso: `WEBDOCS/select-clause.html
`,
	},
	//line sql.y: 10333
	`TABLE`: {
		ShortDescription: `select an entire table`,
		//line sql.y: 10334
		Category: hDML,
		//line sql.y: 10335
		Text: `TABLE <tablename>
`,
		//line sql.y: 10336
		SeeAlso: `SELECT, VALUES, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 10698
	`VALUES`: {
		ShortDescription: `select a given set of values`,
		//line sql.y: 10699
		Category: hDML,
		//line sql.y: 10700
		Text: `VALUES ( <exprs...> ) [, ...]
`,
		//line sql.y: 10701
		SeeAlso: `SELECT, TABLE, WEBDOCS/table-expressions.html
`,
	},
	//line sql.y: 10836
	`<SOURCE>`: {
		ShortDescription: `define a data source for SELECT`,
		//line sql.y: 10837
		Category: hDML,
		//line sql.y: 10838
		Text: `
Data sources:
  <tablename> [ @ { <idxname> | <indexflags> } ]
  <tablefunc> ( <exprs...> )
  ( { <selectclause> | <source> } )
  <source> [AS] <alias> [( <colnames...> )]
  <source> [ <jointype> ] JOIN <source> ON <expr>
  <source> [ <jointype> ] JOIN <source> USING ( <colnames...> )
  <source> NATURAL [ <jointype> ] JOIN <source>
  <source> CROSS JOIN <source>
  <source> WITH ORDINALITY
  '[' EXPLAIN ... ']'
  '[' SHOW ... ']'

Index flags:
  '{' FORCE_INDEX = <idxname> [, ...] '}'
  '{' NO_INDEX_JOIN [, ...] '}'
  '{' NO_ZIGZAG_JOIN [, ...] '}'
  '{' NO_FULL_SCAN [, ...] '}'
  '{' IGNORE_FOREIGN_KEYS [, ...] '}'
  '{' FORCE_ZIGZAG = <idxname> [, ...]  '}'

Join types:
  { INNER | { LEFT | RIGHT | FULL } [OUTER] } [ { HASH | MERGE | LOOKUP | INVERTED } ]

`,
		//line sql.y: 10863
		SeeAlso: `WEBDOCS/table-expressions.html
`,
	},
}
