load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "actorstorage",
    srcs = [
        "actor_storage.capnp.go",
        "server.go",
    ],
    importpath = "github.com/cockroachdb/cockroach/pkg/server/actorstorage",
    visibility = ["//pkg/server:__subpackages__"],
    deps = [
        "//pkg/keys",
        "//pkg/kv",
        "//pkg/roachpb",
        "//pkg/util/encoding",
        "//pkg/util/log",
        "//pkg/util/tracing",
        "@org_capnproto_go_capnp_v3//:capnp",
        "@org_capnproto_go_capnp_v3//encoding/text",
        "@org_capnproto_go_capnp_v3//flowcontrol",
        "@org_capnproto_go_capnp_v3//schemas",
        "@org_capnproto_go_capnp_v3//server",
        "@org_capnproto_go_capnp_v3//std/capnp/stream",
    ],
)
