// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: util/tracing/tracingservicepb/tracing_service.proto

package tracingservicepb

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_semistrict_ratel_pkg_util_tracing_tracingpb "github.com/semistrict/ratel/pkg/util/tracing/tracingpb"
	tracingpb "github.com/semistrict/ratel/pkg/util/tracing/tracingpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetSpanRecordingsRequest struct {
	TraceID github_com_semistrict_ratel_pkg_util_tracing_tracingpb.TraceID `protobuf:"varint,1,opt,name=trace_id,json=traceId,proto3,customtype=github.com/semistrict/ratel/pkg/util/tracing/tracingpb.TraceID" json:"trace_id"`
}

func (m *GetSpanRecordingsRequest) Reset()         { *m = GetSpanRecordingsRequest{} }
func (m *GetSpanRecordingsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSpanRecordingsRequest) ProtoMessage()    {}
func (*GetSpanRecordingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29b78bec82996ca3, []int{0}
}
func (m *GetSpanRecordingsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSpanRecordingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GetSpanRecordingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpanRecordingsRequest.Merge(m, src)
}
func (m *GetSpanRecordingsRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetSpanRecordingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpanRecordingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpanRecordingsRequest proto.InternalMessageInfo

type GetSpanRecordingsResponse struct {
	Recordings []GetSpanRecordingsResponse_Recording `protobuf:"bytes,1,rep,name=recordings,proto3" json:"recordings"`
}

func (m *GetSpanRecordingsResponse) Reset()         { *m = GetSpanRecordingsResponse{} }
func (m *GetSpanRecordingsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSpanRecordingsResponse) ProtoMessage()    {}
func (*GetSpanRecordingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29b78bec82996ca3, []int{1}
}
func (m *GetSpanRecordingsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSpanRecordingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GetSpanRecordingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpanRecordingsResponse.Merge(m, src)
}
func (m *GetSpanRecordingsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetSpanRecordingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpanRecordingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpanRecordingsResponse proto.InternalMessageInfo

type GetSpanRecordingsResponse_Recording struct {
	RecordedSpans []tracingpb.RecordedSpan `protobuf:"bytes,1,rep,name=recorded_spans,json=recordedSpans,proto3" json:"recorded_spans"`
}

func (m *GetSpanRecordingsResponse_Recording) Reset()         { *m = GetSpanRecordingsResponse_Recording{} }
func (m *GetSpanRecordingsResponse_Recording) String() string { return proto.CompactTextString(m) }
func (*GetSpanRecordingsResponse_Recording) ProtoMessage()    {}
func (*GetSpanRecordingsResponse_Recording) Descriptor() ([]byte, []int) {
	return fileDescriptor_29b78bec82996ca3, []int{1, 0}
}
func (m *GetSpanRecordingsResponse_Recording) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSpanRecordingsResponse_Recording) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *GetSpanRecordingsResponse_Recording) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpanRecordingsResponse_Recording.Merge(m, src)
}
func (m *GetSpanRecordingsResponse_Recording) XXX_Size() int {
	return m.Size()
}
func (m *GetSpanRecordingsResponse_Recording) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpanRecordingsResponse_Recording.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpanRecordingsResponse_Recording proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetSpanRecordingsRequest)(nil), "cockroach.util.tracing.GetSpanRecordingsRequest")
	proto.RegisterType((*GetSpanRecordingsResponse)(nil), "cockroach.util.tracing.GetSpanRecordingsResponse")
	proto.RegisterType((*GetSpanRecordingsResponse_Recording)(nil), "cockroach.util.tracing.GetSpanRecordingsResponse.Recording")
}

func init() {
	proto.RegisterFile("util/tracing/tracingservicepb/tracing_service.proto", fileDescriptor_29b78bec82996ca3)
}

var fileDescriptor_29b78bec82996ca3 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x8d, 0xf5, 0xaa, 0xd7, 0xf7, 0xfc, 0xf4, 0x10, 0x44, 0x08, 0x95, 0x0c, 0x6e, 0xd5, 0xa9,
	0x62, 0xb0, 0xa1, 0x1d, 0x91, 0x18, 0x2a, 0x24, 0xd4, 0x91, 0xc0, 0x04, 0x43, 0x95, 0x38, 0x56,
	0x6a, 0xb5, 0x8d, 0x8d, 0xed, 0x32, 0xb0, 0x23, 0x31, 0xf2, 0x59, 0x1d, 0x3b, 0x56, 0x0c, 0x15,
	0xa4, 0x0b, 0x9f, 0x81, 0x9c, 0xa6, 0xa5, 0x40, 0x3a, 0x74, 0x8a, 0x75, 0xee, 0xb9, 0xf7, 0x9c,
	0x73, 0x73, 0x61, 0x6b, 0x64, 0xf8, 0x80, 0x18, 0x15, 0x50, 0x9e, 0xc4, 0xcb, 0xaf, 0x66, 0xea,
	0x9e, 0x53, 0x26, 0xc3, 0x25, 0xd0, 0xcd, 0x11, 0x2c, 0x95, 0x30, 0xc2, 0x3d, 0xa0, 0x82, 0xf6,
	0x95, 0x08, 0x68, 0x0f, 0xdb, 0x76, 0x9c, 0xb3, 0xbc, 0xfd, 0x58, 0xc4, 0x22, 0xa3, 0x10, 0xfb,
	0x5a, 0xb0, 0xbd, 0xa3, 0x22, 0x09, 0x19, 0x12, 0xc5, 0xa8, 0x50, 0x11, 0x8b, 0xba, 0x5a, 0x06,
	0xc9, 0x82, 0x5b, 0x7f, 0x02, 0xb0, 0x72, 0xc1, 0xcc, 0x95, 0x0c, 0x12, 0x3f, 0x2b, 0x5b, 0x37,
	0x3e, 0xbb, 0x1b, 0x31, 0x6d, 0xdc, 0x01, 0xfc, 0x63, 0xbb, 0x59, 0x97, 0x47, 0x15, 0x50, 0x03,
	0x8d, 0x52, 0xfb, 0x72, 0x3c, 0xab, 0x3a, 0x2f, 0xb3, 0xea, 0x59, 0xcc, 0x4d, 0x6f, 0x14, 0x62,
	0x2a, 0x86, 0x44, 0xb3, 0x21, 0xd7, 0x46, 0x71, 0x6a, 0x88, 0x0a, 0x0c, 0x1b, 0x10, 0xd9, 0x8f,
	0x49, 0xb1, 0x05, 0x7c, 0x6d, 0xc7, 0x75, 0xce, 0xd3, 0x59, 0xb5, 0x9c, 0x3f, 0xfd, 0x72, 0x26,
	0xd1, 0x89, 0xea, 0xef, 0x00, 0x1e, 0x16, 0x58, 0xd1, 0x52, 0x24, 0x9a, 0xb9, 0x01, 0x84, 0x6a,
	0x85, 0x56, 0x40, 0xed, 0x57, 0xe3, 0x5f, 0xf3, 0x14, 0x17, 0xef, 0x05, 0x6f, 0x1c, 0x83, 0x57,
	0x50, 0xbb, 0x64, 0xa3, 0xf8, 0x6b, 0x43, 0xbd, 0x1e, 0xfc, 0xbb, 0x2a, 0xbb, 0xb7, 0x70, 0xe7,
	0xcb, 0xbe, 0x96, 0x9a, 0x78, 0x93, 0xe6, 0x67, 0x48, 0x3f, 0xef, 0xb3, 0x16, 0x72, 0x99, 0xff,
	0x6a, 0x0d, 0xd3, 0xcd, 0x47, 0x00, 0xb3, 0xfc, 0x56, 0xe8, 0x01, 0xee, 0xfd, 0xb0, 0xeb, 0x1e,
	0x6f, 0x91, 0x2c, 0xfb, 0x57, 0xde, 0xc9, 0xd6, 0xbb, 0xa8, 0x3b, 0xed, 0xe6, 0xf8, 0x0d, 0x39,
	0xe3, 0x14, 0x81, 0x49, 0x8a, 0xc0, 0x34, 0x45, 0xe0, 0x35, 0x45, 0xe0, 0x79, 0x8e, 0x9c, 0xc9,
	0x1c, 0x39, 0xd3, 0x39, 0x72, 0x6e, 0x76, 0xbf, 0x5f, 0x68, 0xf8, 0x3b, 0x3b, 0x9c, 0xd6, 0x47,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x67, 0x07, 0x42, 0xc9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TracingClient is the client API for Tracing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TracingClient interface {
	// GetSpanRecordings contacts a nodes' inflight span registry to return the
	// tracing.Recordings for each root span with a matching TraceID.
	GetSpanRecordings(ctx context.Context, in *GetSpanRecordingsRequest, opts ...grpc.CallOption) (*GetSpanRecordingsResponse, error)
}

type tracingClient struct {
	cc *grpc.ClientConn
}

func NewTracingClient(cc *grpc.ClientConn) TracingClient {
	return &tracingClient{cc}
}

func (c *tracingClient) GetSpanRecordings(ctx context.Context, in *GetSpanRecordingsRequest, opts ...grpc.CallOption) (*GetSpanRecordingsResponse, error) {
	out := new(GetSpanRecordingsResponse)
	err := c.cc.Invoke(ctx, "/cockroach.util.tracing.Tracing/GetSpanRecordings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TracingServer is the server API for Tracing service.
type TracingServer interface {
	// GetSpanRecordings contacts a nodes' inflight span registry to return the
	// tracing.Recordings for each root span with a matching TraceID.
	GetSpanRecordings(context.Context, *GetSpanRecordingsRequest) (*GetSpanRecordingsResponse, error)
}

// UnimplementedTracingServer can be embedded to have forward compatible implementations.
type UnimplementedTracingServer struct {
}

func (*UnimplementedTracingServer) GetSpanRecordings(ctx context.Context, req *GetSpanRecordingsRequest) (*GetSpanRecordingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpanRecordings not implemented")
}

func RegisterTracingServer(s *grpc.Server, srv TracingServer) {
	s.RegisterService(&_Tracing_serviceDesc, srv)
}

func _Tracing_GetSpanRecordings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpanRecordingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TracingServer).GetSpanRecordings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cockroach.util.tracing.Tracing/GetSpanRecordings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TracingServer).GetSpanRecordings(ctx, req.(*GetSpanRecordingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tracing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cockroach.util.tracing.Tracing",
	HandlerType: (*TracingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpanRecordings",
			Handler:    _Tracing_GetSpanRecordings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "util/tracing/tracingservicepb/tracing_service.proto",
}

func (m *GetSpanRecordingsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSpanRecordingsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSpanRecordingsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TraceID != 0 {
		i = encodeVarintTracingService(dAtA, i, uint64(m.TraceID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetSpanRecordingsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSpanRecordingsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSpanRecordingsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Recordings) > 0 {
		for iNdEx := len(m.Recordings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Recordings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTracingService(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GetSpanRecordingsResponse_Recording) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSpanRecordingsResponse_Recording) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSpanRecordingsResponse_Recording) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RecordedSpans) > 0 {
		for iNdEx := len(m.RecordedSpans) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RecordedSpans[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTracingService(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTracingService(dAtA []byte, offset int, v uint64) int {
	offset -= sovTracingService(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetSpanRecordingsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TraceID != 0 {
		n += 1 + sovTracingService(uint64(m.TraceID))
	}
	return n
}

func (m *GetSpanRecordingsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Recordings) > 0 {
		for _, e := range m.Recordings {
			l = e.Size()
			n += 1 + l + sovTracingService(uint64(l))
		}
	}
	return n
}

func (m *GetSpanRecordingsResponse_Recording) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RecordedSpans) > 0 {
		for _, e := range m.RecordedSpans {
			l = e.Size()
			n += 1 + l + sovTracingService(uint64(l))
		}
	}
	return n
}

func sovTracingService(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTracingService(x uint64) (n int) {
	return sovTracingService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetSpanRecordingsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTracingService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSpanRecordingsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSpanRecordingsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceID", wireType)
			}
			m.TraceID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracingService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TraceID |= github_com_semistrict_ratel_pkg_util_tracing_tracingpb.TraceID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTracingService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTracingService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSpanRecordingsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTracingService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSpanRecordingsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSpanRecordingsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recordings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracingService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTracingService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTracingService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recordings = append(m.Recordings, GetSpanRecordingsResponse_Recording{})
			if err := m.Recordings[len(m.Recordings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTracingService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTracingService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSpanRecordingsResponse_Recording) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTracingService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Recording: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Recording: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordedSpans", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracingService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTracingService
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTracingService
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecordedSpans = append(m.RecordedSpans, tracingpb.RecordedSpan{})
			if err := m.RecordedSpans[len(m.RecordedSpans)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTracingService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTracingService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTracingService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTracingService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTracingService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTracingService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTracingService
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTracingService
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTracingService
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTracingService        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTracingService          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTracingService = fmt.Errorf("proto: unexpected end of group")
)
