exports_files([
    "README.md",
    "worker.jsonc",
])

ESBUILD_ARGS = "examples/workers/chat/src/worker.js --bundle --format=esm --outfile=$@ --platform=browser --target=es2022"

config_setting(
    name = "darwin_arm64",
    constraint_values = [
        "@platforms//os:macos",
        "@platforms//cpu:arm64",
    ],
)

config_setting(
    name = "darwin_x86_64",
    constraint_values = [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
    ],
)

config_setting(
    name = "linux_arm64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:arm64",
    ],
)

config_setting(
    name = "linux_x86_64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
)

genrule(
    name = "chat_worker",
    srcs = glob(["src/**"]),
    outs = ["chat_worker.js"],
    cmd = select({
        ":darwin_arm64": "$(location @npm//:aspect_rules_js~~npm~npm__esbuild-darwin-arm64__0.14.43_source_directory)/bin/esbuild " + ESBUILD_ARGS,
        ":darwin_x86_64": "$(location @npm//:aspect_rules_js~~npm~npm__esbuild-darwin-64__0.14.43_source_directory)/bin/esbuild " + ESBUILD_ARGS,
        ":linux_arm64": "$(location @npm//:aspect_rules_js~~npm~npm__esbuild-linux-arm64__0.14.43_source_directory)/bin/esbuild " + ESBUILD_ARGS,
        ":linux_x86_64": "$(location @npm//:aspect_rules_js~~npm~npm__esbuild-linux-64__0.14.43_source_directory)/bin/esbuild " + ESBUILD_ARGS,
    }),
    tools = select({
        ":darwin_arm64": ["@npm//:aspect_rules_js~~npm~npm__esbuild-darwin-arm64__0.14.43_source_directory"],
        ":darwin_x86_64": ["@npm//:aspect_rules_js~~npm~npm__esbuild-darwin-64__0.14.43_source_directory"],
        ":linux_arm64": ["@npm//:aspect_rules_js~~npm~npm__esbuild-linux-arm64__0.14.43_source_directory"],
        ":linux_x86_64": ["@npm//:aspect_rules_js~~npm~npm__esbuild-linux-64__0.14.43_source_directory"],
    }),
    visibility = ["//visibility:public"],
)

sh_test(
    name = "playwright_test",
    srcs = ["tests/run_playwright.sh"],
    data = [
        "tests/chat.spec.js",
    ],
    tags = [
        "external",
        "manual",
    ],
)
