// Copyright 2020 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by generate_visitor.go. DO NOT EDIT.

package scop

import "context"

// BackfillOp is an operation which can be visited by BackfillVisitor.
type BackfillOp interface {
	Op
	Visit(context.Context, BackfillVisitor) error
}

// BackfillVisitor is a visitor for BackfillOp operations.
type BackfillVisitor interface {
	BackfillIndex(context.Context, BackfillIndex) error
}

// Visit is part of the BackfillOp interface.
func (op BackfillIndex) Visit(ctx context.Context, v BackfillVisitor) error {
	return v.BackfillIndex(ctx, op)
}
