// Copyright 2021 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

syntax = "proto3";
package cockroach.util.tracing.tracingpb;
option go_package = "tracingpb";

import "gogoproto/gogo.proto";


enum RecordingMode {
  OFF = 0;
  VERBOSE = 1;
  STRUCTURED = 2;
}

// TraceInfo represents the tracing context of an operation. It is the proto
// representation of tracing.SpanMeta. TraceInfos are passed around in RPC
// payloads so that the server can create spans that are linked to the remote
// parent.
message TraceInfo {
  uint64 trace_id = 1 [(gogoproto.nullable) = false, (gogoproto.customname) = "TraceID", (gogoproto.customtype) = "TraceID"];
  // ID of the parent span.
  uint64 parent_span_id = 2 [(gogoproto.nullable) = false, (gogoproto.customname) = "ParentSpanID", (gogoproto.customtype) = "SpanID"];

  // The type of recording, if any, that the parent span is doing. See
  // tracing.RecordingType.
  RecordingMode recording_mode = 3;

  // OtelInfo contains the OpenTelemetry tracing context, if any.
  message OtelInfo {
    // trace_id will have exactly 16 bytes.
    bytes trace_id = 1 [(gogoproto.customname) = "TraceID"];
    // span_id will have exactly 8 bytes.
    bytes span_id = 2 [(gogoproto.customname) = "SpanID"];
  }

  OtelInfo otel = 4;
}

