// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sql/sessiondatapb/session_data.proto

package sessiondatapb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	github_com_semistrict_ratel_pkg_security "github.com/semistrict/ratel/pkg/security"
	lex "github.com/semistrict/ratel/pkg/sql/lex"
	duration "github.com/semistrict/ratel/pkg/util/duration"
	pgdate "github.com/semistrict/ratel/pkg/util/timeutil/pgdate"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VectorizeExecMode controls if an when the Executor executes queries using
// the columnar execution engine.
type VectorizeExecMode int32

const (
	// VectorizeUnset means the VectorizeExecMode wasn't explicitly set. Having
	// the first enum value as zero is required by proto3. This is mapped to
	// VectorizeOn.
	VectorizeUnset VectorizeExecMode = 0
	// VectorizeOn means that any supported queries will be run using the
	// columnar execution.
	VectorizeOn VectorizeExecMode = 2
	// VectorizeExperimentalAlways means that we attempt to vectorize all
	// queries; unsupported queries will fail. Mostly used for testing.
	VectorizeExperimentalAlways VectorizeExecMode = 3
	// VectorizeOff means that columnar execution is disabled.
	VectorizeOff VectorizeExecMode = 4
)

var VectorizeExecMode_name = map[int32]string{
	0: "VectorizeUnset",
	2: "VectorizeOn",
	3: "VectorizeExperimentalAlways",
	4: "VectorizeOff",
}

var VectorizeExecMode_value = map[string]int32{
	"VectorizeUnset":              0,
	"VectorizeOn":                 2,
	"VectorizeExperimentalAlways": 3,
	"VectorizeOff":                4,
}

func (VectorizeExecMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9fa1c5a4e61eec38, []int{0}
}

// SessionData contains session parameters that are easily serializable and are
// required to be propagated to the remote nodes for the correct execution of
// DistSQL flows.
type SessionData struct {
	// Database indicates the "current" database for the purpose of resolving
	// names.
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	// ApplicationName is the name of the application running the current
	// session. This can be used for logging and per-application statistics.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// User is the name of the user logged into the session.
	UserProto github_com_semistrict_ratel_pkg_security.SQLUsernameProto `protobuf:"bytes,3,opt,name=user_proto,json=userProto,proto3,casttype=github.com/semistrict/ratel/pkg/security.SQLUsernameProto" json:"user_proto,omitempty"`
	// DataConversion gives access to the data conversion configuration.
	DataConversionConfig DataConversionConfig `protobuf:"bytes,4,opt,name=data_conversion_config,json=dataConversionConfig,proto3" json:"data_conversion_config"`
	// VectorizeMode indicates which kinds of queries to use vectorized execution
	// engine for.
	VectorizeMode VectorizeExecMode `protobuf:"varint,5,opt,name=vectorize_mode,json=vectorizeMode,proto3,enum=cockroach.sql.sessiondatapb.VectorizeExecMode" json:"vectorize_mode,omitempty"`
	// TestingVectorizeInjectPanics indicates whether random panics are injected
	// into the vectorized flow execution. The goal of such behavior is making
	// sure that errors that are propagated as panics in the vectorized engine
	// are caught in all scenarios.
	TestingVectorizeInjectPanics bool `protobuf:"varint,6,opt,name=testing_vectorize_inject_panics,json=testingVectorizeInjectPanics,proto3" json:"testing_vectorize_inject_panics,omitempty"`
	// DefaultIntSize specifies the size in bits or bytes (preferred) of how a
	// "naked" INT type should be parsed.
	DefaultIntSize int32 `protobuf:"varint,7,opt,name=default_int_size,json=defaultIntSize,proto3" json:"default_int_size,omitempty"`
	// The name of the location according to whose current timezone we're going to
	// parse timestamps. Used to initialize sessiondata.SessionData.Location on
	// the remote nodes.
	//
	// Note that the current serialization of the time.Location objects as
	// strings has many drawbacks which could lead to unstable computation on the
	// remote nodes. See #36864 and
	// https://github.com/semistrict/ratel/pull/55377#issuecomment-707794695
	// for more details.
	Location string `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	// SearchPath is a list of namespaces to search builtins in. Used to
	// initialize sessiondata.SessionData.SearchPath on the remote nodes.
	SearchPath          []string `protobuf:"bytes,9,rep,name=search_path,json=searchPath,proto3" json:"search_path,omitempty"`
	TemporarySchemaName string   `protobuf:"bytes,10,opt,name=temporary_schema_name,json=temporarySchemaName,proto3" json:"temporary_schema_name,omitempty"`
	// SeqState gives access to the SQL sequences that have been manipulated by
	// the session.
	SeqState SequenceState `protobuf:"bytes,11,opt,name=seq_state,json=seqState,proto3" json:"seq_state"`
	// WorkMemLimit determines how much RAM (in bytes) a single operation of a
	// single query can use before it has to spill to disk.
	WorkMemLimit int64 `protobuf:"varint,12,opt,name=WorkMemLimit,proto3" json:"WorkMemLimit,omitempty"`
	// IntervalStyleEnabled allows the setting of IntervalStyle to different
	// values.
	IntervalStyleEnabled bool `protobuf:"varint,13,opt,name=interval_style_enabled,json=intervalStyleEnabled,proto3" json:"interval_style_enabled,omitempty"`
	// DateStyleEnabled allows the setting of DateStyle to different
	// values.
	DateStyleEnabled bool `protobuf:"varint,14,opt,name=date_style_enabled,json=dateStyleEnabled,proto3" json:"date_style_enabled,omitempty"`
	// LockTimeout is the maximum amount of time that a query will wait while
	// attempting to acquire a lock on a key or while blocking on an existing
	// lock in order to perform a non-locking read on a key.
	LockTimeout time.Duration `protobuf:"bytes,15,opt,name=lock_timeout,json=lockTimeout,proto3,stdduration" json:"lock_timeout"`
	// Internal is true if this query came from InternalExecutor or an internal
	// planner.
	Internal bool `protobuf:"varint,16,opt,name=internal,proto3" json:"internal,omitempty"`
	// OnUpdateRehomeRowEnabled controls whether the ON UPDATE rehome_row()
	// will actually trigger on row updates.
	OnUpdateRehomeRowEnabled bool `protobuf:"varint,17,opt,name=on_update_rehome_row_enabled,json=onUpdateRehomeRowEnabled,proto3" json:"on_update_rehome_row_enabled,omitempty"`
	// JoinReaderOrderingStrategyBatchSize is the size limit on the input rows to
	// the joinReader processor (when ordering is required to be maintained) to
	// construct a single lookup KV batch.
	JoinReaderOrderingStrategyBatchSize int64 `protobuf:"varint,18,opt,name=join_reader_ordering_strategy_batch_size,json=joinReaderOrderingStrategyBatchSize,proto3" json:"join_reader_ordering_strategy_batch_size,omitempty"`
	// ParallelizeMultiKeyLookupJoinsEnabled is true when the join reader should
	// parallelize lookup batches under all circumstances. Enabling this will
	// increase the speed of lookup joins when each input row might get multiple
	// looked up rows at the cost of increased memory usage.
	ParallelizeMultiKeyLookupJoinsEnabled bool `protobuf:"varint,19,opt,name=parallelize_multi_key_lookup_joins_enabled,json=parallelizeMultiKeyLookupJoinsEnabled,proto3" json:"parallelize_multi_key_lookup_joins_enabled,omitempty"`
	// ActorScope selects the actor whose table data is accessed by default for
	// statements in this session. An empty value means unscoped table access.
	ActorScope string `protobuf:"bytes,20,opt,name=actor_scope,json=actorScope,proto3" json:"actor_scope,omitempty"`
	// Troubleshooting mode determines whether we refuse to do additional work with
	// the query (i.e. collect & emit telemetry data). Troubleshooting mode is
	// disabled by default.
	TroubleshootingMode bool `protobuf:"varint,21,opt,name=troubleshooting_mode,json=troubleshootingMode,proto3" json:"troubleshooting_mode,omitempty"`
	// JoinReaderNoOrderingStrategyBatchSize is the size limit on the input rows
	// to the joinReader processor (when ordering is **not** required to be
	// maintained) to construct a single lookup KV batch.
	JoinReaderNoOrderingStrategyBatchSize int64 `protobuf:"varint,22,opt,name=join_reader_no_ordering_strategy_batch_size,json=joinReaderNoOrderingStrategyBatchSize,proto3" json:"join_reader_no_ordering_strategy_batch_size,omitempty"`
	// JoinReaderIndexJoinStrategyBatchSize is the size limit on the input rows
	// to the joinReader processor (when performing index joins) to construct a
	// single lookup KV batch.
	JoinReaderIndexJoinStrategyBatchSize int64 `protobuf:"varint,23,opt,name=join_reader_index_join_strategy_batch_size,json=joinReaderIndexJoinStrategyBatchSize,proto3" json:"join_reader_index_join_strategy_batch_size,omitempty"`
}

func (m *SessionData) Reset()         { *m = SessionData{} }
func (m *SessionData) String() string { return proto.CompactTextString(m) }
func (*SessionData) ProtoMessage()    {}
func (*SessionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fa1c5a4e61eec38, []int{0}
}
func (m *SessionData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SessionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SessionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionData.Merge(m, src)
}
func (m *SessionData) XXX_Size() int {
	return m.Size()
}
func (m *SessionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionData.DiscardUnknown(m)
}

var xxx_messageInfo_SessionData proto.InternalMessageInfo

// DataConversionConfig contains the parameters that influence the output
// of certain data types as strings or bytes.
type DataConversionConfig struct {
	// BytesEncodeFormat indicates how to encode byte arrays when converting to
	// string.
	BytesEncodeFormat lex.BytesEncodeFormat `protobuf:"varint,1,opt,name=bytes_encode_format,json=bytesEncodeFormat,proto3,enum=cockroach.sql.sessiondatapb.BytesEncodeFormat" json:"bytes_encode_format,omitempty"`
	// ExtraFloatDigits indicates the number of digits beyond the standard number
	// to use for float conversions.This must be set to a value between -15 and
	// 3, inclusive.
	ExtraFloatDigits int32 `protobuf:"varint,2,opt,name=extra_float_digits,json=extraFloatDigits,proto3" json:"extra_float_digits,omitempty"`
	// IntervalStyle indicates the style to parse and display intervals as.
	IntervalStyle duration.IntervalStyle `protobuf:"varint,3,opt,name=interval_style,json=intervalStyle,proto3,enum=cockroach.util.duration.IntervalStyle" json:"interval_style,omitempty"`
	// DateStyle indicates the style to parse and display dates as.
	DateStyle pgdate.DateStyle `protobuf:"bytes,4,opt,name=date_style,json=dateStyle,proto3" json:"date_style"`
}

func (m *DataConversionConfig) Reset()         { *m = DataConversionConfig{} }
func (m *DataConversionConfig) String() string { return proto.CompactTextString(m) }
func (*DataConversionConfig) ProtoMessage()    {}
func (*DataConversionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fa1c5a4e61eec38, []int{1}
}
func (m *DataConversionConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataConversionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DataConversionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataConversionConfig.Merge(m, src)
}
func (m *DataConversionConfig) XXX_Size() int {
	return m.Size()
}
func (m *DataConversionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DataConversionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DataConversionConfig proto.InternalMessageInfo

// SequenceState is used to marshall the sessiondata.SequenceState struct.
type SequenceState struct {
	Seqs []*SequenceState_Seq `protobuf:"bytes,1,rep,name=seqs,proto3" json:"seqs,omitempty"`
	// last_seq_incremented is the id of the last sequence incremented by the
	// session. This field is filled in iff seqs is not empty.
	LastSeqIncremented uint32 `protobuf:"varint,2,opt,name=last_seq_incremented,json=lastSeqIncremented,proto3" json:"last_seq_incremented,omitempty"`
}

func (m *SequenceState) Reset()         { *m = SequenceState{} }
func (m *SequenceState) String() string { return proto.CompactTextString(m) }
func (*SequenceState) ProtoMessage()    {}
func (*SequenceState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fa1c5a4e61eec38, []int{2}
}
func (m *SequenceState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SequenceState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SequenceState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceState.Merge(m, src)
}
func (m *SequenceState) XXX_Size() int {
	return m.Size()
}
func (m *SequenceState) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceState.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceState proto.InternalMessageInfo

// Seq represents the last value of one sequence modified by the session.
type SequenceState_Seq struct {
	SeqID     uint32 `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	LatestVal int64  `protobuf:"varint,2,opt,name=latest_val,json=latestVal,proto3" json:"latest_val,omitempty"`
}

func (m *SequenceState_Seq) Reset()         { *m = SequenceState_Seq{} }
func (m *SequenceState_Seq) String() string { return proto.CompactTextString(m) }
func (*SequenceState_Seq) ProtoMessage()    {}
func (*SequenceState_Seq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fa1c5a4e61eec38, []int{2, 0}
}
func (m *SequenceState_Seq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SequenceState_Seq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SequenceState_Seq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceState_Seq.Merge(m, src)
}
func (m *SequenceState_Seq) XXX_Size() int {
	return m.Size()
}
func (m *SequenceState_Seq) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceState_Seq.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceState_Seq proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cockroach.sql.sessiondatapb.VectorizeExecMode", VectorizeExecMode_name, VectorizeExecMode_value)
	proto.RegisterType((*SessionData)(nil), "cockroach.sql.sessiondatapb.SessionData")
	proto.RegisterType((*DataConversionConfig)(nil), "cockroach.sql.sessiondatapb.DataConversionConfig")
	proto.RegisterType((*SequenceState)(nil), "cockroach.sql.sessiondatapb.SequenceState")
	proto.RegisterType((*SequenceState_Seq)(nil), "cockroach.sql.sessiondatapb.SequenceState.Seq")
}

func init() {
	proto.RegisterFile("sql/sessiondatapb/session_data.proto", fileDescriptor_9fa1c5a4e61eec38)
}

var fileDescriptor_9fa1c5a4e61eec38 = []byte{
	// 1207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xcf, 0x72, 0x1b, 0xc5,
	0x13, 0xd6, 0xc6, 0x76, 0x7e, 0xd6, 0xc8, 0x52, 0x94, 0xb1, 0x92, 0xdf, 0xe2, 0x04, 0x49, 0x98,
	0x84, 0x52, 0x0c, 0x25, 0x11, 0xc3, 0x85, 0x03, 0x54, 0xa1, 0xd8, 0xae, 0x32, 0xc4, 0x49, 0x58,
	0xe1, 0x00, 0x29, 0x8a, 0xa9, 0xd1, 0x6e, 0x4b, 0x9a, 0x78, 0x76, 0x67, 0x35, 0x33, 0x72, 0xac,
	0xf0, 0x02, 0x1c, 0xe1, 0xc6, 0x1d, 0x0e, 0xbc, 0x07, 0x97, 0x5c, 0xa8, 0xca, 0x31, 0xa7, 0x00,
	0xce, 0x5b, 0x70, 0xa2, 0xa6, 0xf5, 0xc7, 0x92, 0x13, 0x9c, 0xd3, 0x4e, 0x77, 0x7f, 0x5f, 0x4f,
	0x6f, 0xcf, 0x7c, 0x3d, 0xe4, 0x9a, 0xe9, 0xcb, 0x86, 0x01, 0x63, 0x84, 0x4a, 0x22, 0x6e, 0x79,
	0xda, 0x9e, 0x58, 0xcc, 0x99, 0xf5, 0x54, 0x2b, 0xab, 0xe8, 0x95, 0x50, 0x85, 0x07, 0x5a, 0xf1,
	0xb0, 0x57, 0x37, 0x7d, 0x59, 0x9f, 0xc3, 0xaf, 0x95, 0x5c, 0x0a, 0x09, 0x47, 0x0d, 0x48, 0x42,
	0x15, 0xc1, 0x88, 0xb2, 0x76, 0x75, 0x60, 0x85, 0x6c, 0x44, 0x03, 0xcd, 0xad, 0x50, 0xc9, 0x74,
	0x31, 0x8e, 0xbe, 0x85, 0x51, 0x2b, 0x62, 0xc0, 0x45, 0xda, 0x8d, 0xb8, 0x85, 0xf1, 0x67, 0x0c,
	0x29, 0x75, 0x55, 0x57, 0xe1, 0xb2, 0xe1, 0x56, 0x63, 0x6f, 0xb9, 0xab, 0x54, 0x57, 0x42, 0x03,
	0xad, 0xf6, 0xa0, 0x73, 0x2a, 0xf1, 0xfa, 0x4f, 0x39, 0x92, 0x6b, 0x8d, 0xca, 0xdb, 0xe2, 0x96,
	0xd3, 0x35, 0xb2, 0xec, 0xca, 0x6c, 0x73, 0x03, 0xbe, 0x57, 0xf5, 0x6a, 0xd9, 0x60, 0x6a, 0xd3,
	0x1b, 0xa4, 0xc8, 0xd3, 0x54, 0x8a, 0x10, 0x13, 0xb0, 0x84, 0xc7, 0xe0, 0x9f, 0x43, 0xcc, 0x85,
	0x19, 0xff, 0x1d, 0x1e, 0x03, 0xfd, 0x96, 0x90, 0x81, 0x01, 0xcd, 0x70, 0x13, 0x7f, 0xc1, 0x81,
	0x9a, 0x1f, 0xff, 0xf3, 0xbc, 0xf2, 0x51, 0x57, 0xd8, 0xde, 0xa0, 0x5d, 0x0f, 0x55, 0xdc, 0x30,
	0x10, 0x0b, 0x63, 0xb5, 0x08, 0x6d, 0x43, 0x73, 0x0b, 0xb2, 0x91, 0x1e, 0x74, 0x1b, 0x06, 0xc2,
	0x81, 0x16, 0x76, 0x58, 0x6f, 0x7d, 0x71, 0x7b, 0xdf, 0x80, 0x76, 0x9b, 0xdc, 0x73, 0x49, 0x82,
	0xac, 0x4b, 0x88, 0x4b, 0x1a, 0x93, 0xcb, 0xae, 0x28, 0x16, 0xaa, 0xe4, 0x10, 0x34, 0x36, 0x3f,
	0x54, 0x49, 0x47, 0x74, 0xfd, 0xc5, 0xaa, 0x57, 0xcb, 0x6d, 0xde, 0xac, 0x9f, 0xd1, 0xff, 0xba,
	0xfb, 0xcf, 0x5b, 0x53, 0xe6, 0x2d, 0x24, 0x36, 0x17, 0x9f, 0x3c, 0xaf, 0x64, 0x82, 0x52, 0xf4,
	0x8a, 0x18, 0xdd, 0x27, 0x85, 0x43, 0x08, 0xad, 0xd2, 0xe2, 0x31, 0xb0, 0x58, 0x45, 0xe0, 0x2f,
	0x55, 0xbd, 0x5a, 0x61, 0xb3, 0x7e, 0xe6, 0x36, 0xf7, 0x27, 0x94, 0xed, 0x23, 0x08, 0xf7, 0x54,
	0x04, 0x41, 0x7e, 0x9a, 0xc5, 0x99, 0x74, 0x9b, 0x54, 0x2c, 0x18, 0x2b, 0x92, 0x2e, 0x3b, 0x49,
	0x2f, 0x92, 0x87, 0x10, 0x5a, 0x96, 0xf2, 0x44, 0x84, 0xc6, 0x3f, 0x5f, 0xf5, 0x6a, 0xcb, 0xc1,
	0xd5, 0x31, 0x6c, 0x9a, 0x71, 0x17, 0x41, 0xf7, 0x10, 0x43, 0x6b, 0xa4, 0x18, 0x41, 0x87, 0x0f,
	0xa4, 0x65, 0x22, 0xb1, 0xcc, 0x88, 0xc7, 0xe0, 0xff, 0xaf, 0xea, 0xd5, 0x96, 0x82, 0xc2, 0xd8,
	0xbf, 0x9b, 0xd8, 0x96, 0x78, 0x0c, 0xee, 0x6c, 0xa5, 0x1a, 0x1d, 0x92, 0xbf, 0x3c, 0x3a, 0xdb,
	0x89, 0x4d, 0x2b, 0x24, 0x67, 0x80, 0xeb, 0xb0, 0xc7, 0x52, 0x6e, 0x7b, 0x7e, 0xb6, 0xba, 0x50,
	0xcb, 0x06, 0x64, 0xe4, 0xba, 0xc7, 0x6d, 0x8f, 0x6e, 0x92, 0x4b, 0x16, 0xe2, 0x54, 0x69, 0xae,
	0x87, 0xcc, 0x84, 0x3d, 0x88, 0xf9, 0xe8, 0x06, 0x10, 0xcc, 0xb4, 0x3a, 0x0d, 0xb6, 0x30, 0x86,
	0xb7, 0x60, 0x8f, 0x64, 0x0d, 0xf4, 0x99, 0xb1, 0xdc, 0x82, 0x9f, 0xc3, 0xa3, 0xd9, 0x38, 0xb3,
	0x67, 0x2d, 0xe8, 0x0f, 0x20, 0x09, 0xa1, 0xe5, 0x18, 0xe3, 0x33, 0x59, 0x36, 0xd0, 0x47, 0x9b,
	0xae, 0x93, 0x95, 0xaf, 0x94, 0x3e, 0xd8, 0x83, 0xf8, 0xb6, 0x88, 0x85, 0xf5, 0x57, 0xaa, 0x5e,
	0x6d, 0x21, 0x98, 0xf3, 0xd1, 0x0f, 0xc9, 0x65, 0x91, 0x58, 0xd0, 0x87, 0x5c, 0x32, 0x63, 0x87,
	0x12, 0x18, 0x24, 0xbc, 0x2d, 0x21, 0xf2, 0xf3, 0xd8, 0xcb, 0xd2, 0x24, 0xda, 0x72, 0xc1, 0xed,
	0x51, 0x8c, 0xbe, 0x47, 0xa8, 0x53, 0xd2, 0x29, 0x46, 0x01, 0x19, 0x45, 0x17, 0x99, 0x43, 0xef,
	0x90, 0x15, 0xa9, 0xc2, 0x03, 0xe6, 0xe4, 0xa8, 0x06, 0xd6, 0xbf, 0x80, 0x7f, 0xf6, 0x46, 0x7d,
	0x24, 0xb5, 0xfa, 0x44, 0x6a, 0xf5, 0xad, 0xb1, 0xd4, 0x9a, 0xcb, 0xee, 0x47, 0x7e, 0xfe, 0xb3,
	0xe2, 0x05, 0x39, 0x47, 0xfc, 0x72, 0xc4, 0x73, 0xe7, 0x81, 0xd5, 0x24, 0x5c, 0xfa, 0x45, 0xdc,
	0x6b, 0x6a, 0xd3, 0x4f, 0xc8, 0x55, 0x95, 0xb0, 0x41, 0x8a, 0x65, 0x69, 0xe8, 0xa9, 0x18, 0x98,
	0x56, 0x8f, 0xa6, 0xb5, 0x5d, 0x44, 0xbc, 0xaf, 0x92, 0x7d, 0x84, 0x04, 0x88, 0x08, 0xd4, 0xa3,
	0x49, 0x8d, 0xfb, 0xa4, 0xf6, 0x50, 0x89, 0x84, 0x69, 0xe0, 0x11, 0x68, 0xa6, 0x74, 0x04, 0xda,
	0xdd, 0x34, 0x63, 0x9d, 0xd6, 0xba, 0x43, 0xd6, 0xe6, 0x36, 0xec, 0x8d, 0x6e, 0x0b, 0xc5, 0x3e,
	0xbe, 0xed, 0xf0, 0x01, 0xc2, 0xef, 0x8e, 0xd1, 0xad, 0x31, 0xb8, 0xe9, 0xb0, 0x78, 0x85, 0xbe,
	0x21, 0x1b, 0x29, 0xd7, 0x5c, 0x4a, 0x90, 0x28, 0x86, 0x81, 0xb4, 0x82, 0x1d, 0xc0, 0x90, 0x49,
	0xa5, 0x0e, 0x06, 0x29, 0x73, 0x39, 0xcc, 0xb4, 0xc8, 0x55, 0x2c, 0xf2, 0xfa, 0x0c, 0x63, 0xcf,
	0x11, 0x3e, 0x87, 0xe1, 0x6d, 0x84, 0x7f, 0xe6, 0xd0, 0x93, 0x8a, 0x2b, 0x24, 0xc7, 0xdd, 0xfd,
	0x66, 0x26, 0x54, 0x29, 0xf8, 0x25, 0xbc, 0x56, 0x04, 0x5d, 0x2d, 0xe7, 0xa1, 0x37, 0x49, 0xc9,
	0x6a, 0x35, 0x68, 0x4b, 0x30, 0x3d, 0xa5, 0x50, 0x37, 0x28, 0xc6, 0x4b, 0xb8, 0xcb, 0xea, 0xa9,
	0x18, 0x4a, 0xec, 0x01, 0x79, 0x77, 0xb6, 0x0b, 0x89, 0x3a, 0xbb, 0x11, 0x97, 0xb1, 0x11, 0xd7,
	0x4f, 0x1a, 0x71, 0x47, 0xfd, 0x77, 0x2b, 0xbe, 0x26, 0x1b, 0xb3, 0xb9, 0x45, 0x12, 0xc1, 0x11,
	0xfe, 0xff, 0x2b, 0x53, 0xff, 0x1f, 0x53, 0x5f, 0x3b, 0x49, 0xbd, 0xeb, 0xf0, 0xae, 0x01, 0x2f,
	0x65, 0x5e, 0xff, 0xfd, 0x1c, 0x29, 0xbd, 0x6a, 0x48, 0xd1, 0xef, 0xc8, 0x6a, 0x7b, 0x68, 0xc1,
	0x35, 0xd8, 0xbd, 0x1c, 0xac, 0xa3, 0x74, 0xcc, 0x2d, 0xce, 0xe9, 0xd7, 0x4d, 0xa3, 0xa6, 0xe3,
	0x6d, 0x23, 0x6d, 0x07, 0x59, 0xc1, 0xc5, 0xf6, 0x69, 0x97, 0x93, 0x01, 0x1c, 0x59, 0xcd, 0x59,
	0x47, 0x2a, 0x6e, 0x59, 0x24, 0xba, 0xc2, 0x1a, 0x1c, 0xf1, 0x4b, 0x41, 0x11, 0x23, 0x3b, 0x2e,
	0xb0, 0x85, 0x7e, 0xba, 0x47, 0x0a, 0xf3, 0x52, 0xc3, 0x39, 0x5f, 0xd8, 0x7c, 0x67, 0xa6, 0x10,
	0xf7, 0x5a, 0xd5, 0xa7, 0x4f, 0xce, 0xee, 0xac, 0xf6, 0x82, 0xfc, 0x9c, 0x14, 0xe9, 0x1d, 0x42,
	0x4e, 0x34, 0x38, 0x1e, 0xe4, 0x37, 0x4e, 0xa7, 0x9a, 0xbc, 0x80, 0xf5, 0xf1, 0xd3, 0xb7, 0x35,
	0xd1, 0xe6, 0x78, 0x58, 0x64, 0xa7, 0x62, 0x5d, 0xff, 0xc3, 0x23, 0xf9, 0xb9, 0x79, 0x42, 0x9b,
	0x64, 0xd1, 0x40, 0xdf, 0xf8, 0x5e, 0x75, 0xa1, 0x96, 0x7b, 0x4d, 0xbf, 0xe6, 0x98, 0xce, 0x0a,
	0x90, 0x4b, 0xdf, 0x27, 0x25, 0xc9, 0x8d, 0x65, 0x6e, 0xae, 0x89, 0x24, 0xd4, 0x10, 0x43, 0x62,
	0x21, 0xc2, 0x26, 0xe5, 0x03, 0xea, 0x62, 0x2d, 0xe8, 0xef, 0x9e, 0x44, 0xd6, 0x76, 0xc8, 0x42,
	0x0b, 0xfa, 0xb4, 0x4a, 0xce, 0x23, 0x27, 0xc2, 0xe3, 0xca, 0x37, 0xb3, 0xc7, 0xcf, 0x2b, 0x4b,
	0x0e, 0xba, 0x15, 0x2c, 0x19, 0xe8, 0xef, 0x46, 0xf4, 0x4d, 0x42, 0x24, 0x77, 0xa3, 0x9e, 0x1d,
	0x72, 0x89, 0x09, 0x17, 0x82, 0xec, 0xc8, 0x73, 0x9f, 0xcb, 0x8d, 0xef, 0xc9, 0xc5, 0x97, 0x9e,
	0x14, 0x4a, 0x49, 0x61, 0xea, 0xdc, 0x4f, 0x0c, 0xd8, 0x62, 0x86, 0x5e, 0x20, 0xb9, 0xa9, 0xef,
	0x6e, 0x52, 0x3c, 0x47, 0x2b, 0xe4, 0xca, 0x0c, 0x33, 0x05, 0x2d, 0x5c, 0x69, 0x5c, 0x7e, 0x2a,
	0x1f, 0xf1, 0xa1, 0x29, 0x2e, 0xd0, 0x22, 0x59, 0x39, 0x61, 0x74, 0x3a, 0xc5, 0xc5, 0xb5, 0xe5,
	0x1f, 0x7e, 0x29, 0x67, 0x7e, 0xfb, 0xb5, 0x9c, 0x59, 0x5f, 0x5c, 0xf6, 0x8a, 0x5e, 0xb3, 0xf1,
	0xe4, 0xef, 0x72, 0xe6, 0xc9, 0x71, 0xd9, 0x7b, 0x7a, 0x5c, 0xf6, 0x9e, 0x1d, 0x97, 0xbd, 0xbf,
	0x8e, 0xcb, 0xde, 0x8f, 0x2f, 0xca, 0x99, 0xa7, 0x2f, 0xca, 0x99, 0x67, 0x2f, 0xca, 0x99, 0x07,
	0xf9, 0xb9, 0xfe, 0xb5, 0xcf, 0xe3, 0x14, 0xfc, 0xe0, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76,
	0xbd, 0xa3, 0x5e, 0x30, 0x09, 0x00, 0x00,
}

func (m *SessionData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SessionData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SessionData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.JoinReaderIndexJoinStrategyBatchSize != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.JoinReaderIndexJoinStrategyBatchSize))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb8
	}
	if m.JoinReaderNoOrderingStrategyBatchSize != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.JoinReaderNoOrderingStrategyBatchSize))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.TroubleshootingMode {
		i--
		if m.TroubleshootingMode {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if len(m.ActorScope) > 0 {
		i -= len(m.ActorScope)
		copy(dAtA[i:], m.ActorScope)
		i = encodeVarintSessionData(dAtA, i, uint64(len(m.ActorScope)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.ParallelizeMultiKeyLookupJoinsEnabled {
		i--
		if m.ParallelizeMultiKeyLookupJoinsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.JoinReaderOrderingStrategyBatchSize != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.JoinReaderOrderingStrategyBatchSize))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.OnUpdateRehomeRowEnabled {
		i--
		if m.OnUpdateRehomeRowEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.Internal {
		i--
		if m.Internal {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.LockTimeout, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.LockTimeout):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintSessionData(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x7a
	if m.DateStyleEnabled {
		i--
		if m.DateStyleEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.IntervalStyleEnabled {
		i--
		if m.IntervalStyleEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.WorkMemLimit != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.WorkMemLimit))
		i--
		dAtA[i] = 0x60
	}
	{
		size, err := m.SeqState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if len(m.TemporarySchemaName) > 0 {
		i -= len(m.TemporarySchemaName)
		copy(dAtA[i:], m.TemporarySchemaName)
		i = encodeVarintSessionData(dAtA, i, uint64(len(m.TemporarySchemaName)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.SearchPath) > 0 {
		for iNdEx := len(m.SearchPath) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SearchPath[iNdEx])
			copy(dAtA[i:], m.SearchPath[iNdEx])
			i = encodeVarintSessionData(dAtA, i, uint64(len(m.SearchPath[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintSessionData(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x42
	}
	if m.DefaultIntSize != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.DefaultIntSize))
		i--
		dAtA[i] = 0x38
	}
	if m.TestingVectorizeInjectPanics {
		i--
		if m.TestingVectorizeInjectPanics {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.VectorizeMode != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.VectorizeMode))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.DataConversionConfig.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.UserProto) > 0 {
		i -= len(m.UserProto)
		copy(dAtA[i:], m.UserProto)
		i = encodeVarintSessionData(dAtA, i, uint64(len(m.UserProto)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ApplicationName) > 0 {
		i -= len(m.ApplicationName)
		copy(dAtA[i:], m.ApplicationName)
		i = encodeVarintSessionData(dAtA, i, uint64(len(m.ApplicationName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Database) > 0 {
		i -= len(m.Database)
		copy(dAtA[i:], m.Database)
		i = encodeVarintSessionData(dAtA, i, uint64(len(m.Database)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DataConversionConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataConversionConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataConversionConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DateStyle.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSessionData(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.IntervalStyle != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.IntervalStyle))
		i--
		dAtA[i] = 0x18
	}
	if m.ExtraFloatDigits != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.ExtraFloatDigits))
		i--
		dAtA[i] = 0x10
	}
	if m.BytesEncodeFormat != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.BytesEncodeFormat))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SequenceState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SequenceState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SequenceState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastSeqIncremented != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.LastSeqIncremented))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Seqs) > 0 {
		for iNdEx := len(m.Seqs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Seqs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSessionData(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SequenceState_Seq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SequenceState_Seq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SequenceState_Seq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LatestVal != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.LatestVal))
		i--
		dAtA[i] = 0x10
	}
	if m.SeqID != 0 {
		i = encodeVarintSessionData(dAtA, i, uint64(m.SeqID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSessionData(dAtA []byte, offset int, v uint64) int {
	offset -= sovSessionData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SessionData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Database)
	if l > 0 {
		n += 1 + l + sovSessionData(uint64(l))
	}
	l = len(m.ApplicationName)
	if l > 0 {
		n += 1 + l + sovSessionData(uint64(l))
	}
	l = len(m.UserProto)
	if l > 0 {
		n += 1 + l + sovSessionData(uint64(l))
	}
	l = m.DataConversionConfig.Size()
	n += 1 + l + sovSessionData(uint64(l))
	if m.VectorizeMode != 0 {
		n += 1 + sovSessionData(uint64(m.VectorizeMode))
	}
	if m.TestingVectorizeInjectPanics {
		n += 2
	}
	if m.DefaultIntSize != 0 {
		n += 1 + sovSessionData(uint64(m.DefaultIntSize))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovSessionData(uint64(l))
	}
	if len(m.SearchPath) > 0 {
		for _, s := range m.SearchPath {
			l = len(s)
			n += 1 + l + sovSessionData(uint64(l))
		}
	}
	l = len(m.TemporarySchemaName)
	if l > 0 {
		n += 1 + l + sovSessionData(uint64(l))
	}
	l = m.SeqState.Size()
	n += 1 + l + sovSessionData(uint64(l))
	if m.WorkMemLimit != 0 {
		n += 1 + sovSessionData(uint64(m.WorkMemLimit))
	}
	if m.IntervalStyleEnabled {
		n += 2
	}
	if m.DateStyleEnabled {
		n += 2
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.LockTimeout)
	n += 1 + l + sovSessionData(uint64(l))
	if m.Internal {
		n += 3
	}
	if m.OnUpdateRehomeRowEnabled {
		n += 3
	}
	if m.JoinReaderOrderingStrategyBatchSize != 0 {
		n += 2 + sovSessionData(uint64(m.JoinReaderOrderingStrategyBatchSize))
	}
	if m.ParallelizeMultiKeyLookupJoinsEnabled {
		n += 3
	}
	l = len(m.ActorScope)
	if l > 0 {
		n += 2 + l + sovSessionData(uint64(l))
	}
	if m.TroubleshootingMode {
		n += 3
	}
	if m.JoinReaderNoOrderingStrategyBatchSize != 0 {
		n += 2 + sovSessionData(uint64(m.JoinReaderNoOrderingStrategyBatchSize))
	}
	if m.JoinReaderIndexJoinStrategyBatchSize != 0 {
		n += 2 + sovSessionData(uint64(m.JoinReaderIndexJoinStrategyBatchSize))
	}
	return n
}

func (m *DataConversionConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BytesEncodeFormat != 0 {
		n += 1 + sovSessionData(uint64(m.BytesEncodeFormat))
	}
	if m.ExtraFloatDigits != 0 {
		n += 1 + sovSessionData(uint64(m.ExtraFloatDigits))
	}
	if m.IntervalStyle != 0 {
		n += 1 + sovSessionData(uint64(m.IntervalStyle))
	}
	l = m.DateStyle.Size()
	n += 1 + l + sovSessionData(uint64(l))
	return n
}

func (m *SequenceState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Seqs) > 0 {
		for _, e := range m.Seqs {
			l = e.Size()
			n += 1 + l + sovSessionData(uint64(l))
		}
	}
	if m.LastSeqIncremented != 0 {
		n += 1 + sovSessionData(uint64(m.LastSeqIncremented))
	}
	return n
}

func (m *SequenceState_Seq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SeqID != 0 {
		n += 1 + sovSessionData(uint64(m.SeqID))
	}
	if m.LatestVal != 0 {
		n += 1 + sovSessionData(uint64(m.LatestVal))
	}
	return n
}

func sovSessionData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSessionData(x uint64) (n int) {
	return sovSessionData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SessionData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SessionData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SessionData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Database", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Database = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApplicationName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserProto", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserProto = github_com_semistrict_ratel_pkg_security.SQLUsernameProto(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataConversionConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DataConversionConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VectorizeMode", wireType)
			}
			m.VectorizeMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VectorizeMode |= VectorizeExecMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestingVectorizeInjectPanics", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TestingVectorizeInjectPanics = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultIntSize", wireType)
			}
			m.DefaultIntSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultIntSize |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SearchPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SearchPath = append(m.SearchPath, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TemporarySchemaName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TemporarySchemaName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeqState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SeqState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkMemLimit", wireType)
			}
			m.WorkMemLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WorkMemLimit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntervalStyleEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IntervalStyleEnabled = bool(v != 0)
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DateStyleEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DateStyleEnabled = bool(v != 0)
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.LockTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Internal", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Internal = bool(v != 0)
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnUpdateRehomeRowEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OnUpdateRehomeRowEnabled = bool(v != 0)
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinReaderOrderingStrategyBatchSize", wireType)
			}
			m.JoinReaderOrderingStrategyBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JoinReaderOrderingStrategyBatchSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParallelizeMultiKeyLookupJoinsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ParallelizeMultiKeyLookupJoinsEnabled = bool(v != 0)
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActorScope", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActorScope = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TroubleshootingMode", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TroubleshootingMode = bool(v != 0)
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinReaderNoOrderingStrategyBatchSize", wireType)
			}
			m.JoinReaderNoOrderingStrategyBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JoinReaderNoOrderingStrategyBatchSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinReaderIndexJoinStrategyBatchSize", wireType)
			}
			m.JoinReaderIndexJoinStrategyBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JoinReaderIndexJoinStrategyBatchSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSessionData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataConversionConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataConversionConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataConversionConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BytesEncodeFormat", wireType)
			}
			m.BytesEncodeFormat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BytesEncodeFormat |= lex.BytesEncodeFormat(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraFloatDigits", wireType)
			}
			m.ExtraFloatDigits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExtraFloatDigits |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntervalStyle", wireType)
			}
			m.IntervalStyle = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IntervalStyle |= duration.IntervalStyle(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DateStyle", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DateStyle.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSessionData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SequenceState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SequenceState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SequenceState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seqs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSessionData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSessionData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seqs = append(m.Seqs, &SequenceState_Seq{})
			if err := m.Seqs[len(m.Seqs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSeqIncremented", wireType)
			}
			m.LastSeqIncremented = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastSeqIncremented |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSessionData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SequenceState_Seq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSessionData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Seq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Seq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeqID", wireType)
			}
			m.SeqID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SeqID |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestVal", wireType)
			}
			m.LatestVal = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestVal |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSessionData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSessionData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSessionData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSessionData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSessionData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSessionData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSessionData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSessionData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSessionData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSessionData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSessionData = fmt.Errorf("proto: unexpected end of group")
)
