// Copyright 2021 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

syntax = "proto3";
package cockroach.sql.sessiondatapb;
option go_package = "sessiondatapb";

import "gogoproto/gogo.proto";
import "sql/sessiondatapb/session_data.proto";
import "sql/sessiondatapb/local_only_session_data.proto";

// MigratableSession represents a serialization of a session that can be
// migrated between SQL sessions.
message MigratableSession {
  cockroach.sql.sessiondatapb.SessionData session_data = 1 [(gogoproto.nullable)=false];
  cockroach.sql.sessiondatapb.LocalOnlySessionData local_only_session_data = 2 [(gogoproto.nullable)=false];

  // PreparedStatement represents a prepared statement in a migratable session.
  message PreparedStatement {
    string name = 1;
    repeated uint32 placeholder_type_hints = 2 [
      (gogoproto.customtype)="github.com/lib/pq/oid.Oid"
    ];
    string sql = 3 [(gogoproto.customname)="SQL"];
  }
  repeated PreparedStatement prepared_statements = 3 [(gogoproto.nullable)=false];

}
