// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto

package loqrecoverypb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_semistrict_ratel_pkg_roachpb "github.com/semistrict/ratel/pkg/roachpb"
	roachpb "github.com/semistrict/ratel/pkg/roachpb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DescriptorChangeType int32

const (
	DescriptorChangeType_Split         DescriptorChangeType = 0
	DescriptorChangeType_Merge         DescriptorChangeType = 1
	DescriptorChangeType_ReplicaChange DescriptorChangeType = 2
)

var DescriptorChangeType_name = map[int32]string{
	0: "Split",
	1: "Merge",
	2: "ReplicaChange",
}

var DescriptorChangeType_value = map[string]int32{
	"Split":         0,
	"Merge":         1,
	"ReplicaChange": 2,
}

func (x DescriptorChangeType) String() string {
	return proto.EnumName(DescriptorChangeType_name, int32(x))
}

func (DescriptorChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a2cc96948b3cab0, []int{0}
}

// DescriptorChangeInfo future descriptor change info extracted from commit
// triggers in raft log.
type DescriptorChangeInfo struct {
	// Change type.
	ChangeType DescriptorChangeType `protobuf:"varint,1,opt,name=changeType,proto3,enum=cockroach.kv.kvserver.loqrecovery.loqrecoverypb.DescriptorChangeType" json:"changeType,omitempty"`
	// Range descriptor containing new state of for replica change updates and
	// LHS for split and merge operations.
	Desc *roachpb.RangeDescriptor `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// Optional range descriptor with is populated for split and merge changes
	// and contains RHS descriptor for the operation.
	OtherDesc *roachpb.RangeDescriptor `protobuf:"bytes,3,opt,name=otherDesc,proto3" json:"otherDesc,omitempty"`
}

func (m *DescriptorChangeInfo) Reset()         { *m = DescriptorChangeInfo{} }
func (m *DescriptorChangeInfo) String() string { return proto.CompactTextString(m) }
func (*DescriptorChangeInfo) ProtoMessage()    {}
func (*DescriptorChangeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a2cc96948b3cab0, []int{0}
}
func (m *DescriptorChangeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DescriptorChangeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *DescriptorChangeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescriptorChangeInfo.Merge(m, src)
}
func (m *DescriptorChangeInfo) XXX_Size() int {
	return m.Size()
}
func (m *DescriptorChangeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DescriptorChangeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DescriptorChangeInfo proto.InternalMessageInfo

// ReplicaInfo contains info about state of range replica for the purpose of range
// recovery. This information should be enough for recovery algorithm to pick a
// survivor replica in when not replicas are available.
// Information includes range descriptor as well as parts of raft state.
type ReplicaInfo struct {
	NodeID                   github_com_semistrict_ratel_pkg_roachpb.NodeID  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3,casttype=github.com/semistrict/ratel/pkg/roachpb.NodeID" json:"node_id,omitempty"`
	StoreID                  github_com_semistrict_ratel_pkg_roachpb.StoreID `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3,casttype=github.com/semistrict/ratel/pkg/roachpb.StoreID" json:"store_id,omitempty"`
	Desc                     roachpb.RangeDescriptor                         `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc"`
	RaftAppliedIndex         uint64                                          `protobuf:"varint,4,opt,name=raft_applied_index,json=raftAppliedIndex,proto3" json:"raft_applied_index,omitempty"`
	RaftCommittedIndex       uint64                                          `protobuf:"varint,5,opt,name=raft_committed_index,json=raftCommittedIndex,proto3" json:"raft_committed_index,omitempty"`
	RaftLogDescriptorChanges []DescriptorChangeInfo                          `protobuf:"bytes,6,rep,name=raft_log_descriptor_changes,json=raftLogDescriptorChanges,proto3" json:"raft_log_descriptor_changes,omitempty"`
}

func (m *ReplicaInfo) Reset()         { *m = ReplicaInfo{} }
func (m *ReplicaInfo) String() string { return proto.CompactTextString(m) }
func (*ReplicaInfo) ProtoMessage()    {}
func (*ReplicaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a2cc96948b3cab0, []int{1}
}
func (m *ReplicaInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplicaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ReplicaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaInfo.Merge(m, src)
}
func (m *ReplicaInfo) XXX_Size() int {
	return m.Size()
}
func (m *ReplicaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaInfo proto.InternalMessageInfo

// Collection of replica information gathered from a collect-info run on a single node.
type NodeReplicaInfo struct {
	Replicas []ReplicaInfo `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas"`
}

func (m *NodeReplicaInfo) Reset()         { *m = NodeReplicaInfo{} }
func (m *NodeReplicaInfo) String() string { return proto.CompactTextString(m) }
func (*NodeReplicaInfo) ProtoMessage()    {}
func (*NodeReplicaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a2cc96948b3cab0, []int{2}
}
func (m *NodeReplicaInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeReplicaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeReplicaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeReplicaInfo.Merge(m, src)
}
func (m *NodeReplicaInfo) XXX_Size() int {
	return m.Size()
}
func (m *NodeReplicaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeReplicaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeReplicaInfo proto.InternalMessageInfo

// ReplicaUpdate contains information that needs to be updated on replica on the node
// to make it a designated survivor so that replica could act as a source of truth when
// doing loss of quorum recovery.
type ReplicaUpdate struct {
	RangeID       github_com_semistrict_ratel_pkg_roachpb.RangeID   `protobuf:"varint,1,opt,name=range_id,json=rangeId,proto3,casttype=github.com/semistrict/ratel/pkg/roachpb.RangeID" json:"range_id,omitempty" yaml:"RangeID"`
	StartKey      RecoveryKey                                       `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3,casttype=RecoveryKey" json:"start_key,omitempty" yaml:"StartKey"`
	OldReplicaID  github_com_semistrict_ratel_pkg_roachpb.ReplicaID `protobuf:"varint,3,opt,name=old_replica_id,json=oldReplicaId,proto3,casttype=github.com/semistrict/ratel/pkg/roachpb.ReplicaID" json:"old_replica_id,omitempty" yaml:"OldReplicaID"`
	NewReplica    roachpb.ReplicaDescriptor                         `protobuf:"bytes,4,opt,name=new_replica,json=newReplica,proto3" json:"new_replica" yaml:"NewReplica"`
	NextReplicaID github_com_semistrict_ratel_pkg_roachpb.ReplicaID `protobuf:"varint,5,opt,name=next_replica_id,json=nextReplicaId,proto3,casttype=github.com/semistrict/ratel/pkg/roachpb.ReplicaID" json:"next_replica_id,omitempty" yaml:"NextReplicaID"`
}

func (m *ReplicaUpdate) Reset()      { *m = ReplicaUpdate{} }
func (*ReplicaUpdate) ProtoMessage() {}
func (*ReplicaUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a2cc96948b3cab0, []int{3}
}
func (m *ReplicaUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplicaUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ReplicaUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaUpdate.Merge(m, src)
}
func (m *ReplicaUpdate) XXX_Size() int {
	return m.Size()
}
func (m *ReplicaUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaUpdate proto.InternalMessageInfo

// ReplicaUpdatePlan Collection of updates for all recoverable replicas in the cluster.
type ReplicaUpdatePlan struct {
	Updates []ReplicaUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates"`
}

func (m *ReplicaUpdatePlan) Reset()         { *m = ReplicaUpdatePlan{} }
func (m *ReplicaUpdatePlan) String() string { return proto.CompactTextString(m) }
func (*ReplicaUpdatePlan) ProtoMessage()    {}
func (*ReplicaUpdatePlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a2cc96948b3cab0, []int{4}
}
func (m *ReplicaUpdatePlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplicaUpdatePlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ReplicaUpdatePlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaUpdatePlan.Merge(m, src)
}
func (m *ReplicaUpdatePlan) XXX_Size() int {
	return m.Size()
}
func (m *ReplicaUpdatePlan) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaUpdatePlan.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaUpdatePlan proto.InternalMessageInfo

// ReplicaRecoveryRecord is a struct that loss of quorum recovery commands
// write to the store locally when replicas are rewritten to preserve information
// about changes. This records are then consumed on startup to post data to
// appropriate destinations like log, rangelog etc.
// This struct is a union of all necessary information that is needed by all
// downstream destinations.
type ReplicaRecoveryRecord struct {
	// Timestamp of loss of quorum recovery application phase. Timestamp is chosen by process
	// rewriting changes before any replica is rewritten. All events created by single process
	// will share the same timestamp. Different processes updating different stores will
	// produce different timestamps even if updates originated from the same recovery plan.
	// Expressed as nanoseconds since the Unix epoch.
	Timestamp       int64                                             `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RangeID         github_com_semistrict_ratel_pkg_roachpb.RangeID   `protobuf:"varint,2,opt,name=range_id,json=rangeId,proto3,casttype=github.com/semistrict/ratel/pkg/roachpb.RangeID" json:"range_id,omitempty" yaml:"RangeID"`
	StartKey        RecoveryKey                                       `protobuf:"bytes,3,opt,name=start_key,json=startKey,proto3,casttype=RecoveryKey" json:"start_key,omitempty" yaml:"StartKey"`
	EndKey          RecoveryKey                                       `protobuf:"bytes,4,opt,name=end_key,json=endKey,proto3,casttype=RecoveryKey" json:"end_key,omitempty" yaml:"StartKey"`
	OldReplicaID    github_com_semistrict_ratel_pkg_roachpb.ReplicaID `protobuf:"varint,5,opt,name=old_replica_id,json=oldReplicaId,proto3,casttype=github.com/semistrict/ratel/pkg/roachpb.ReplicaID" json:"old_replica_id,omitempty" yaml:"OldReplicaID"`
	NewReplica      roachpb.ReplicaDescriptor                         `protobuf:"bytes,6,opt,name=new_replica,json=newReplica,proto3" json:"new_replica" yaml:"NewReplica"`
	RangeDescriptor roachpb.RangeDescriptor                           `protobuf:"bytes,7,opt,name=range_descriptor,json=rangeDescriptor,proto3" json:"range_descriptor" yaml:"RangeDescriptor"`
}

func (m *ReplicaRecoveryRecord) Reset()         { *m = ReplicaRecoveryRecord{} }
func (m *ReplicaRecoveryRecord) String() string { return proto.CompactTextString(m) }
func (*ReplicaRecoveryRecord) ProtoMessage()    {}
func (*ReplicaRecoveryRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a2cc96948b3cab0, []int{5}
}
func (m *ReplicaRecoveryRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReplicaRecoveryRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ReplicaRecoveryRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaRecoveryRecord.Merge(m, src)
}
func (m *ReplicaRecoveryRecord) XXX_Size() int {
	return m.Size()
}
func (m *ReplicaRecoveryRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaRecoveryRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaRecoveryRecord proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cockroach.kv.kvserver.loqrecovery.loqrecoverypb.DescriptorChangeType", DescriptorChangeType_name, DescriptorChangeType_value)
	proto.RegisterType((*DescriptorChangeInfo)(nil), "cockroach.kv.kvserver.loqrecovery.loqrecoverypb.DescriptorChangeInfo")
	proto.RegisterType((*ReplicaInfo)(nil), "cockroach.kv.kvserver.loqrecovery.loqrecoverypb.ReplicaInfo")
	proto.RegisterType((*NodeReplicaInfo)(nil), "cockroach.kv.kvserver.loqrecovery.loqrecoverypb.NodeReplicaInfo")
	proto.RegisterType((*ReplicaUpdate)(nil), "cockroach.kv.kvserver.loqrecovery.loqrecoverypb.ReplicaUpdate")
	proto.RegisterType((*ReplicaUpdatePlan)(nil), "cockroach.kv.kvserver.loqrecovery.loqrecoverypb.ReplicaUpdatePlan")
	proto.RegisterType((*ReplicaRecoveryRecord)(nil), "cockroach.kv.kvserver.loqrecovery.loqrecoverypb.ReplicaRecoveryRecord")
}

func init() {
	proto.RegisterFile("kv/kvserver/loqrecovery/loqrecoverypb/recovery.proto", fileDescriptor_5a2cc96948b3cab0)
}

var fileDescriptor_5a2cc96948b3cab0 = []byte{
	// 893 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcf, 0x6f, 0xdc, 0x44,
	0x14, 0x5e, 0x67, 0xbd, 0xbb, 0xc9, 0x6c, 0x7e, 0x6c, 0x86, 0x50, 0x99, 0x82, 0xec, 0xc8, 0x02,
	0x29, 0x42, 0xc5, 0x86, 0x80, 0x38, 0x94, 0xa8, 0x85, 0x6d, 0x38, 0xac, 0x0a, 0xa1, 0x72, 0xe8,
	0x01, 0x84, 0xb2, 0x38, 0x9e, 0x57, 0xc7, 0x5a, 0xdb, 0xe3, 0x8e, 0xa7, 0xdb, 0xec, 0x95, 0x03,
	0x67, 0x24, 0x2e, 0x1c, 0xf9, 0x1f, 0xfa, 0x4f, 0xe4, 0xd8, 0x63, 0x4f, 0x16, 0x38, 0x37, 0x8e,
	0x39, 0x80, 0xc4, 0x09, 0xcd, 0xd8, 0xde, 0xf5, 0x96, 0x1f, 0xda, 0x44, 0x15, 0x3d, 0xed, 0xcc,
	0x7b, 0xef, 0xfb, 0xde, 0x7b, 0x7e, 0xdf, 0xf3, 0x1a, 0x7d, 0x30, 0x1a, 0xdb, 0xa3, 0x71, 0x0a,
	0x6c, 0x0c, 0xcc, 0x0e, 0xe9, 0x43, 0x06, 0x1e, 0x1d, 0x03, 0x9b, 0xd4, 0xcf, 0xc9, 0xb1, 0x5d,
	0x1d, 0xad, 0x84, 0x51, 0x4e, 0xb1, 0xed, 0x51, 0x6f, 0xc4, 0xa8, 0xeb, 0x9d, 0x58, 0xa3, 0xb1,
	0x55, 0xe1, 0xad, 0x1a, 0xc6, 0x9a, 0xc3, 0x5f, 0xbf, 0x26, 0x83, 0x93, 0x63, 0x3b, 0x02, 0xee,
	0x12, 0x97, 0xbb, 0x05, 0xd1, 0xf5, 0x2d, 0x9f, 0xfa, 0x54, 0x1e, 0x6d, 0x71, 0x2a, 0xac, 0xe6,
	0x1f, 0x0a, 0xda, 0xda, 0x87, 0xd4, 0x63, 0x41, 0xc2, 0x29, 0xbb, 0x73, 0xe2, 0xc6, 0x3e, 0x0c,
	0xe2, 0x07, 0x14, 0x03, 0x42, 0x9e, 0xbc, 0x7d, 0x39, 0x49, 0x40, 0x53, 0xb6, 0x95, 0x9d, 0xf5,
	0xdd, 0x4f, 0xad, 0x4b, 0x16, 0x63, 0x3d, 0x4f, 0x2d, 0xc8, 0x9c, 0x1a, 0x31, 0xfe, 0x10, 0xa9,
	0x04, 0x52, 0x4f, 0x5b, 0xda, 0x56, 0x76, 0xba, 0xbb, 0x66, 0x2d, 0x41, 0xd9, 0x86, 0xe5, 0x88,
	0xd8, 0x19, 0x8f, 0x23, 0xe3, 0xf1, 0xc7, 0x68, 0x85, 0xf2, 0x13, 0x60, 0xc2, 0xa1, 0x35, 0x17,
	0x06, 0xcf, 0x40, 0xe6, 0x8f, 0x2a, 0xea, 0x3a, 0x90, 0x84, 0x81, 0xe7, 0xca, 0x86, 0xef, 0xa3,
	0x4e, 0x4c, 0x09, 0x0c, 0x03, 0x22, 0xbb, 0x6d, 0xf5, 0xf7, 0xf2, 0xcc, 0x68, 0x1f, 0x50, 0x02,
	0x83, 0xfd, 0x3f, 0x33, 0xc3, 0xf2, 0x03, 0x7e, 0xf2, 0xe8, 0xd8, 0xf2, 0x68, 0x64, 0xa7, 0x10,
	0x05, 0x29, 0x67, 0x81, 0xc7, 0x6d, 0xe6, 0x72, 0x08, 0xed, 0x64, 0xe4, 0xdb, 0x55, 0xca, 0x02,
	0xe1, 0xb4, 0x05, 0xd9, 0x80, 0xe0, 0xaf, 0xd0, 0x72, 0xca, 0x29, 0x93, 0xbc, 0x4b, 0x92, 0xf7,
	0x56, 0x9e, 0x19, 0x9d, 0x43, 0x61, 0x93, 0xc4, 0xf6, 0xa2, 0xc4, 0x25, 0xc4, 0xe9, 0x48, 0xbe,
	0x01, 0xc1, 0x7b, 0xe5, 0xb3, 0x5b, 0xb8, 0xfd, 0xbe, 0x7a, 0x96, 0x19, 0x8d, 0xf2, 0x09, 0xde,
	0x40, 0x98, 0xb9, 0x0f, 0xf8, 0xd0, 0x4d, 0x92, 0x30, 0x00, 0x32, 0x0c, 0x62, 0x02, 0xa7, 0x9a,
	0xba, 0xad, 0xec, 0xa8, 0x4e, 0x4f, 0x78, 0x3e, 0x29, 0x1c, 0x03, 0x61, 0xc7, 0xef, 0xa2, 0x2d,
	0x19, 0xed, 0xd1, 0x28, 0x0a, 0x38, 0x9f, 0xc6, 0xb7, 0x64, 0xbc, 0x64, 0xba, 0x53, 0xb9, 0x0a,
	0xc4, 0x13, 0x05, 0xbd, 0x2e, 0x21, 0x21, 0xf5, 0x87, 0x64, 0x5a, 0xc3, 0xb0, 0x18, 0x7e, 0xaa,
	0xb5, 0xb7, 0x9b, 0x3b, 0xdd, 0x17, 0x20, 0x29, 0x31, 0xbc, 0xfe, 0x3b, 0xa2, 0xb1, 0xdf, 0x32,
	0xe3, 0xad, 0xff, 0xc8, 0x78, 0x83, 0x46, 0x01, 0x87, 0x28, 0xe1, 0x13, 0x47, 0x13, 0x61, 0x9f,
	0x51, 0xff, 0x79, 0xae, 0xd4, 0x7c, 0x88, 0x36, 0xc4, 0x00, 0xeb, 0xc2, 0x38, 0x42, 0xcb, 0xac,
	0xb8, 0xa6, 0x9a, 0x22, 0x8b, 0xde, 0xbb, 0x74, 0xd1, 0x35, 0xbe, 0x72, 0x08, 0x53, 0x4e, 0xf3,
	0x89, 0x8a, 0xd6, 0x4a, 0xff, 0xfd, 0x84, 0xb8, 0x1c, 0xf0, 0x08, 0x2d, 0x33, 0x51, 0x4e, 0xa5,
	0xc5, 0x66, 0xff, 0x9e, 0xd0, 0x8c, 0x9c, 0xe6, 0x60, 0xff, 0x22, 0x33, 0xd6, 0x27, 0x6e, 0x14,
	0xde, 0x34, 0x4b, 0x83, 0x79, 0x19, 0x15, 0x95, 0x18, 0xa7, 0x23, 0x33, 0x0c, 0x08, 0xbe, 0x8d,
	0x56, 0x52, 0xee, 0x32, 0x3e, 0x1c, 0xc1, 0x44, 0x2a, 0x74, 0xb5, 0x6f, 0x5e, 0x64, 0xc6, 0x46,
	0x91, 0xe2, 0x50, 0xb8, 0xee, 0xc2, 0x44, 0xe4, 0xe8, 0x3a, 0x65, 0x43, 0x77, 0x61, 0xe2, 0x2c,
	0xa7, 0xa5, 0x07, 0x7f, 0xa7, 0xa0, 0x75, 0x1a, 0x92, 0x61, 0xd9, 0x90, 0x28, 0xba, 0x29, 0x85,
	0xfe, 0x4d, 0x9e, 0x19, 0xab, 0x5f, 0x84, 0xa4, 0x6a, 0x5e, 0x54, 0xfe, 0x4a, 0x41, 0x5b, 0xb7,
	0x0a, 0xea, 0xf7, 0x16, 0x2e, 0xbf, 0x42, 0x39, 0xab, 0x74, 0xc6, 0x41, 0xf0, 0xb7, 0xa8, 0x1b,
	0xc3, 0xe3, 0xaa, 0x06, 0x29, 0xe3, 0xee, 0xee, 0x9b, 0xff, 0xb4, 0x12, 0x45, 0x44, 0x6d, 0x29,
	0x5e, 0x13, 0xf3, 0xb8, 0xc8, 0x8c, 0xcd, 0xa2, 0xb4, 0x03, 0x78, 0x5c, 0xc6, 0x98, 0x0e, 0x8a,
	0xa7, 0x17, 0xfc, 0xbd, 0x82, 0x36, 0x62, 0x38, 0xe5, 0xf5, 0x3e, 0x5b, 0xb2, 0xcf, 0xa3, 0x3c,
	0x33, 0xd6, 0x0e, 0xe0, 0x94, 0xd7, 0x1b, 0xdd, 0xaa, 0xd8, 0x6a, 0xe6, 0x2b, 0x76, 0xba, 0x16,
	0xd7, 0x48, 0xc8, 0x4d, 0xf5, 0xa7, 0x9f, 0x8d, 0x86, 0x99, 0xa2, 0xcd, 0x39, 0xd1, 0xdc, 0x0b,
	0xdd, 0x18, 0x1f, 0xa1, 0xce, 0x23, 0x79, 0xab, 0x94, 0x7a, 0xeb, 0xaa, 0x4a, 0x2d, 0x48, 0x4b,
	0xad, 0x56, 0xa4, 0xe6, 0xef, 0x2a, 0x7a, 0xb5, 0x0c, 0xa8, 0xb4, 0x20, 0x7e, 0x19, 0xc1, 0x6f,
	0xa0, 0x15, 0x1e, 0x44, 0x90, 0x72, 0x37, 0x4a, 0x0a, 0xcd, 0x3a, 0x33, 0xc3, 0x9c, 0xa0, 0x97,
	0xfe, 0x57, 0x41, 0x37, 0xaf, 0x20, 0xe8, 0x8f, 0x50, 0x07, 0x62, 0x22, 0xe1, 0xea, 0xc2, 0xf0,
	0x36, 0xc4, 0xe4, 0x5f, 0xb6, 0xa1, 0xf5, 0xb2, 0xb7, 0xa1, 0xfd, 0xe2, 0xb7, 0x21, 0x42, 0xbd,
	0x62, 0xa2, 0xb3, 0xf7, 0xac, 0xd6, 0x59, 0xf8, 0x7f, 0x48, 0x2f, 0x93, 0x5c, 0xab, 0x8d, 0x7d,
	0xe6, 0x36, 0x9d, 0x0d, 0x36, 0x6f, 0x79, 0xfb, 0xf6, 0xdf, 0xbf, 0x52, 0xe4, 0xe7, 0xc3, 0x0a,
	0x6a, 0x1d, 0x26, 0x61, 0xc0, 0x7b, 0x0d, 0x71, 0xfc, 0x1c, 0x98, 0x0f, 0x3d, 0x05, 0x6f, 0x4e,
	0x5f, 0xa8, 0x45, 0x68, 0x6f, 0xa9, 0x6f, 0x9f, 0xfd, 0xaa, 0x37, 0xce, 0x72, 0x5d, 0x79, 0x9a,
	0xeb, 0xca, 0xb3, 0x5c, 0x57, 0x7e, 0xc9, 0x75, 0xe5, 0x87, 0x73, 0xbd, 0xf1, 0xf4, 0x5c, 0x6f,
	0x3c, 0x3b, 0xd7, 0x1b, 0x5f, 0xaf, 0xcd, 0xed, 0xc1, 0x71, 0x5b, 0x7e, 0x1f, 0xbd, 0xff, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x6e, 0xae, 0x81, 0xb6, 0x09, 0x00, 0x00,
}

func (m *DescriptorChangeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DescriptorChangeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DescriptorChangeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OtherDesc != nil {
		{
			size, err := m.OtherDesc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRecovery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Desc != nil {
		{
			size, err := m.Desc.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRecovery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ChangeType != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.ChangeType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReplicaInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplicaInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplicaInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RaftLogDescriptorChanges) > 0 {
		for iNdEx := len(m.RaftLogDescriptorChanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RaftLogDescriptorChanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRecovery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.RaftCommittedIndex != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.RaftCommittedIndex))
		i--
		dAtA[i] = 0x28
	}
	if m.RaftAppliedIndex != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.RaftAppliedIndex))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.Desc.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRecovery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.StoreID != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.StoreID))
		i--
		dAtA[i] = 0x10
	}
	if m.NodeID != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.NodeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NodeReplicaInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeReplicaInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeReplicaInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Replicas) > 0 {
		for iNdEx := len(m.Replicas) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Replicas[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRecovery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ReplicaUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplicaUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplicaUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextReplicaID != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.NextReplicaID))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.NewReplica.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRecovery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.OldReplicaID != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.OldReplicaID))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StartKey) > 0 {
		i -= len(m.StartKey)
		copy(dAtA[i:], m.StartKey)
		i = encodeVarintRecovery(dAtA, i, uint64(len(m.StartKey)))
		i--
		dAtA[i] = 0x12
	}
	if m.RangeID != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.RangeID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ReplicaUpdatePlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplicaUpdatePlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplicaUpdatePlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Updates) > 0 {
		for iNdEx := len(m.Updates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Updates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRecovery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ReplicaRecoveryRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReplicaRecoveryRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReplicaRecoveryRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RangeDescriptor.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRecovery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.NewReplica.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintRecovery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.OldReplicaID != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.OldReplicaID))
		i--
		dAtA[i] = 0x28
	}
	if len(m.EndKey) > 0 {
		i -= len(m.EndKey)
		copy(dAtA[i:], m.EndKey)
		i = encodeVarintRecovery(dAtA, i, uint64(len(m.EndKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StartKey) > 0 {
		i -= len(m.StartKey)
		copy(dAtA[i:], m.StartKey)
		i = encodeVarintRecovery(dAtA, i, uint64(len(m.StartKey)))
		i--
		dAtA[i] = 0x1a
	}
	if m.RangeID != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.RangeID))
		i--
		dAtA[i] = 0x10
	}
	if m.Timestamp != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRecovery(dAtA []byte, offset int, v uint64) int {
	offset -= sovRecovery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DescriptorChangeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChangeType != 0 {
		n += 1 + sovRecovery(uint64(m.ChangeType))
	}
	if m.Desc != nil {
		l = m.Desc.Size()
		n += 1 + l + sovRecovery(uint64(l))
	}
	if m.OtherDesc != nil {
		l = m.OtherDesc.Size()
		n += 1 + l + sovRecovery(uint64(l))
	}
	return n
}

func (m *ReplicaInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NodeID != 0 {
		n += 1 + sovRecovery(uint64(m.NodeID))
	}
	if m.StoreID != 0 {
		n += 1 + sovRecovery(uint64(m.StoreID))
	}
	l = m.Desc.Size()
	n += 1 + l + sovRecovery(uint64(l))
	if m.RaftAppliedIndex != 0 {
		n += 1 + sovRecovery(uint64(m.RaftAppliedIndex))
	}
	if m.RaftCommittedIndex != 0 {
		n += 1 + sovRecovery(uint64(m.RaftCommittedIndex))
	}
	if len(m.RaftLogDescriptorChanges) > 0 {
		for _, e := range m.RaftLogDescriptorChanges {
			l = e.Size()
			n += 1 + l + sovRecovery(uint64(l))
		}
	}
	return n
}

func (m *NodeReplicaInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Replicas) > 0 {
		for _, e := range m.Replicas {
			l = e.Size()
			n += 1 + l + sovRecovery(uint64(l))
		}
	}
	return n
}

func (m *ReplicaUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RangeID != 0 {
		n += 1 + sovRecovery(uint64(m.RangeID))
	}
	l = len(m.StartKey)
	if l > 0 {
		n += 1 + l + sovRecovery(uint64(l))
	}
	if m.OldReplicaID != 0 {
		n += 1 + sovRecovery(uint64(m.OldReplicaID))
	}
	l = m.NewReplica.Size()
	n += 1 + l + sovRecovery(uint64(l))
	if m.NextReplicaID != 0 {
		n += 1 + sovRecovery(uint64(m.NextReplicaID))
	}
	return n
}

func (m *ReplicaUpdatePlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Updates) > 0 {
		for _, e := range m.Updates {
			l = e.Size()
			n += 1 + l + sovRecovery(uint64(l))
		}
	}
	return n
}

func (m *ReplicaRecoveryRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovRecovery(uint64(m.Timestamp))
	}
	if m.RangeID != 0 {
		n += 1 + sovRecovery(uint64(m.RangeID))
	}
	l = len(m.StartKey)
	if l > 0 {
		n += 1 + l + sovRecovery(uint64(l))
	}
	l = len(m.EndKey)
	if l > 0 {
		n += 1 + l + sovRecovery(uint64(l))
	}
	if m.OldReplicaID != 0 {
		n += 1 + sovRecovery(uint64(m.OldReplicaID))
	}
	l = m.NewReplica.Size()
	n += 1 + l + sovRecovery(uint64(l))
	l = m.RangeDescriptor.Size()
	n += 1 + l + sovRecovery(uint64(l))
	return n
}

func sovRecovery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRecovery(x uint64) (n int) {
	return sovRecovery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DescriptorChangeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRecovery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DescriptorChangeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DescriptorChangeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChangeType", wireType)
			}
			m.ChangeType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChangeType |= DescriptorChangeType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Desc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Desc == nil {
				m.Desc = &roachpb.RangeDescriptor{}
			}
			if err := m.Desc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OtherDesc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OtherDesc == nil {
				m.OtherDesc = &roachpb.RangeDescriptor{}
			}
			if err := m.OtherDesc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRecovery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRecovery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReplicaInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRecovery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplicaInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplicaInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			m.NodeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NodeID |= github_com_semistrict_ratel_pkg_roachpb.NodeID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreID", wireType)
			}
			m.StoreID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StoreID |= github_com_semistrict_ratel_pkg_roachpb.StoreID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Desc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Desc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftAppliedIndex", wireType)
			}
			m.RaftAppliedIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftAppliedIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftCommittedIndex", wireType)
			}
			m.RaftCommittedIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RaftCommittedIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RaftLogDescriptorChanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RaftLogDescriptorChanges = append(m.RaftLogDescriptorChanges, DescriptorChangeInfo{})
			if err := m.RaftLogDescriptorChanges[len(m.RaftLogDescriptorChanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRecovery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRecovery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeReplicaInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRecovery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeReplicaInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeReplicaInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicas", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Replicas = append(m.Replicas, ReplicaInfo{})
			if err := m.Replicas[len(m.Replicas)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRecovery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRecovery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReplicaUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRecovery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplicaUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplicaUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RangeID", wireType)
			}
			m.RangeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RangeID |= github_com_semistrict_ratel_pkg_roachpb.RangeID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartKey = append(m.StartKey[:0], dAtA[iNdEx:postIndex]...)
			if m.StartKey == nil {
				m.StartKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldReplicaID", wireType)
			}
			m.OldReplicaID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldReplicaID |= github_com_semistrict_ratel_pkg_roachpb.ReplicaID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewReplica", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewReplica.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextReplicaID", wireType)
			}
			m.NextReplicaID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextReplicaID |= github_com_semistrict_ratel_pkg_roachpb.ReplicaID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRecovery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRecovery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReplicaUpdatePlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRecovery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplicaUpdatePlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplicaUpdatePlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Updates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Updates = append(m.Updates, ReplicaUpdate{})
			if err := m.Updates[len(m.Updates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRecovery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRecovery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReplicaRecoveryRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRecovery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReplicaRecoveryRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReplicaRecoveryRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RangeID", wireType)
			}
			m.RangeID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RangeID |= github_com_semistrict_ratel_pkg_roachpb.RangeID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartKey = append(m.StartKey[:0], dAtA[iNdEx:postIndex]...)
			if m.StartKey == nil {
				m.StartKey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndKey = append(m.EndKey[:0], dAtA[iNdEx:postIndex]...)
			if m.EndKey == nil {
				m.EndKey = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldReplicaID", wireType)
			}
			m.OldReplicaID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OldReplicaID |= github_com_semistrict_ratel_pkg_roachpb.ReplicaID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewReplica", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewReplica.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RangeDescriptor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RangeDescriptor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRecovery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRecovery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRecovery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRecovery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRecovery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRecovery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRecovery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRecovery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRecovery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRecovery = fmt.Errorf("proto: unexpected end of group")
)
