// Copyright 2021 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

package a

import "fmt"

// In the main source code, embedded.go files are generated by go-bindata.

func init() {
	_ = recover()

	_ = fmt.Errorf(wrappedErr.Error())              // linting is skipped.
	_ = fmt.Errorf("format %s", wrappedErr.Error()) // linting is skipped.

	_ = fmt.Errorf("got %s", wrappedErr) // linting is skipped.
	_ = fmt.Errorf("got %v", wrappedErr) // linting is skipped.
}
