// Copyright 2022 The Cockroach Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing
// permissions and limitations under the License.

package kvserverbase

import "fmt"

// RaftCommandEncodingVersion versions CockroachDB's raft entries.
type RaftCommandEncodingVersion byte

// Raft commands are encoded with a 1-byte version (currently 0 or 1), an 8-byte
// ID, followed by the payload. This inflexible encoding is used so we can
// efficiently parse the command id while processing the logs.
//
// TODO(bdarnell): is this commandID still appropriate for our needs?
const (
	// RaftVersionStandard is the initial Raft command version, used for all regular Raft traffic.
	RaftVersionStandard RaftCommandEncodingVersion = 0
	// RaftVersionSideloaded indicates a proposal containing an SSTable which
	// preferably should be sideloaded (i.e. not stored in the Raft log
	// wholesale). Can be treated as a regular proposal when arriving on the wire,
	// but when retrieved from the local Raft log it necessary to inline the
	// payload first as it has usually been sideloaded.
	RaftVersionSideloaded RaftCommandEncodingVersion = 1
	// RaftCommandIDLen is the length for each command ID.
	RaftCommandIDLen = 8
	// RaftCommandPrefixLen is the prescribed length of each encoded command's prefix.
	RaftCommandPrefixLen = 1 + RaftCommandIDLen
	// RaftCommandNoSplitBit is deprecated.
	// The no-split bit is now unused, but we still apply the mask to the first
	// byte of the command for backward compatibility.
	//
	// TODO(tschottdorf): predates v1.0 by a significant margin. Remove.
	RaftCommandNoSplitBit = 1 << 7
	// RaftCommandNoSplitMask is deprecated.
	RaftCommandNoSplitMask = RaftCommandNoSplitBit - 1
)

// EncodeRaftCommand encodes a raft command (including the versioning prefix).
func EncodeRaftCommand(
	version RaftCommandEncodingVersion, commandID CmdIDKey, command []byte,
) []byte {
	b := make([]byte, RaftCommandPrefixLen+len(command))
	EncodeRaftCommandPrefix(b[:RaftCommandPrefixLen], version, commandID)
	copy(b[RaftCommandPrefixLen:], command)
	return b
}

// EncodeRaftCommandPrefix encodes the versioning prefix for a Raft command.
func EncodeRaftCommandPrefix(b []byte, version RaftCommandEncodingVersion, commandID CmdIDKey) {
	if len(commandID) != RaftCommandIDLen {
		panic(fmt.Sprintf("invalid command ID length; %d != %d", len(commandID), RaftCommandIDLen))
	}
	if len(b) != RaftCommandPrefixLen {
		panic(fmt.Sprintf("invalid command prefix length; %d != %d", len(b), RaftCommandPrefixLen))
	}
	b[0] = byte(version)
	copy(b[1:], []byte(commandID))
}

// DecodeRaftCommand splits a raftpb.Entry.Data into its commandID and
// command portions. The caller is responsible for checking that the data
// is not empty (which indicates a dummy entry generated by raft rather
// than a real command). Usage is mostly internal to the storage package
// but is exported for use by debugging tools.
func DecodeRaftCommand(data []byte) (CmdIDKey, []byte) {
	v := RaftCommandEncodingVersion(data[0] & RaftCommandNoSplitMask)
	if v != RaftVersionStandard && v != RaftVersionSideloaded {
		panic(fmt.Sprintf("unknown command encoding version %v", data[0]))
	}
	return CmdIDKey(data[1 : 1+RaftCommandIDLen]), data[1+RaftCommandIDLen:]
}

// EncodeTestRaftCommand encodes provided command as raft command by adding
// appropriate prefix to the data. It is only used for testing to create test
// raft log entries. No correctness guarantees are provided.
//
// See: #75729
func EncodeTestRaftCommand(command []byte, commandID CmdIDKey) []byte {
	return EncodeRaftCommand(RaftVersionStandard, commandID, command)
}
